### ISSUE TITLE
Snap Question

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel4#1]
Hello again, I just saw that you released to beta and thought id finally try and swap out my jspanel 3 with the 4.

If you remember from our conversation in the v3 git i mentioned something about using the mouse cursor instead of the panel coords to trigger the sticking.

Do you happen to have some of your old code when you tried that technique?  I am guessing the following needs changing:

`const pmx = e.touches ? e.touches[0].clientX : e.clientX,	// current pointer x while pointer moves (don't use pageY, doesn't work on FF for Android)
                            pmy = e.touches ? e.touches[0].clientY : e.clientY,	    // current pointer y while pointer moves (don't use pageY, doesn't work on FF for Android)
                            dragStyles = window.getComputedStyle(elmt),             // get current styles while draging
                            elmtL = parseFloat(dragStyles.left),
                            elmtL2 = elmtL ** 2,
                            elmtT = parseFloat(dragStyles.top),
                            elmtT2 =  elmtT ** 2,
                            elmtR = parseFloat(dragStyles.right),
                            elmtR2 = elmtR ** 2,
                            elmtB = parseFloat(dragStyles.bottom),
                            elmtB2 = elmtB ** 2,
                            lefttopVectorDrag     = Math.sqrt(elmtL2 + elmtT2),
                            leftbottomVectorDrag  = Math.sqrt(elmtL2 + elmtB2),
                            righttopVectorDrag    = Math.sqrt(elmtR2 + elmtT2),
                            rightbottomVectorDrag = Math.sqrt(elmtR2 + elmtB2),
                            horizontalDeltaDrag = Math.abs(elmtL - elmtR)/2,
                            verticalDeltaDrag   = Math.abs(elmtT - elmtB)/2,
                            leftVectorDrag   = Math.sqrt(elmtL2 + verticalDeltaDrag ** 2),
                            topVectorDrag    = Math.sqrt(elmtT2 + horizontalDeltaDrag ** 2),
                            rightVectorDrag  = Math.sqrt(elmtR2 + verticalDeltaDrag ** 2),
                            bottomVectorDrag = Math.sqrt(elmtB2 + horizontalDeltaDrag ** 2);`

I tried with the current solution which seems to work great for small panels but when i use it for my large ones (they are pretty much full screen with a small margin) its hard to pick which snap zone you want it to go to (since they all basically almost touch the zone already). 

Thanks,

**Comment by Flyer53** [comment]
Hi again :)
I never used the pointer position to trigger the snap. Always a reference point of the panel. But I see that this is a problem when the panel is almost filling the screen already. Might have to rethink this and admit that I always used "normally" sized panel to do the testing. 

Let me think about this a bit ... using pointer position instead would solve this, I know ...

**Comment by whittssg** [comment]
:) maybe an option to choose mouse coords or panel edges as the trigger since i think the edges works great for 'normal' size panels. Thanks

**Comment by whittssg** [comment]
Great release by the way.. looks great - glad i can finally get rid of Jquery UI

**Comment by Flyer53** [comment]
Ok, there is a testfile incorporating a new setting trigger for the snap feature:
```javascript
jsPanel.create({
    dragit: {
        snap: {
            trigger: 'pointer' // defaults to 'panel'
        }
    }
});
```
trigger defaults to **'panel'** and can be set to **'pointer'** in order to make the pointer position the trigger for the snap action.
Download testfile from http://jspanel.de/downloads/jspanel-4-beta.1.1.zip
The zip containsis only the compiled unminified jspanel.js

Give it a try and let me know how it works out.

**Comment by whittssg** [comment]
Seems to work great. Thanks a lot  :smile:

**Comment by Flyer53** [comment]
I worked again on the snap feature and added the parameters
+ containment
+ repositionOnSnap

to the snap configuration.

Take a look at http://alpha.jspanel.de/docs/#options/dragit - especially example 6
http://jspanel.de/downloads/jspanel-4-beta.1.12.zip

**Comment by itpmngt** [comment]
Just a thought: I wonder if 'snapping' could be enhanced to 'docking' - as we have in most of the IDEs - where a panel assumes predefined-default positioning/sizing values?

jsPanel is enabling me to shift some of my programming paradigms with the interesting concept of closing functionality in a panel - becoming a web-component positioned in page. Being following trends like Angular, Reactive, Web-components, etcetera, but they become 'opinionated frameworks' - maybe 'docked-panels' could become an alternative - just a thought!!! 

Best

**Comment by Flyer53** [comment]
@itpmngt 
Thoughts are alyways welcome of course 😄 
What exactly do have in mind talking about **docking**? Lately I did some work on the snap feature and just updated the http://jspanel.de/docs/#options/dragit docs including two new examples. Take a look at example 6 and try all the positions a panel can snap to. I thought this is already sort of a docking feature.

But whatever you have in mind ... don't hesitate to tell me, I'm always grateful for feedback.

Beat regards,
Stefan

PS: Will probably release a beta 2 this week.

**Comment by whittssg** [comment]
The resizeToPreSnap is working really well now.. Just implemented it (had a nice surprise though with the new contentSize needing a function but fixed it quickly) and now i see that after you drag it out of snap the panel moves to your cursor position (which i think it didnt on previous tests)... Works perfect now - thanks for all your hard work :)

**Comment by whittssg** [comment]
In regards to the docking... I personally feel this should stay separated from 'real' docking since other libraries exist like https://golden-layout.com/ ... I think i will try and integrate golden layout at some point with this plugin since i love jspanels panels and love golden layouts docking - so when you click the popout  icon on golden layout it opens a jspanel instead of an entirely new chome window. 

At the moment i am not using golden layout at all since its seems to be a pain to get it working with angular 1.x but jspanel works like a dream

**Comment by Flyer53** [comment]
@whittssg 
My pleasure ... and very pleased to hear this 😄 
Concerning **docking** I agree with you. The ideas what a docking feature should look like vary widely and I won't be able to make it right for everyone. And anyhow, with some creative thinking there's a lot possible with jsPanel already.
Playing around a bit I came up with the following code that sort of "glues" 2 panels together. Drag either panel, resize the master panel and work the controls of the master panel.
Just an idea with lots of room for individual ideas ...
```javascript
var p1, p2;

p1 = jsPanel.create({
    id: 'panelMaster',
    position: 'left-top 20 20',
    theme: 'primary',
    headerTitle: 'Master',
    maximizedMargin: [20, 340, 20, 20],
    dragit: {
        drag: function () {
            if (document.querySelector('#panelSlave')) {
                p2.reposition(); // no arg needed because reposition() by default uses position set in option.position
            }
        }
    },
    resizeit: {
        resize: function (panel, size) {
            if (document.querySelector('#panelSlave')) {
                p2.reposition();
                p2.resize({
                    height: size.height + 'px'
                });
            }
        }
    },
    onmaximized: function () {
        if (document.querySelector('#panelSlave')) {
            p2.reposition();
            p2.resize({
                height: p1.style.height
            });
            p2.dragit('disable');
        }
    },
    onminimized: function () {
        if (document.querySelector('#panelSlave')) {
            p2.minimize();
        }
    },
    onnormalized: function () {
        if (document.querySelector('#panelSlave')) {
            p2.normalize();
            p2.reposition();
            p2.resize({
                height: p1.style.height
            });
            p2.dragit('enable');
        }
    },
    onsmallified: function () {
        if (document.querySelector('#panelSlave')) {
            p2.smallify();
        }
    },
    onunsmallified: function () {
        if (document.querySelector('#panelSlave')) {
            p2.unsmallify();
        }
    },
    onclosed: function () {
        if (document.querySelector('#panelSlave')) {
            p2.close();
        }
    }
});
p2 = jsPanel.create({
    id: 'panelSlave',
    position: {
        my: 'left-top',
        at: 'right-top',
        of: p1,
        offsetX: 5
    },
    theme: 'success',
    headerTitle: 'Slave',
    headerControls: 'closeonly',
    contentSize: '300 200',
    minimizeTo: false,
    dragit: {
        drag: function () {
            p1.reposition({
                my: 'right-top',
                at: 'left-top',
                of: p2,
                offsetX: -5
            });
        }
    },
    resizeit: false
});
```
