### ISSUE TITLE
the right way to trig jspanel

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#10]
Hi stafen
I hope that I found the way to issue the panel in all the environments,
I well be happy to get your approval or yours comments .
1) I define field that have the events 
`var uEvent = 'click tap touchstart';`

2) With this string I trig all the events

3) In the callback 
  ```javascript
function (p) {
	$('#btn-close').on(uEvent, function (e) {
		$('#traceevent2').html('e.type : ' + e.type);
		e.preventDefault();
		e.stopPropagation();
		p.close();
		return false;
	});
}
```
yours
Avi

**Comment by Flyer53** [comment]
Hi Avi,
I took the freedom to reformat your code sample so it's better readable.

**Two questions:**
1. Unless you created a custom event I'm not aware that javascript has a tap event??
2. If I understand you, you have a jsPanel and somewhere in the document a button that will eventually close the panel and the event type is logged to yet another element. In case I got you Avi, what is your intention? Why do you need an extra btn to close a panel using several event types although just using `click` works on touch as well? Please explain what your thought behind this is.

Best regards,
Stefan :)

**Comment by AviHafner** [comment]
Hi Stefan
1) Thanks, I remove the tap event and everything is working.

2) When I put the 2 events, I catch only one event according to the environment, 
And in iPhone only when I add the touchstart its start to work.

I Build example: 
A little explanation of the pictures and examples page.
The same page displayed in mobile contains a button that trig jspanel  for each line that shows more information .

In the page
http://www.admin.technion.ac.il/avi/
You can find 3 examples with documents (only the Third example working in all the environments)
The 5 pictures are from the real Students page (I change the student name to Stefan),
You can understand better what I Am doing from the pictures.

A new issue:
You can see that each button close the panel that is open and open another panel.
**question :**   how can I know if panel exists, and close it, you can see in the examples that i am getting error in the creation first panel when,
 I try to close the panel that is not exist.

Best regards,
Avi

**Comment by Flyer53** [comment]
Hi Avi,
I took a look at the one code version you say works in all environments.
Looks good to me, but did you ever check using only the `click` event? On all mobile devices/browsers I can test on `click` works just as well.

How to check whether a panel exsists:
In your `try ... catch` block you have the code
```javascript
panel.close(function (panelId) {
    console.log('panel.close : ' + panelId);
});
```
Change that to
```javascript
if (panel) {
    panel.close(function (panelId) {
        console.log('panel.close : ' + panelId);
    });
}
```

**Comment by AviHafner** [comment]
Hi Stefan
Click event working in IPad/iPhone
**The bug**:
 I don't understand why click event not supported in the callback of jspanel on **iPad/iPhone** environments?
You can check the example in
http://www.admin.technion.ac.il/avi/

Best regards,
Avi

**Comment by Flyer53** [comment]
Hi Avi,
that has to do with the fact that the footer by default is also a drag handle.
See http://jspanel.de/docs/#options/footerToolbar Example 1 on how to add footer button handlers that work on an iPad as well (an iPad is the only Apple device I have for testing).

**Comment by AviHafner** [comment]
Hi Stefan
In the example from the link that you send to me you create the event **touchstart** and that’s worked on iPad.

**Now for our problem. **

In one off the examples, I shows you that on android the problem occur when the user press on the bottom in the panel that trig the button in layer under the jspanel.

So the solution that I found,
is to trig the panel and the callback button with the same event and to add  
e.stopPropagation() in the callback 

Now if I change the **evt** in your example to **'click'** this not work on iPad.

Please check the  example 2 in the page
http://www.admin.technion.ac.il/avi/

Best regards,
Avi

**Comment by Flyer53** [comment]
Hi Avi,
the issue that an underlying element handler is triggered will be fixed with the next beta update.

Concerning the footer toolbar you can't use `click` events if want to make it work on mobiles. **It simply doesn't work** because the footer is a drag handle by default and due to the inner workings of the dragit interaction. **So far I could not find a satisfying way to use the `click` event in a footer item without getting unacceptable other problems.**
So I recommend you use the technique shown in example 4 of http://jspanel.de/docs/#options/footerToolbar which works on mobiles including iPad.

PS: The code in the second example of the link you posted above doesn't make any sense at all.

**Comment by AviHafner** [comment]
Hi Stefan

The purpose of last example is to convince you that a problem exist in callback of jsPanel  with a click event.

In my projects I trigger the jspanel and callback event with
JQuery and the 2 events ' ‘click touchstart’.

You remember that I need to have the same trigger for jsPanel and callback
(To avoid triggering the event of button in the layer under jsPanel - in android )

Thanks a lots
Yours
Avi

**Comment by Flyer53** [comment]
@AviHafner 
Avi, there is on option to use `click` events for the footer items that works on mobiles as well. If you don't need the footer section as drag handle (meaning only the header section serves as drag handle) you can disble the dragit interaction for the footer section like:
```javascript
jsPanel.create({
    dragit: {
        handles: '.jsPanel-headerlogo, .jsPanel-titlebar',
    }
});
```
The setting **handles** of option.dragit is reset without `.jsPanel-ftr`, so the footer is not used as drag handle -> `click `for footer items works.

Best regards,
Stefan

**Comment by AviHafner** [comment]
Thanks Stefan
It works and I think that it a perfect solution.

yours
Avi Hafner
