### ISSUE TITLE
feature request :: data 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#100]
custom data on panel.  

sample

jsPanel.create({
  position:    "left-top",
  contentSize: "600 350",

  data: {
     'data1': data1,
     'data2': data2,
     'data3': data3
  },

  callback:    function (panel) {
     // do whatever you like
     // the keyword "this" inside the callback function refers to the panel
  }

});

**Comment by Flyer53** [comment]
Do you really think it's necessary to add extra code to the jsPanel script for this? There are easy ways to add custom data to a panel.
In case you need to add only string data you could use datasets like
```javascript
var p = jsPanel.create();
p.setAttribute('data-custom', 'custom data');
console.log(p.dataset.custom);
```
For other data you could add a property to the panel like
```javascript
var p = jsPanel.create();
p.customData = {data1: 'data1', data2: 'data1'};
console.table(p.customData);
```

**Comment by alpastar** [comment]
OK,   i  have made it  by  using callback.. 
    this feature-request  should be ignored....

jsPanel.create({
    contentSize: "600 350",
    callback: function (panel) {       // onShown 
          panel.data = {                    // add-property 
            'data1': data1,
            'data2': data2
          } ;
     }
}
