### ISSUE TITLE
feature request ::  auto-close-callback 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#101]
is there any way to find out 
whether panel was closed by user-action(click close button)
 or  panel was closed by autoclose ?

if there  is no-such-way , i  think  autoclose-callback  will be helpful .

autoclose: {
  timeout : '60s' ,
  callback : callback-function ,  <- this-one
}
-------
scenario 
display  autoclose  modal panel (say,  60sec)
if a user closes  panel by click , then  it  triggers  action-a
but  if panel  was closed  by auto-close(no-user-action), then action-b occurs

**Comment by Flyer53** [comment]
Please take a look at and compare the two events

- `jspanelclosed` https://jspanel.de/api.html#events/jspanelclosed
- `jspanelcloseduser` https://jspanel.de/api.html#events/jspanelcloseduser

I think that already helps ...

**Comment by alpastar** [comment]
in my test ,  the event sequence  is 

BY  api(close), or autoclose 
1. jspanelclosed
2. onclose

BY  user click 
1. jspanelclosed
2. onclose
3. jspanelcloseduser

IMHO,  jspanelcloseduser should  be first one , preceding jspanelclose  
so 
1. jspanelcloseduser
2. jspanelclosed
3. onclose

**Comment by Flyer53** [comment]
I agree that `jspanelcloseduser` should fire before `jspanelclosed`. You may [download v4.8.0-alpha.3](https://alpha.jspanel.de/downloads/jspanel-4.8.0-alpha.3.zip) which has a changed sequence of those events.
I noticed another issue:
`jspanelcloseduser` fires even if an `onbeforeclose` callback prevents the panel from being removed.

**Comment by alpastar** [comment]
if onclosed()  have a  flag  argument,  it will be very convenient. 

sample 
jsPanel.create({
  position: "left-top",
  contentSize: "600 350",
 
  onclosed : function(panel,flag){
    // if  occured by user -click , then flag == true ,  else flag == falsey 
   if  (flag) {
      // user-click, action-a 
   }
  else{
     // api-close ,action-b 
  }
 },
});

**Comment by Flyer53** [comment]
Ok, there's a new alpha version incorporating a few changes:
+ `jspanelcloseduser` now fires only when panel is really closed
+ option `onclosed` and `onbeforeclose` callbacks receive an additional parameter indicating whether the panel was closed by the user
+ updated **modal extension** due to the updated/fixed method `jsPanel.close()`

A panel is considered closed by the user if:
+ panel is closed via close control
+ panel is closed via ESC key
+ modal extension: panel is closed with click in modal background

A panel is **not** considered closed by the user if:
+ panel is closed by the `autoclose` feature
+ panel is closed by calling `close()` programatically

Please see the relevant docs e.g. https://alpha.jspanel.de/api.html#options/onclosed
Download alpha from https://alpha.jspanel.de/downloads/jspanel-4.8.0-alpha.4.zip

Please give it a try and let me know how ir works out ...

**Comment by alpastar** [comment]
test-result : 
  onbeforeclose :   closedByUser  -> normalized (always !! ) 

--------------------------------------------------------------.
with single function 
.
**autoclose 
on-before-close:: id=jsPanel-1,closedByUser= normalized
jspanelclosed:: id=jsPanel-1
on-closed....:: id=jsPanel-1,closedByUser= undefined

**user-click 
on-before-close:: id=jsPanel-1,closedByUser= normalized
jspanelcloseduser:: id=jsPanel-1
jspanelclosed:: id=jsPanel-1
on-closed:: id=jsPanel-1,closedByUser= true
.
.------------------------------------------------------------------
with function-array 
.
**autoclose 
on-before-close:: 1st callback,id=jsPanel-1,closedByUser= normalized
on-before-close:: 2nd callback,id=jsPanel-1,closedByUser= normalized
jspanelclosed:: id=jsPanel-1
on-closed:: 1st callback,id=jsPanel-1,closedByUser= undefined
on-closed:: 2nd callback,id=jsPanel-1,closedByUser= undefined
.
**user-click 
on-before-close,1st callback,id=jsPanel-1,closedByUser= normalized
on-before-close,2nd callback,id=jsPanel-1,closedByUser= normalized
jspanelcloseduser :: id=jsPanel-1
jspanelclosed       ::id=jsPanel-1
on-closed:: 1st callback,id=jsPanel-1,closedByUser= true
on-closed:: 2nd callback,id=jsPanel-1,closedByUser= true
------------------------------------------
modeless( jsPanel.create() ) , and  modal ( jsPanel.modal.create()) 
 same-result

**Comment by Flyer53** [comment]
Note that the `onbeforeclose` callback receives **3 arguments** where the third is `closedByUser` and the `onclosed` callback receives only **2 arguments** where the second is `closedByUser`.

So if you set up an `onbeforeclose` callback with only 2 args the second one is panel status and not `closedByUser`.

I guess that's the problem ...

**Comment by alpastar** [comment]
OK,  it is working.... thank you..
