### ISSUE TITLE
feature-request : tooltip destroy-delay-time 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#102]
in  a default-mode,  
tooltip immediately destroys  when  mouse leaves target 
so ,  user can-not move  over the tooltip .  (small gap between target and  tooltip)
because  when user  leaves  target,  the tooltip will be destroyed 
.
so, in this case , one must use semi-sticky-mode.
but  in semi-sticky-mode , if user moves horizontally , the  below-tooltip never destroys. 
and this is cumbersome. 
.
so,  if there is delay-time (say, default: 300ms) between tooltip-destroy , 
then user can easily  leave-target, and reach the tooltip. (in a  default-mode) 
and  in any case , when user  leaves target, and not over the tooltip , 
the  tooltip will be automatically destroyed after delayed-time. 
. 
FYI,   this is a  bootstrap-popover hack  for a smart  programmer .

best  regards......

**Comment by Flyer53** [comment]
@alpastar 
I understand your reasoning but I'm not convinced that such an addition is really necessary. Even in `semisticky` mode where the mouse didn't move over the tooltip first you just need to click somewhere in the doc and the tooltip is gone.
However ... I'll think about it ...

**Comment by alpastar** [comment]
think about  horizontal 3  buttons .(usually-round button)
lets suppose it is button-1, button-2, button-3.
.
each button  has a  different tooltip below, 
so when user mouse-in button-1 ,  below-tooltip-1 shows .
but when user  moves to button-2 , below-tooltip-1  not destroyed.
.
what i want  is  tooltip-2 shows , and  tooltip-1  destroys automatically.

**Comment by Flyer53** [comment]
I didn't work with the tooltip extension for some time, so it took me a moment to realize that there is already a quite simple solution to your issue:

`jsPanel.tooltip.create()` accepts a second argument which is a callback function to execute after the tooltip was created.
Use `semisticky` for your tooltips and use the callback to get all tooltips except the one just created and close them.

Aworking example is found [here](https://jspanel.de/docs/demos/tooltip-1.html)

**Comment by alpastar** [comment]
simple , but brilliant !! , 
thanks..

**Comment by Flyer53** [comment]
@alpastar 
👍 So I don't see a reason to add extra code to the jsPanel script and would ask you to close the issue unless you have more ...
