### ISSUE TITLE
On Window Resize focused panel switched to last opened panel

### ISSUE THREAD

**Issue by ryhn** [Flyer53/jsPanel4#105]
On Window Resize focused panel switched to last opened panel. Also window resize gives this console error

> Uncaught TypeError: Cannot read property 'clientWidth' of null
    at HTMLDivElement.self.maximize (jspanel.js?8aec:3990)
    at eval (jspanel.js?8aec:5353)
self.maximize @ jspanel.js?8aec:3990
(anonymous) @ jspanel.js?8aec:5353

**Comment by Flyer53** [comment]
Can you explain in more detail please.
What jsPanel version do you use?
What OS?
Which browser?
What's your panel configuration?

**Comment by ryhn** [comment]
I open multiple panels with option container="window" 
All panel status is maximized.

jsPanel version : 4.7.0
Browser:  Latest Chrome on Ubuntu

**Comment by ryhn** [comment]
I upgraded jspanel version to v4.8.0 
No console error. But focused(front panel) issue continue

**Comment by ryhn** [comment]
Sorry, Console error still exist.

At Line: 3990
```self.style.width = parent.clientWidth - margins[1] - margins[3] + 'px';```

**Comment by Flyer53** [comment]
Ok, option onwindowresize has a bug concerning the handling of z-index values.
Please download and try https://alpha.jspanel.de/downloads/jspanel-4.9.0-alpha.2.zip which includes a fix of this issue and let me know whether it changes anything.

**Console error:**
I can not reproduce the error and so far did not have any issues with the referenced line of code. It would help me if you let me know your panel configuration.

**Comment by Flyer53** [comment]
fixed with v4.9.0 release
