### ISSUE TITLE
Latest version 4.9.0 no longer works in my app

### ISSUE THREAD

**Issue by alabaki** [Flyer53/jsPanel4#107]
The latest build now creates an issue in my app, webpack/babel is having issues:

`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

I am using the es6module

**Comment by sohail85** [comment]
It broke our code as well

**Comment by Flyer53** [comment]
@alabaki @sohail85 
Would you please download the modified files https://jspanel.de/downloads/jsPanel4.9.0-es6module.zip and let me know whether it makes a difference. The download contains only the ES6 module files.

**Comment by Flyer53** [comment]
@alabaki @sohail85 
Just released v4.9.1 which should fix this issue.

**Comment by alabaki** [comment]
@Flyer53 I confirm that the issue has been resolved! thanks!
