### ISSUE TITLE
Automatically/Optionally front a docked panel when master is fronted

### ISSUE THREAD

**Issue by dav-92** [Flyer53/jsPanel4#108]
It seems that currently there is no option to automatically front a docked panel in case the master panel is fronted. A lot of other behaviors of the master are mimicked by the slave so it seems logical that front should behave the same.

**Comment by Flyer53** [comment]
@dav-92 
Thanks for your input ... and you're fully correct. I simply missed that so far.
I'll take care of that with the next update. But I won't get that done until after New Year.

Merry Christmas and a happy New Year,
Stefan

**Comment by Flyer53** [comment]
@dav-92 
I have a [preliminary v4.9.2 to download](https://alpha.jspanel.de/downloads/jspanel-4.9.2.zip) including an updated dock extension that should take care of this issue.
Maybe you can give it a try and let me know how it works out.

**Comment by Flyer53** [comment]
@dav-92 
Just released v4.9.2 including an updated dock extension fixing this issue

**Comment by dav-92** [comment]
thanks, it's working great now
