### ISSUE TITLE
how  append window jspanel to taskbar ? 

### ISSUE THREAD

**Issue by khanhnam99** [Flyer53/jsPanel4#109]
how  append min window jspanel to taskbar ? 

how make a taskbar ? when click min window to closed , jspanel window   appended to taskbar, 

append to div (id="taskbar")

`<div id="taskbar"> </div>`

![mn](https://user-images.githubusercontent.com/575720/72122198-b3e9b800-338f-11ea-9848-e7b943fc526d.PNG)

**Comment by Flyer53** [comment]
@khanhnam99 
That is not possible.
The Windows taskbar is part of the operating system and you can only minimize Windows apps/programs to the taskbar. **But a jsPanel is not a Windows app like Word, Excel or the browser you use.** It's just a part of the webpage you created the jsPanel in. So you can only minimize the jsPanel to a part of the webpage.

The only thing you could do is creating your own "taskbar" within your webpage and minimize the jsPanel to that taskbar. See https://jspanel.de/api.html#options/minimizeTo

**Comment by Flyer53** [comment]
@khanhnam99 
You didn't answer to this for a month now. So I consider this topic not relevant anymore and close it.
