### ISSUE TITLE
Build fails with the 4.9.2 release (missing the es6module subfolder)

### ISSUE THREAD

**Issue by appurist** [Flyer53/jsPanel4#110]
Our app no longer builds after upgrading from jsPanel4 4.9.1 to 4.9.2. It is an Electron app although that is probably not relevant on this case other than this defines it to use Webpack.

Both development builds and production builds fail to load jspanel now in 4.9.2, although they are fine if I force it to use 4.9.1. This seems to be due to the 4.9.2 release not including the `es6module` subfolder. (It also drops the `src` folder, but it's the `es6module` that is needed for a build.)

```
vue-cli-service electron:build

 INFO  Bundling render process:

|  Building modern bundle for production...

 ERROR  Failed to compile with 2 errors                                                                       4:50:00 PM

This dependency was not found:

* jspanel4/es6module/jspanel.min.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-js-panel/src/JsPanel.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/STPMain.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save jspanel4/es6module/jspanel.min.js
 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stp@1.0.0-200109 build: `vue-cli-service electron:build`
npm ERR! Exit status 1
```

The key issue is:
```
This dependency was not found:

* jspanel4/es6module/jspanel.min.js 
```

**Comment by Flyer53** [comment]
Seems to be something with the `package.json` file ... I'm checking ...

**Comment by Flyer53** [comment]
I just updated `package.json`. Should work now, current version now is 4.9.4
Please let me know how it works out now.

**Comment by appurist** [comment]
Yes, I can confirm the 4.9.4 update addresses the issue. Thanks for the speedy response and resolution!  (And thanks for jsPanel4!)
