### ISSUE TITLE
Documentation is incomplete for resizeit.aspectRatio changes

### ISSUE THREAD

**Issue by appurist** [Flyer53/jsPanel4#111]
The choices for the value for resizeit's `aspectRatio` option, now a _string_, are not documented in the description [here](https://jspanel.de/api.html#options/resizeit/aspectRatio).

Some of the positive ones are (e.g. `'content'` and `'panel'`), but the full list of choices is not provide, specifically the third value for aspect ratio disabled (formerly `false`).  The former boolean value of `true` is documented to be remapped now to `'panel'` but there is no documentation at all for how to disable `aspectRatio`.

I have been assuming that passing `false` will trigger this to be remapped to whatever the new _string_ value is for aspect ratio lock being disabled, but that is an assumption on my part.  I'm assuming this since `true` is still supported for legacy compatibility, so `false` probably is as well.  The documentation does not indicate any negative values for `aspectRatio` at all (only `'panel'` and `'content'`).

I think the documentation just needs to list all possible recognized values. (Are there only three?) 
 It should also indicate that `false` will be remapped to (something), similar to the existing comment in the documentation that `true` is remapped automatically to `'panel'`.

**Comment by Flyer53** [comment]
Thanks for all your input 👍 
I'll have a look at this next week. Found a small glitch anyhow I have to take care of.

However, setting `aspectRatio: false` is the same as not using `aspectRatio` at all.

**Comment by appurist** [comment]
Indeed, the `defaults` value for `aspectRatio` reports `false`, which surprises me (especially after the recent changes that make that field a string).  We have never set it to anything other than `false`, initially not setting it at all, but started setting it to false after finding the aspectRatio "locked" in some panels after initially being unlocked.  So I believed it was reverting to a default value under some conditions, which apparently is not accurate.  This is why we wanted to set it to the false/unlocked value (but couldn't find one documented).

So that leaves us with a bit of a mystery, how our panels were becoming aspect ratio-locked.  I suspect it is in some way related to hot module reloading, when running under the webpack dev server.  For background on why: we found that already-mounted Vue components weren't getting their initialization rerun again on code changes, and I think that was directly related to the problem where after opening a panel, it suddenly becomes aspectRatio-locked.  The HMR reload point is that "after opening" point in time where it breaks. I think.

Are there any other _indirect_ conditions where resizeit's `aspectRatio` option is changed from `false` to something else, or assumed to be?  For example, if `syncMargins` or `grid` or `containment` is used?

**Comment by Flyer53** [comment]
Well, there definitely is an issue with `aspectRatio` when using the **modifier keys**. It seems like the value for `aspectRatio` is not reset after releasing a modifier key. I'll have to look at this in more detail next week (I'm away for a few days). 

Concerning Webpack, Vue.js and so on I won't be of any help. As amateur programmer I never used those tools and don't have the first idea about their inner workings.

So please be patient until I looked into and fixed the issue I already found. Shouldn't take that long ...

**Comment by Flyer53** [comment]
I just uploaded a modified preliminary v4.9.5 including a fix in `aspectRatio`. Also the docs are updated.
As far as I can see it on my end it looks good now. I would appreciate if you gave it a try and let me know how it works out.

[Download preliminary 4.9.5](https://alpha.jspanel.de/downloads/jspanel-4.9.5.zip)
[alpha.jspanel.de/api.html#options/resizeit/aspectRatio](https://alpha.jspanel.de/api.html#options/resizeit/aspectRatio)

**Comment by appurist** [comment]
Thanks!  I did take a look at the previous code and also couldn't find anything wrong other than perhaps the way the modifier keys actually toggled the aspectRatio boolean directly. I found it very unlikely to be the problem itself, as I wasn't using the modifiers at all as far as I could tell. However, it was the only place where aspectRatio was enabled dynamically so it does seem, in some way, that it must be involved, so it seems you're on the right track.

I'll try the update on Monday when I'm back in the office. Thanks again.

**Comment by appurist** [comment]
That 4.9.5 download seems to pass all my manual testing. 👍

**Comment by Flyer53** [comment]
Sounds good to me 😄
I have to do a bit more testing, but if nothing else comes up I'll release it as v4.9.5 the next days.

**Comment by Flyer53** [comment]
Ok, the modifier key code had a compatibility issue with IE11. So I updated once more. If you just download the same package one more time :smirk:

**Comment by appurist** [comment]
The updated zip file seems to work just as well as the previous, in my limited manual testing. No obvious problems observed.

**Comment by Flyer53** [comment]
I just released v4.9.5
Compared to the prerelease you downloaded it has an additional fix in the close method. So I think you should update to the official v4.9.5 release.

And since your issue is fixed I closed this issue.
