### ISSUE TITLE
in sPanel4 , how make a simple  taskbar?

### ISSUE THREAD

**Issue by khanhnam99** [Flyer53/jsPanel4#115]
in jsPanel4, how make a simple taskbar?

![Capture](https://user-images.githubusercontent.com/575720/74415079-3d9c1200-4e75-11ea-8e68-168d844af075.PNG)

**Comment by Flyer53** [comment]
I'm very sorry. But you really need to explain in a little more detail what you want. Otherwise I can't help you. The screenshot you posted doesn't tell me anything more than your question from 4 weeks ago.

So please describe what you want to achieve!

**Comment by khanhnam99** [comment]
- I click a button, a window is open after  the window minimize closed, this window append to a taskbar


![Capture](https://user-images.githubusercontent.com/575720/74498974-e6e61500-4f14-11ea-8e05-c2ac8314a980.PNG)

how to make a taskbar? how a window minimize closed to append to taskbar?

**Comment by Flyer53** [comment]
As far as I understand you this is the same question as in #109 

What I understand is that you want to create a jsPanel and place its minimized representation in the Windows Taskbar. Is that correct? If so, the answer is the same as in #109
**Not possible!** 

So unless I completely misunderstand you, there is nothing I can do for you, sorry.
