### ISSUE TITLE
[FEATURE] save jspanel "state"

### ISSUE THREAD

**Issue by afourmy** [Flyer53/jsPanel4#118]
Hello,

It could be helpful to have an optional "state" parameter used to save the state of the panel in the localStorage or the sessionStorage.
Typically, for datatables.js, you have such a mechanism described here: https://datatables.net/examples/basic_init/state_save.html (you can change the column ordering, reload and it's still there)

For JsPanel, I'd say the most important parameter to save would be the size. It's often hard to get the size of a panel right because it depends on the screen resolution so there is no one size fits all in percentage or pixels. Even `"auto"` doesn't help because the panel can get too big depending on the size of the content.

When `true`, the state parameter would store the last known size of the panel in the local or session storage per panel ID, and when you open a panel with the same ID, it reuses that last kwown size.

The position in the screen could be another parameter to save.

**Comment by Flyer53** [comment]
Did you take a look at the `layout` extension. It saves **position**, **size** and **status** (maximized, minimized etc.) to either `localStorage` or `sessionStorage` and identifies panels by ID. Maybe you can make use of that?

https://jspanel.de/api.html#extensions/layout

**Comment by afourmy** [comment]
It looks similar but then you need to predefine them right ? What if you don't know the ID beforehand, because your panels have variable ID based on something else like `id-${model.id}` ?
I was thinking about a way to do the same thing as the layout extension without having to predefine anything.
For example, if `saveState` is `true`, then in the `onclose` callback (and ideally `window.onbeforeunload`), there would be a function that saves the size / position in the `localStorage` / `sessionStorage` based on ID or something else.
Anyway I'll close this since it's more or less similar with the layout extension

**Comment by Flyer53** [comment]
How do you identify panel data in localStorage/sessionStorage if you don't know the panel id or something else unique beforehand?
Anyways, I think the layout extension can be used without any predefined config just to save/read panel data. Give me a few days, I'm currently on vacation and will be back some time next week. Then I'll try a few things ...

**Comment by afourmy** [comment]
I agree you need something unique, but I'm saying that in certain cases, you cannot use the ID for that because you'll use different IDs for the same type of panel. So there could be another argument like `StorageId` that is used as a key in the local/session storage.

**Comment by Flyer53** [comment]
Ok, shouldn't be a big deal to add a custom value to the saved data. Next week I'll be back home to continue some work ...

**Comment by Flyer53** [comment]
How about this idea:
you create one or more panels and add a custom data attribute like
```javascript
jsPanel.create({
  callback: (panel) => {
    panel.dataset.jspanelCustom = 'foo';
  }
});
```
Then at some point/event you call `jsPanel.layout.save();` to save panel data to `localStorage`.

The layout extension internally uses already a method to extract data of a single panel by ID. I could modify this method or add a new one to extract data of a panel by the custom data attribute.
Then, whenever needed, you could e.g. call `jsPanel.layout.getCustom('foo');` to extract data of a panel by data attribute.

Foe this to work you don't need an object with a predefined config since you only want to read a certain value from `localStorage`.

But you won't get around the need to have some unique value which is known to you.

**Comment by afourmy** [comment]
Ok, thanks. I'll see if I can make that work when it's available

**Comment by Flyer53** [comment]
@afourmy 
The latest https://alpha.jspanel.de/downloads/jspanel-4.10.0-alpha.zip includes an updated layout extension and implements a new panel option `data` to store some custom data which is also saved when calling `jsPanel.layout.save()`.

See https://alpha.jspanel.de/api.html#extensions/layout and take a look at the examples for `jsPanel.layout.getAll()` and `jsPanel.layout.getDataset()`
Using one or both of those two methods you can retrieve data to restore panels without having to use the other restore methods.

**Comment by afourmy** [comment]
@Flyer53 Ok thanks ! I will test and get back to you when I'm done

**Comment by Flyer53** [comment]
@afourmy 
Updated `jsPanel.layout.getDataset()` once more: If the new option `data` is set with an _array_ or plain _object_ `jsPanel.layout.getDataset(value, attr, storagename)` can search for `value` in the _array_ or _object_ to identify a certain dataset.
Take a look at https://alpha.jspanel.de/api.html#extensions/layout/getDataset

**Comment by Flyer53** [comment]
@afourmy 
Just uploaded another small update of the layout extension. The method `getDataset(value, attr, storagename, findall)` now accepts a fourth argument `findall`. When set to boolean `true` the method will return an array with all matches, or, if no match is found, an empty array. See
https://alpha.jspanel.de/api.html#extensions/layout/getDataset

Download: https://alpha.jspanel.de/downloads/jspanel-4.10.0-alpha.zip

PS: Thank you very much for your generous donation 😄
