### ISSUE TITLE
jsPanel with cytoscape

### ISSUE THREAD

**Issue by jkancio** [Flyer53/jsPanel4#120]
I wonder if samebody already used the Extension tooltip in canvas drawing, like https://js.cytoscape.org/ where there is no html objects associated to the nodes.

**Comment by Flyer53** [comment]
I personally didn't do anything with `canvas` yet. So I won't be able to help you with that, sorry.

As far as I know the rendered canvas is simply a kind of "pixel map" without any identifiable objects that could be used to trigger a "regular" event on mouseover or something like that. So my guess is no.

Is it possible to include some code in the function actually drawing the canvas that dispatches an event on _mouseover_ of a specific `node`?

**Comment by jkancio** [comment]
Please, visit this codepen : https://codepen.io/jkancio/pen/qBdyepz
I've put my doubts in the code

**Comment by Flyer53** [comment]
@jkancio 
Thanks for the sample code.
**Tooltips and the target element:** the tooltip needs to be triggered by (and positioned against) something you can identify in the "normal" DOM. DOM methods are needed to calculate sizes and positions. When I started the tooltip extension I never had "objects" in mind that are hidden somewhere in a canvas.
**Programmatically reposition a jsPanel:** there's a `reposition()` method for this.
Take a look at https://jspanel.de/api.html#methods/reposition

**Questions:** 
+ Does it need to be a tooltip or could you use a "normal" jsPanel? I created a simple example that creates a "normal" panel on node mouseover and closes it on node mouseout/mousedown that does without the extra target div
https://alpha.jspanel.de/docs/demos/test-cytoscape-2.html
+ Is it possible to get a live reading of node position while you drag it?

**Comment by jkancio** [comment]
Thank you Stefan, this is exactly what I want! 
I'will change the code to move the jsPanel while dragging the node and share with you.

**Comment by jkancio** [comment]
Please visit this codepen. This is perfect to me. 
https://codepen.io/jkancio/pen/PoqrMGN
Congratulation for your great Lib. I intend to use it on several projects that I am involved.

**Comment by Flyer53** [comment]
Thanks for the praise 😄 
I'm glad you could achieve what you wanted to do 👍 
In case you use jsPanel somewhere else and it's something publicly accessible I'd appreciate a link.

And if you consider this issue done I'd ask you to close the issue.
Thanks and stay healthy,
Stefan
