### ISSUE TITLE
Paneltype = Contextmenu and ziBase

### ISSUE THREAD

**Issue by ponyEdp** [Flyer53/jsPanel4#124]
Good morning
If we set Paneltype = Contextmenu and we set ziBase = 1001 there is a bug.
The z-index is not set on the jspanel.
May you fix the problem ?
Thanks 
Regards

Example:
```javascript
jsPanel.ziBase = 1001;
    var panel = jsPanel.create({
        id: 'f1Exhi',
        theme: 'dark filledlight',
        headerTitle: 'facility',
        position: 'left-top 0 5',
        contentSize: '500, 400',
        closeOnEscape: true,
        headerControls: {
            minimize: 'remove',
            smallify: 'remove', 
            normalize: 'remove', 
            maximize: 'remove'
        },
        paneltype: 'contextmenu', 
        content: '...' 
        // footer toolbar
        footerToolbar: '<span style="flex:1 1 auto">&nbsp;</span>',

        // callbacks
        callback: function (panel) {
            // stilizza alcune cose...
            panel.content.style.padding = '0.5em';
        }
    });
```

**Comment by Flyer53** [comment]
@ponyEdp 
Hi there,
Well, I see 3 things in your code sample that don't work:

1. in option `contentSize` you hava a `,` in the string between the two values. Remove it, the string is supposed to be a space separated list.
2. the `,` is missing behind option `content`
3. you set option `paneltype` to _contextmenu_. Maybe the docs are not clear enough about that, but **you should not use option `paneltype` at all**. If you want to create a contextmenu with jsPanel use the **contextmenu extension** and call `jsPanel.contextmenu.create()`.

I modified your code sample to make it work:
```javascript
jsPanel.ziBase = 1001;
var panel = jsPanel.create({
    id: 'f1Exhi',
    theme: 'dark filledlight',
    headerTitle: 'facility',
    position: 'left-top 0 5',
    contentSize: '500 400',
    closeOnEscape: true,
    headerControls: 'closeonly', // no need to remove all other controls separately
    content: '...',
    footerToolbar: '<span style="flex:1 1 auto">&nbsp;</span>',
    callback: function (panel) {
        panel.content.style.padding = '0.5em';
    }
});
```
And remember to call `jsPanel.ziBase = 1001;` only once before you create the first panel.

Let me know how it works out.
Regards,
Stefan

**Comment by ponyEdp** [comment]
Thank you so much.
Best regards
