### ISSUE TITLE
JavaScript Passive Event Listeners

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#13]
Hi Stefan
When I debug my application in chrome and Simulate Mobile Devices,
I get the warning 
[Violation] Added non-passive event listener to a scroll-blocking <some> event. 
Consider marking event handler as 'passive' to make the page more responsive.
 See <URL>
 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. 
Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

You can see at 
https://developers.google.com/web/updates/2016/06/passive-event-listeners
Example why we should try to use it in mobile
The internet is full with example from google with the Reason why use it,
And I think that the Passive event is going to improve the performance of the application in mobile.

**Stefan** what you think about this issue and maybe you know what is the disadvantage of using the passive events.

jquery framework going to support the Passive  Events only from version 4.
Example of using the passive event you can find in 
http://www.admin.technion.ac.il/avi/

Yours
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
thanks for the heads up :)
I'm not aware of this feature yet, so I have to read about this first. Thanks as well for the links.

Best regards,
Stefan

**Comment by Flyer53** [comment]
Hi Avi,
after reading a bit about this "passive event listener" feature I currently don't see a need include this in jsPanel. In one of the links you sent me it says: 
> Now that we have an extensible syntax for specifying options at event handler registration time, we can add a new passive option which declares up-front that the listener will never call `preventDefault()` on the event.

But a lot of event listeners in jsPanel, especially those responsible for dragging and resizing, do call `preventDefault()`. So unless there is something I don't understand yet it doesn't make any sense in jsPanel.

Best regards,
Stefan

**Comment by AviHafner** [comment]
Stefan ,
Thanks a lot
For all the efforts


Best regards,
Avi
