### ISSUE TITLE
click event doesn't close a panel

### ISSUE THREAD

**Issue by limo49** [Flyer53/jsPanel4#130]
Hi
is it possible to close a jsPanel sending a "click" event to the close button?

In jquery:
$("button.jsPanel-btn-close").click()
doesn't work.

I could use the "close" method but I need to send a click event or something else because I'm trying to use Selenium for testing my GUI.

**Comment by Flyer53** [comment]
Hi,
If you want to close the panel programmatically I  recommend using its [close()](https://jspanel.de/api.html#methods/close) method.

However, your code sample above could also use the `close()` method using jQuery like this:
`$("button.jsPanel-btn-close").closest('.jsPanel')[0].close();`
But this code (just as your code posted above) doesn't target a specific panel. It closes the first panel matched by the selector.

**Comment by limo49** [comment]
Thanks for info
but I need to simulate as close as possibile the actions performed by the user to check if the web GUI works.
On the field, the jsPanel gets a click event by the browser (I think), so if I use the close method I'm not reproducing the real behaviour of the component.

**Comment by Flyer53** [comment]
Ok, but the controls don't listen to a click event. Depending on used device and supported Event APIs the controls listen to either `mouseup`, `touchend` or `pointerup` events.
In v4.11.0-beta I just released the controls listen only to `mouseup` and/or `touchend` events.

If a user clicks the close control the handler does nothing else than also calling the `close()` method for that panel.

**For jsPanel version <= 4.10.2**
+ if the device supports only the Mouse Event API the controls listen only to a `mouseup` event
+ if the device supports Mouse Event and Touch Event APIs the controls listen to `mouseup` AND `touchend` events
+ if the device supports the Pointer Event API the controls listen to the `pointerup` event

**For jsPanel v4.11.0-beta**
+ if the device supports only the Mouse Event API the controls listen only to a `mouseup` event
+ if the device supports Mouse Event and Touch Event APIs the controls listen to `mouseup` AND `touchend` events
+ the use of the Pointer Event API is disabled for now

**Comment by Flyer53** [comment]
@limo49 
You didn't respond to this for 2 months now. Is there anything more to say about this? Otherwise I'll close the issue ...

**Comment by limo49** [comment]
Thanks, I'll try with the events you suggested.
