### ISSUE TITLE
Reload ContentAjax

### ISSUE THREAD

**Issue by randacpan** [Flyer53/jsPanel4#132]
Guys, can we reload contentAjax from outside? 
Thanks

**Comment by Flyer53** [comment]
Did you take a look at [jsPanel.ajax()](https://jspanel.de/#global/ajax) already?

Example (assumes latest jsPanel v4.11.0-beta):
```javascript
// create a panel
let panel = jsPanel.create({
  contentAjax: 'docs/sample-content/sampleContent.html'
});

// later load or reload content
jsPanel.ajax({
  url: 'docs/sample-content/sampleContent.html',
  done: (xhr) => {
      panel.content.innerHTML = xhr.responseText;
  }
});
```
Basically the same works with [jsPanel.fetch()](https://jspanel.de/#global/fetch)
