### ISSUE TITLE
Persisting panel location

### ISSUE THREAD

**Issue by roamhacker** [Flyer53/jsPanel4#134]
Hello, Looking to persist and reload location of a panel. Do you have any advice on best way to handle this? Might be interesting extensions to save to cookies location of panel on last use, and restoring upon reopening it.

Thanks for a great control

**Comment by Flyer53** [comment]
Hi there,
The only built-in tool for this is the layout-extension using either LocalStorage or SessionStorage. If you want to use a cookie you could still use the layou-extension to save/read the needed data and then store it in a cookie.

**Comment by roamhacker** [comment]
Thank you for the advice. Will use this.
