### ISSUE TITLE
iFrame causing odd resize isue

### ISSUE THREAD

**Issue by roamhacker** [Flyer53/jsPanel4#135]
HI, I am embedding and iframe during the jspanel.create process with content:'<iframe.....'>

When I don't have the iframe, i can resize the window up and down and works as a normal window.

With iframe embed, it sometimes resizes the whole window proportionally (horizontally and vertically). Example: I try to make window taller, dragging from bottom of panel down, but the window also gets wider. Do you know why an iframe would affect  this way? without iFrame, all sizes well.

**Comment by Flyer53** [comment]
Hi again,
Well, so far I did not have any such issue  and don't think it's caused by an iframe.
When you talk about window you mean the panel and not the browser window I guess??
Can you tell me some more about the panel configuration?

**Comment by roamhacker** [comment]
Thank you for your response. When I remove the iFrame, the panel behaves normally. Here is the code:

` jsPanel.create({
        id: this.idPanelDNP,
        header: 'auto-show-hide',
        headerControls: { smallify: 'remove', maximize: 'remove' },        
        content: '<iframe src="' + this.baseUrlRoamDb + '" id="iframePanelDNP" style="width: 100%; height: 100%;border:0px solid white"></iframe>',
        headerTitle: '<div style="font-variant: normal;position:relative;left:5px;z-index:1000;width:200px;color:white !important;padding-top:2px;">Daily Notes</div>',
        iconfont: [
          'bp3-button bp3-minimal bp3-small bp3-icon-small-minus', 
          'bp3-button bp3-minimal bp3-small bp3-icon-chevron-down',  
          'bp3-button bp3-minimal bp3-small bp3-icon-expand-all', 
          'bp3-button bp3-minimal bp3-small bp3-icon-maximize', 
          'bp3-button bp3-minimal bp3-small bp3-icon-cross'
          ],
        onwindowresize: true,
        resizeit: {  minWidth: 400, minHeight: 200, },
        panelSize: '650 300',
        position: { my: 'center-bottom', at: 'center-bottom', offsetX: -10, offsetY: -10 },
        dragit: {
          containment: 10,
          snap: { containment: true, repositionOnSnap: true }
        },        
        boxShadow: 4,
      })`

As I mentioned, just the iframe causes the issue. Even if the iframe is small (not sized to the width of the panel)

**Comment by Flyer53** [comment]
Thanks for the code. I'll try to reproduce it next week. I'm currently out of town for a few days.

**Comment by roamhacker** [comment]
Yes I have tried different browsers. Thanks for looking into this.
Perhaps one question: is it a feature of jsPanel to maintain aspect ratio? Or is this some unusual?

**Comment by Flyer53** [comment]
Option "resizeit" has an "aspectRatio" parameter, but it should be "undefined" by default. 
https://jspanel.de/#options/resizeit

**Comment by roamhacker** [comment]
Thanks. yes I played  with those settings, no changes. Ok. So I wait for your feedback. Unless you have another option for loading a iframe into the panel?

**Comment by roamhacker** [comment]
I discovered something interesting. Right after the panel is created I mark set the .style.visible ='hidden'. I do this so the web page loads in the iframe in the jsPanel and is ready when user loads the panel. If I remove the .style.visible ='hidden', the panel works as expected.

So it seems to be something about the panel being hidden via css.

Is there a way to hide the panel in the background in a better way?

**Comment by Flyer53** [comment]
One option could be to create the panel offscreen and reposition it upon some event that suits your needs.
There might be other ways of course. I can try a few things once I'm back home next week...

**Comment by Flyer53** [comment]
I tried something that seems to work quite well. Create the panel offscreen and add an onload handler to the iframe to reposition the panel once the iframe content loaded. Example:
```javascript
jsPanel.create({
    contentSize: {
        width:  window.innerWidth * 0.8,
        height: window.innerHeight * 0.8
    },
    contentOverflow: 'hidden',
    position: {
	my: 'right-center',
	at: 'left-center',
	of: document.body
   },
    content: '<iframe src="path/to/your/resource" style="width: 100%; height: 100%;"></iframe>',
    callback: function(panel) {
	panel.querySelector('iframe').onload = function(){
		panel.reposition('center');
	};
    }
});
```

**Comment by roamhacker** [comment]
Thanks for this solution. It does work. Thank you for the help and also a great library.
