### ISSUE TITLE
 Panel appears outside the window

### ISSUE THREAD

**Issue by jkancio** [Flyer53/jsPanel4#138]
Hi,
Congratulation for your nice and useful lib.
Now I'm facing a problem that makes the panel appears outside the window if a set the option {...container: document.body, ...}
But when I do not set this option the panel goes to the same outside position em I start to drag it.
This happens only when I set {dragit: {containment: [...]}

**Comment by Flyer53** [comment]
Hi there ... and thanks,
Would you please show the full code including all options you use to create the panel. And it would be helpful if I knew your intentions, especially concerning container, position and containment options.

**Comment by jkancio** [comment]
Please check this Codepen:
https://codepen.io/jkancio/pen/eYzZQMK

**Comment by Flyer53** [comment]
Did you ever try it in a "normal" webpage?
It seems to be an issue that appears only within a pen/fiddle. I guess because the document the panel is created in is in an iframe.
So please check whether you have the same issue in a "normal" webpage.

**Comment by jkancio** [comment]
**Yes**, I have already tried with a normal and single page without a frame or iframe. The behavior is the same.
If you do not have the button in that div, the problem disappears.
```
 <div>
	<!--<button id="btOpen"> Open</button>-->
</div>
```
I think the problem is due to this code: (Line 1973)
```
 maxTop = parentRect.height / scaleFactor.y - parseFloat(dragStyles.height) - containment[2] - yCorr;
 ```
 _parentRect.height / scaleFactor.y = 21
 dragStyles.height = 234px
 maxTop = -281  Negative: outside window_

**Comment by Flyer53** [comment]
Found it ...
In your codepen example the `html` and `body` element's height is just the height of the `button` element resulting in seemingly wrong position calculations for the containment feature. Add CSS `height: 100%` to `html` **and** `body` elements and it works as expected. Let me know how it works out please.

**Comment by jkancio** [comment]
Yes, it works fine if I put
```
html{
    height: 100%
}
body {
    height: 100%
}
```
I hope this has no side effects on my application.
I suggest you state this at lib's documentation because I had never used this style before.
Thank you,

**Comment by Flyer53** [comment]
You don't necessarily have to set those styles. Just make sure that the `html` and `body` elements fill the available height of the window. I assume that's the case anyhow when you have finished your page. And then it's not an issue anymore ...

**Comment by Flyer53** [comment]
@jkancio I guess this issue is settled. Unless you have more questions about this I'd ask you to close the issue.
