### ISSUE TITLE
Add an id to the class="jsPanel-content" div

### ISSUE THREAD

**Issue by CouinCouin** [Flyer53/jsPanel4#139]
Hi, 

I would use JSPanel so a tchat member could read PM's with other members eve if they are not connected, and I would the lasts messages are directly visible. 
In this case, I need to scroll to content of the panel to the bottom. I can do it in the callback function of JSPanel :
`document.getElementById('mpCouin_content').scrollTo(0,document.getElementById('mpCouin_content').scrollHeight);`

In fact, I would change the code from this : 
```
<div class="jsPanel jsPanel-standard jsPanel-depth-3" style="left: [...];" id="mpCouin"><div class="jsPanel-hdr jsPanel-hdr-dark">
[...]
<div class="jsPanel-title" style="color: rgb(255, 255, 255);">Couin</div>
[...]
<div class="jsPanel-content" style="border-top: [...];">...
```

to that :
```
<div class="jsPanel jsPanel-standard jsPanel-depth-3" style="left: [...];" id="mpCouin"><div class="jsPanel-hdr jsPanel-hdr-dark">
[...]
<div class="jsPanel-title" style="color: rgb(255, 255, 255);">Couin</div>
[...]
<div class="jsPanel-content" style="border-top: [...];" id="mpCouin_content">...
```

I found where to add the id tag in jspanle.js ( line 1670), here  :
`<div class=\"jsPanel-content\">`
to 
<div class=\"jsPanel-content\" id=\""+ panelcontentid + "\">

where panelcontentid = panelid + "_content" . 
and panelid is the id defined  in the jsPanel.create command on my webpage. 
```
jsPanel.create({
    id: "mp" + name ,
	position: { .... 
```

I searched where is the panel id in the jspanel.js but didn't find it :( 

Some help would be welcome :)

Thanks ! 
Couin

**Comment by Flyer53** [comment]
Hi there,
If you already assign an ID to the panel itself via the built-in option then you have everything you need.
Example:
```javascript
// create panel with custom ID
jsPanel.create({
    id: 'mypanel'
});
// get content section for the panel with the custom ID
document.querySelector('#mypanel .jsPanel-content');
```
So there is absolutely no need to add an extra ID value to the div with the content.

**Comment by CouinCouin** [comment]
Hi dear, 

Thanks for your answer :)

I didn't hink that it was a easy solution like this ! 
Works great ! 

I'll open a new thread for another small question ;)

Thanks !
