### ISSUE TITLE
Size height : "auto" + maxHeight : value

### ISSUE THREAD

**Issue by CouinCouin** [Flyer53/jsPanel4#140]
Hi ! 

I would use a panel to list tchat members of MPs. 

I would like the panel has an auto height, for example, if there is only few members, like 5, the panel height match with the 5 lines display. 
But if there are some more lines, I would the height does not over than a size (number of pixels or propotional to the window height).

I tried :
```
 	contentSize: {
	width: "auto",
	height: "auto",
	MaxHeight: 0.75 * window.innerHeight 
	},
```

but it does not run :(

Tried : 
```
	contentSize: {
	width: "auto",
	height: "auto"
	},
```
and 
`this.resize({maxHeight: 0.75 * window.innerHeight}).reposition();`
in the callback function, but if the list is too long, it goes out from the screen. 

Is there a little trick to do this ? 
 
Thanks :D 
Couin

**Comment by Flyer53** [comment]
Using `"auto"` for either _height_ and/or _width_ within option `contentSize` (which does not have a property _MaxHeight_) is a bit tricky and might not work the way you expect it.
You have to consider that at the time the script tries to calculate an _auto_ width/height of the content section it can only work with content that's already there. In your case you probably get the content via some kind of Ajax request. So the content most probably is not there yet when the script calculates the dimensions.

**Suggestion:**
Use option `contentAjax` with the parameters `autoresize` and `autoreposition` in combination with `contentSize: {width: "auto", height: "auto"}` (might be better to use a fixed width and use "auto" only for height).
See [option contentAjax](https://jspanel.de/#options/contentAjax)
If that doesn't work use the `done` callback of the Ajax request to resize/reposition the panel as needed.

**Comment by CouinCouin** [comment]
Hi dear, 
Thanks for answer. 

You are right, I getting the cotnent data via Ajax, but in fact, I do the Ajax request to create the content data (memberlist, in the following code). When the Ajax request get success answer from server, it runs mpmmemberlistpanel() function that creates the panel :

```
$.ajax({	
url: "./archmp/index.php",
success: function (data) {
memberlist = data;
mpmemberlistpanel();
	}
});

function mpmemberlistpanel() {
    jsPanel.create({
[...]
   content: memberlist,
[...]
}
```

The "auto" weight is running go like this . You can see the first panel has a good size for the member list : 
 ![list1](https://user-images.githubusercontent.com/62549730/99205296-6e202c00-27b8-11eb-9a8f-52ec155b4503.jpg)

If there is more members (I doubled the lines for the example), the panel set it's height correcty too : 
![list2](https://user-images.githubusercontent.com/62549730/99205350-9740bc80-27b8-11eb-9750-c07c14930178.jpg)

But I would get the panel height not more than 0.75+window height.

So, I use the callback/resize feature like this : 
```
	if ( document.getElementById( "mpmemberlist" ).style.height.replace(/\D+/g, '') > 0.75 * window.innerHeight ) {
	this.resize({ height: 0.75 * window.innerHeight }).reposition();
	}
```
and here is the result with a list longer than 0.75 window.height :
![list3](https://user-images.githubusercontent.com/62549730/99207649-cc500d80-27be-11eb-976c-ad355743cd03.jpg)
TADAAAAA ! lol 

Unless a cleaner solution, I would keep it :) 

Thanks !

**Comment by Flyer53** [comment]
Looks good to me 😄 
But you could simplify the callback doing the resize a bit. Since you create the panel only if the Ajax request returns successfully you don't necessarily need the if clause and height checking can be done shorter.
```javascript
function mpmemberlistpanel() {
    jsPanel.create({
        // your options ...,
	callback: panel => {
	    panel.resize({
		height: () => { return Math.min(parseInt(panel.currentData.height), window.innerHeight*0.75) }
	    }).reposition();
	}
    });
}
```
**Note:**
You don't find the panel property `currentData` in the docs. But it returns an object like:
```javascript
{
  width: '500px',
  height: '300px',
  left: '100px',
  top: '100px'
}
```
with the values the panel currently has. The function calculating a new height for the panel uses Math.min() to return the smaller of two values.

Maybe you want to give it a try 😏

**Comment by CouinCouin** [comment]
Hi dear, 

Thanks for the tip :) 
I tried and obtained the same result with this nicer code 👍 

See ya !

**Comment by Flyer53** [comment]
My pleasure,
So unless you have more questions about this I'd ask you to close the issue.

**Comment by CouinCouin** [comment]
Hi dear, 
You are right, solution looks good so I close the thread 👍
