### ISSUE TITLE
Autoposition "overlap"

### ISSUE THREAD

**Issue by webcliq** [Flyer53/jsPanel4#142]
I have used jsPanel for some years in my Cliqon projects. As a general rule, I have tended to open one panel at a time. 

I am working on a project where I am trying to do something more sophisticated with jsPanels and I could have 3 or 4 open at once. Every instance of a panel will obtain its content via an AJAX call. 

I have spent two days programming and testing a practical solution. JsPanel holds up perfectly to the demands I am making of it. Panel one will contain a table, panel two will contain an add record form, panel three might contain a lookup form to fill in a field on the form or a map and so on.

If we are dealing with purely srtatic content, your concept of overlapping the panels and controlling each panel with a separate number during the session, works well. But when there is a lot of interaction between the contents of each panel, one needs to have precise control of the ID of the window and the name of the window for the purposes of closing the window (not using the close button) but programmatically when the service provided within the window has completed its task.

I have solved all that with my own programming by having defined IDs and defined names that unique (amongst themselves for one set of activities.

The problem, as you know, when one replaces your autoID with a defined ID, is that overlapping with a useful offset no longer works automatically. As the developer I am required to use either Autoposition: right or down etc. to control the position of the second and subsequent window. Using Autop. right or down, soon puts the panel off the screen .....

What I would really like is for an Autoposition: overlap and some control over the offsetting of the overlap. I could write this control into my Javascript but that does feel the right place to do it. I believe that it should be in the jsPanel code itself. 

At this moment, I am autopositioning sub panels to the right. Then dragging a sub panel to where I want it.

Having said all this I am congnisant that the concepts of docking and child panels might do what I want. If that is the case then it is absolutely not clear from the documentation that this a benefit offered by either the extension or the facility.

**Comment by Flyer53** [comment]
@webcliq 
Thanks for your post. Please give me a few days to answer. I'm out of town currently ...

**Comment by Flyer53** [comment]
@webcliq 
First of all thanks for using jsPanel for some years already 😄 
Now to your questions:
The autoposition feature is primarily intended for use with hints/notifiers/alerts or however you want to call those panels which show some kind of information and can be closed after a short while. Typically combined with `autoclose`. Of course you don't need to autoclose those panels, but, as you say, depending on their size panels that remain open will soon be out of view. So I would suggest not to use `autoposition` at all. Use the _normal_ positioning options to position the panels in the overlapping way you want them.
Concerning the `dock` extension or the usage of childpanels is something that very much depends on your kind of app. It's not that I suggest a specific one and only usecase for that. It's completely up to the developer and I can't anticipate all usecases a developer might possibly find.
Another point is that I always wanted to keep the code base reasonably small. If I try to build in everything immaginable the jsPanel script would get bigger and bigger, mostly for features most of the users don't need. A lot of things can be done with some extra custom code I guess ... or possibly a custom extension. Further, jsPanel is a one-man-show, and for me, as amateur programmer, it's already not so easy to handle all the code.

Idea: Depending on your app it might be worth to think about a custom setting for the **global** property `jsPanel.autopositionSpacing`. For an example go to the autoposition example on [alpha.jspanel.de](https://alpha.jspanel.de/api.html#options/position) (example 5) and add `jsPanel.autopositionSpacing = -50;` as very first line of code to get an idea how this could work for _autoposition down_ panels.

I hope this is of some help at least?! 

Regards,
Stefan

**Comment by webcliq** [comment]
![screenshot-treetest test-2020 12 21-18_51_56](https://user-images.githubusercontent.com/1401189/102806741-b802c000-43bd-11eb-9594-9c90a806bfdf.png)

Dear Stefan,

Thank you for your reply. Thank you for confirming to me that what I want to do is not possible withing the existing system. There is no element of criticsm in that statement just a relief that I had not overlooked something that was incredibly simple that might make me feel more of an idiot .........

I understand your position. However, I would like that jsPanel does the task rather than in my JS code. In principal because I want to maintain the correct separation of concerns. This means that I should look to writing a custom extension to jsPanel which does the task. 

My solution must be generic and multi-lingual and at the same time satisfy my requirements. As you say, it will not involve "autoposition" but a series of programmable patterns that a developer can generate. 90% of my situations in my code will follow the pattern as shown in my screenshot, where the table opens first, then the form is executed from the table and finally a preview or auto-lookup is instantiated from the form. 

At this moment the code to do the above is in my JS. I need to transfer and augment it into an extension. I expect to be in touch in the New Year but in the meantime will close the Issue/Feature Request.

Have a safe Christmas.

Until the New Year, 

Mark@Webcliq

**Comment by Flyer53** [comment]
Hey Mark,
all fine ... don't worry 😏 

Thanks for the screenshot. If  I get this right the three panels are more or less the same each time and get called one after the other in the same sequence. The second and third panels triggered by some action in the previous panel.

Assuming that's correct we didn't see the most obvious and easiest solution: Using [option position](https://jspanel.de/#options/position) parameter `of` to position a panel relative to the previous one.

Example:
```javascript
jsPanel.create({
  id: 'table',
  position: 'left-top'
});
jsPanel.create({
  id: 'form',
  position:  {
    my: "left-top",
    at: "left-top",
    of: "#table",
    offsetX: 70,
    offsetY: 70
  },
  theme: 'info'
});
// using option position shorthand
jsPanel.create({
  id: 'preview',
  position:  'left-top 70 70 #form',
  theme: 'dark'
});
```
No need for custom js or even an extension ...

Same to you Mark, stay healthy and positive,
Stefan

PS: Don't worry about a prompt answer ... I won't do much more this year either ...
