### ISSUE TITLE
Panel in parent iframe ?

### ISSUE THREAD

**Issue by CouinCouin** [Flyer53/jsPanel4#145]
Hi ans happy new year :) 

Is there a way to display a panel in the parent frame of a frameset ? 

I mean, the website has a topper frame and a main frame under the topper frame. 
I would open a panel from the topper frame page, but that can be moved into the whole window. 

In simple images, actually, I get this : 
![image](https://user-images.githubusercontent.com/62549730/104748290-d2785100-5751-11eb-918c-0978516571a1.png)

And I would have : 
![image](https://user-images.githubusercontent.com/62549730/104750808-de194700-5754-11eb-955c-14c884243b9f.png)

Of course if I put the code in the parent page I get the good behavior, but in some case, the mainframe can be opened in the separate window, so the script has to be in the mainframe page. 

Thanks :)

**Comment by Flyer53** [comment]
@CouinCouin
Thank you very much 🙂 and a happy New Year to you as well.

Before we continue with this question: Do you really talk about `<frameset>` and `<frame>` elements? If so please consider that those elements are **deprecated**, no longer recommended  and May cease to work at any time. So if at all you should use `<iframe>` elements.

**Comment by CouinCouin** [comment]
Thanks Flyer53 :) 

There are iframes.

**Comment by Flyer53** [comment]
Well, one thing you have to consider is that each iframe hosts its own separate document with its own javascript context. For security reasons you can't just execute some javascript in page A and have it act on something in page B. So there's no simple way to achieve what you want.
You might find the following article interesting:
[https://javascript.info/cross-window-communication](https://javascript.info/cross-window-communication)

**Comment by Flyer53** [comment]
@CouinCouin 
Any news on this issue?

**Comment by CouinCouin** [comment]
Hi Dear, 

I'm sorry, I missed answer notification. 
Also, I'll check the link you provided, but on the website where I would do it, I already pass from an iframe to another. 
I explain : 
On the topper iframe, I get some infos from an Ajax request. In these infos, there if the now playing song album art, and the 5 previous songs album arts. 
The 5 previous album art ar displayed on the bottom iframe. 

You can see it here https://eurodance90.fr :) 

Thanks !

**Comment by Flyer53** [comment]
Hi again,
ok ... I took a quick look at the link you posted and realized that the content you load comes from php files hosted on your own server. So there is absolutely no need and no reason to use `<iframe>` elements to show this content. This doesn't make any sense at all to me. Those php files generate html you can get with an ajax request and load into a regular div for example. Using an `<iframe>` doesn't solve a problem, but causes a lot problems.

My recommendation: Get rid of those `<iframe>` elements.

**Comment by Flyer53** [comment]
@CouinCouin 
Anyway, how you organize the content of your page is completely up to you . And problems/difficulties that derive from the use of `<iframe>` elements embeded in your app are not something jsPanel has to solve. It's not a jsPanel issue that `<iframe>` elements are subject to certain restrictions. Those restrictions are there for a reason.
As far as I can say from your explanations my best advice is to get rid of the `<iframe>` elements and you have a lot less issues to solve.

**Comment by CouinCouin** [comment]
Hi Dear, 

Sorry for delayed answers, I'm very busy theese times :(

I used iframes so the stream still playing while changing page (Emissions, Discothèque, Tchat, Contact...). 

I plan to modify the website to replacing iframes by divs and ajax requests but it's not in the near future :(

I'm aware that is not a problem JSPanel has to solve, it was just in case of there was a tip to send the panel in the parent window instead of iframe :) Like a "target" option. 

Otherwise, I'll see to put the script in the parent window.

**Comment by Flyer53** [comment]
No problem, don't worry.

Maybe [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is a topic you should read about ...

So concerning jsPanel I consider this issue done and close it.

Happy coding,
Stefan
