### ISSUE TITLE
Panel could be dragged outside the window

### ISSUE THREAD

**Issue by balage1551** [Flyer53/jsPanel4#147]
**Describe the bug**
A panel could be dragged to the top and over the edge of the page. This will hide the titlebar and prevent the panel to be dragged back. If layout extension is used, it is quite hard to reset.

**To Reproduce**
1. Create a panel.
2. Drag it over the top.

**Expected behavior**
1. The screen should bound the dragging (at least on top and left).
2. An easy way to reset the state of a panel and/or clear the stored layout info programically.

**Screenshots**
![image](https://user-images.githubusercontent.com/11457054/104966910-57799980-59e2-11eb-990c-0ac977c43758.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser any
 - Version 4.11.2

**Comment by Flyer53** [comment]
Did you try the `containment` parameter of option **dragit**?

**Comment by balage1551** [comment]
Thanks. It works.
