### ISSUE TITLE
Snap without centering

### ISSUE THREAD

**Issue by balage1551** [Flyer53/jsPanel4#148]
**Is your feature request related to a problem? Please describe.**
When you use `drag.snap`, it snaps to the side, but also snaps the given anchor to each other. For example, when I drag a panel to the right and it snaps, the center of the panel is aligned to the center of the window (the `at` target). Although this is often the desired behavior, sometimes I would like to snap to the side of the screen while keeping the Y position. (For example, when you allow the user to freely organize a pack of (different size) panels to the side of the screen.)

**Describe the solution you'd like**
An option to allow only snapping along a given axis. If you snap to the side (left or right), only the X is set, while the Y coordinate is maintained as it is. Likewise, snapping to top or bottom only effect the Y coordinate, leaving the X alone. Snapping to the corners should snap to both axis.

**Additional context**
When the panel (blue) is snapped to the right side, now it is centered on Y-axis (red), the desired behavior would be to keep the Y (green).
![image](https://user-images.githubusercontent.com/11457054/105009360-a9e6a480-5a3a-11eb-8ea8-ac5477f39b35.png)

**Comment by Flyer53** [comment]
Thanks for your request.

While I see your reasoning I can't promise to implement such a feature. I'll have to look at that a bit closer first.

So far I would suggest that you do without the **snap** feature and use the `containment` parameter of the **dragit** interaction. Then you can drag the panel up, right, left or down until it stops at the desired boundary. Just give it a try ...

Regards,
Stefan

**Comment by balage1551** [comment]
Yes, I will use the containment. That's more than enough for now.
It is a minor request, so if the code doesn't offer a quick and easy solution, don't bother with it!

Meanwhile I've found some minor issue once you may address. The scrollbars. Now if the screen has no scrollbar on right and you "snap" to it, it snaps correctly to the right edge. However, when the scrollbar appears, it covers the right side of the panels. (When you drag the panel a pixel it snaps to the new viewport correctly.) I am not sure how much work to react the appearance/disappearance of the scrollbars, but following the viewport would be a user-friendly. Or in more general: the panels "snapped" to the right may follow the size change of the screen. 

But maybe I missed a feature, again... ;-)

**Comment by Flyer53** [comment]
I made a note to check on your "snap without centering" request.

Concerning the scrollbars ... well ... yes, that's a point. The basic problem is that there's no easy way to detect the presence of a scrollbar and its width/height working across browsers.
There is a workaround though that might work for you:
Let's assume your app always has a scrollbar on the righthand side. Then you could use options `maximizedMargin` and `syncMargins` in combination with the parameter `dragit.snap.containment`. Example:
```javascript
jsPanel.create({
    maximizedMargin: [0, 16, 0, 0],
    dragit: {
        snap: { containment: true }
    },
    syncMargins: true
});
```
A panel with this configuration would always maintain a distance of 16 pixels from the right edge even when it snaps. But it would do so regardless of scrollbars. Beside that the panel can not be maximized, dragged or resized beyond this 16 pixel limit.

**Comment by balage1551** [comment]
Thanks! I'll test your snippet!

As for the scrollbar, here is a small snippet to show how to detect viewport (window internal size without the scrollbar) and get notification on the change:

```
<html>
<head>
<script>

window.addEventListener("resize", function(event) {
    document.getElementById("d").innerHTML=document.body.clientWidth + ' wide by ' + document.body.clientHeight+' high';
})

</script>

</head>
<body>
<div id="d" style="background-color:red; width: 1000px; height:600px;"></div>
</body>
</html>
```

(sorry for the (missing) formatting.)

**Comment by Flyer53** [comment]
Thanks for your code sample.
But that's a little bit too easy. I'd need a solution that works on diffrent operating systems, browsers, desktop and mobile devices just as well.
I'll look into that when I have some more time ...

**Comment by Flyer53** [comment]
@balage1551 
Any news on this issue? Did you check out/test the options I mentioned above?
If the snap issue is sufficiently solved for now and unless you have more questions on that I'd ask you to close the issue.

Concerning the scrollbar thing I made a note to look at that for a future release ...

**Comment by balage1551** [comment]
I could live with it. Or without it. ;-)
I did a little research and learnt that the current snapping function is only at-the-time snapping (it doesn't maintain snapping when environment changes). It's not anchoring. So what I asked is not clearly a feature for the current snapping. 

An anchoring mechanism, as an extension may be useful in the far future. Anchoring is somewhat the combination of the docking and snapping. It's a kind of snapping to the edge of the viewport, and then maintaining this relation in the future. You may think of it in long term. (I would say I do it, but I'm quite a noob in JS libraries. ;-))

So thanks, I close this feature request.

**Comment by Flyer53** [comment]
I'm not sure whether I really understand your intention. What exactly do you mean with "anchoring"?

+ did you notice that you can pass your own callback function to each of the snap positions? See https://jspanel.de/#options/dragitsnap
+ another option you should look at is [option onwindowresize](https://jspanel.de/#options/onwindowresize)

**Comment by balage1551** [comment]
Wow! No, I wasn't aware these options. :-) 👍 
So there is almost everything. Only the scrollbar appearance and the turn off forced center to page is what I miss a little (original post), but that I could live with.

**Comment by Flyer53** [comment]
Well, sometimes it's a good idea to take a closer look at the documentation 😏 

As said, I will look at the scrollbar thing as soon as I find some time ...

Concerning the snap feature you'll have to live with it as it is. To me it doesn't make a lot of sense to add extra code to the jsPanel script for this since you can just drag the panel over and the containment setting prevents the panel from going over the edge.

**Comment by Flyer53** [comment]
@balage1551 
I incorporated some changes in positioning to address the scrollbar issue. It should be better now.
I'd apprciate if you gave it a try and let me know how it works out. [You can download a preliminary v4.11.4-alpha](https://alpha.jspanel.de/downloads/jspanel-4.11.4-alpha.zip)
Regards,
Stefan
