### ISSUE TITLE
jsPanel4 - how to get current ID panel's position x, y ?

### ISSUE THREAD

**Issue by yasim21c** [Flyer53/jsPanel4#149]
hi ~

I use jspanel-4.11.2

I make 5 panels.

and give ID pan0,1,2,3,4.

and move each panels

and then

how to get each ID panel's position x, y ?

**Comment by Flyer53** [comment]
Hi there,

I assume you mean CSS left/top values. Then you have several options.
If you create a panel with ...
```javascript
jsPanel.create({
  id: 'panel0'
});
```
... then get the panel's CSS left with
```javascript
document.getElementById('panel0').style.left;
// or
document.querySelector('#panel0').style.left;
```
If you assign the panel to a variable like
If you create a panel with ...
```javascript
var p = jsPanel.create({
  id: 'panel0'
});
```
... then you could also get the panel's CSS left with
```javascript
p.style.left;
```
**_Please note that all this above is very basic plain javascript that is not specific to jsPanel._**

In case you always need a callback after you dragged a panel think about using the corresponding `stop` **parameter** of **option** `dragit`. See [jspanel.de/#options/dragit](https://jspanel.de/#options/dragit
)

**Comment by yasim21c** [comment]
thank you very much.

**Comment by Flyer53** [comment]
My pleasure,

If that answers your question please close the issue.
