### ISSUE TITLE
[BUG] Creating default panel throws error

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#15]
Hi Stefan,

Got very curious about v4, decided to plug it in into my web app.

The code:

```js
jsPanel.create();
```

Results in:

`Uncaught TypeError: this.zi.next is not a function` here:

https://github.com/Flyer53/jsPanel4/blob/master/dist/jspanel.js#L3082

Cloned most recent code, included `jspanel.css` and `jspanel.js` only. What am I doing wrong? :-)

Thx!

**Comment by Flyer53** [comment]
Hi Temuri,
I can't reproduce the error - tried with FF, Chrome, Brave, Opera, Vivaldi, EDGE and IE11!!

Although it shouldn't make a difference ... did you try the regular download instead of cloning?

**Comment by temuri416** [comment]
Stefan,

I've tried `jspanel-4-beta.zip` too and I still get the same error. On its own, it is working fine. But replacing jsPanel3 includes with jsPanel4 makes it crash.

Can you give any clues as to what to check next?

**Comment by temuri416** [comment]
ok, I've found the culprit, I was doing this globally:

```js
if ('jsPanel' in window) {
    window.jsPanel.ziBase = 2000;
    window.jsPanel.zi = 2000;
}
```

What's the analogue of that in jsPanel4? :-)

**Comment by Flyer53** [comment]
Oh well ... then the solution is easy.
In jsPanel4 you need only the first line:
```javascript
jsPanel.ziBase = 2000; // call before very first panel is created
```
**Just for info:**
Only if you need to change ziBase after panels were already created call
```javascript
jsPanel.zi = false;
jsPanel.ziBase = 1000; 
```
`jsPanel.zi` is a function that runs only once when the first panel is created and returns a method `next()` that in turn returns the next `z-index` value to use. So every new panel calls `jsPanel.zi.next()` to determine its z-index.

**Comment by temuri416** [comment]
Hmm, having problem with `jsPanel.ziBase = 1000;`.

Traced the code and saw that `jsPanel.zi = function () {...}` is called when jsPanel is being loaded. I cannot add `jsPanel.ziBase = 1000;` before jsPanel is created and if I add it after, `jsPanel.ziBase` is already set default value of 100 and `jsPanel.zi` is already defined.

Do you mind creating a small codepen example to show how to set initial ziBase value?

Thanks!

**Comment by Flyer53** [comment]
Yes you can and should call `jsPanel.ziBase = 1000;` **before** you create the first panel.

`jsPanel.zi` is a method that runs only **once** when the very first panel is created - the reason is it needs to read `jsPanel.ziBase` to get the base z-index. And for that the object `jsPanel` must be defined.

**Comment by temuri416** [comment]
That's what I'm saying - setting `jsPanel.ziBase = 1000;` before I create the first panel is ignored.

**Comment by Flyer53** [comment]
Just wanted to do the codepen example and see it doesn't work there :(
It works in all my tests on my local machine though.
Ok ... I need to check that out, sorry!

**Comment by Flyer53** [comment]
Seems to be an issue with the beta.2 release.
Try beta.2.23 please - http://alpha.jspanel.de/downloads/jspanel-4-beta.zip

Or just go to http://alpha.jspanel.de/ and copy/paste
```javascript
jsPanel.ziBase = 1000;

jsPanel.create({
  callback: function() {
    this.content.textContent = this.style.zIndex;
  }
});
jsPanel.create({
  position: 'center 40 40',
  callback: function() {
    this.content.textContent = this.style.zIndex;
  }
});
```
to see it works.

**Comment by temuri416** [comment]
Yes! That fixed it :-) Thank you so much.

**Comment by Flyer53** [comment]
Your welcome :)
