### ISSUE TITLE
Feature Request: loading external content inside jsPanels that typically would generate X-Frame error

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#151]
For Teachers like me, it gets very complicated when you want to show reading content from different websites to your students without the need of opening a dozen more tabs on your browser and lose their attention quickly.

Is there a way to implement this feature inside jsPanel to be able to load external websites that typically would give you X-Frame errors?

Thanks and #StaySafe.

**Comment by Flyer53** [comment]
Hi Hugo,
Well, as far as I can say there is no way to achieve what you want.

It's exactly the purpose of `x-frame-options` to allow or disallow loding content from another domain into a `frame`, `iframe`, `object` or `embed` element.

The only option I see is that whoever is responsible for the setting of the page you want to load content from reconfigures the x-frame-options to allow your domain. So you would have to contact each responsible person and ask for it. Probably involves quite some work for you and I doubt the success.

Regards,
Stefan

**Comment by Flyer53** [comment]
@inglesuniversal 
Is there anything more to say to this issue Hugo?

**Comment by inglesuniversal** [comment]
Thanks for your great help. I found a library that kinda does that but with some limitations. So your best bet is to have your content always enabling CORS access for a specific set of domains. Thanks again.
