### ISSUE TITLE
Prevent the default action of close button

### ISSUE THREAD

**Issue by alexwenbj** [Flyer53/jsPanel4#153]
First of all, thank you for this awesome panel.
What I want to know is, how can I prevent the default close action of close button,cause I want to do sth special for the content before closing the jspanel. I found this thread in StackOverflow,but it not worked for me:
`https://stackoverflow.com/questions/32758401/how-to-stop-function-in-event-handler`
Maybe this solution is expired for current version.

Thank you again.

**Comment by Flyer53** [comment]
My pleasure ... and thanks for the praise 😄 

How about the regular [option onbeforeclose](https://stackoverflow.com/questions/32758401/how-to-stop-function-in-event-handler)? But make sure you carefully read the docs

Of course the [event jspanelbeforeclose](https://jspanel.de/#events/jspanelbeforeclose) is still available, but option onbeforeclose should be the right place for your task.

**Comment by alexwenbj** [comment]
Yes,it worked.Thank you again.
Another question: according to this [https://jspanel.de/#methods/resize](https://jspanel.de/#methods/resize), the resize() method is for setting the contentSize, but in my code,it seems resizes the panelSize:
```
Panel.resize({
    width:  800,
    height: 600
}
```

**Comment by Flyer53** [comment]
The method resizes the whole panel as the docs say in the very first sentence: "This method resizes an already existing panel."
What is mentioned about _contentSize_ applies only to the default setting of the `size` parameter if omitted.

But I could make that a bit more clear, that's true...

**Comment by Flyer53** [comment]
If your issue is solved please close it.

**Comment by alexwenbj** [comment]
Yeah,resolved! Thank you for your kindness.
