### ISSUE TITLE
Loss of focus when opening a jspanel from another jspanel

### ISSUE THREAD

**Issue by afourmy** [Flyer53/jsPanel4#154]
Hello,

I'm seeing a strange behavior when I create a panel from another panel: the new panel loses focus and moves behind the first panel after a few milliseconds. I think his z-index is changing to be less than the parent panel.

I am using jspanel 4.10.0

Here's a demo of the problem :

![demo](https://user-images.githubusercontent.com/16152622/108762639-a4f0a580-7550-11eb-895b-ba640d8b460c.gif)

I am not 100% sure that this is caused by jspanel, but I don't see anything in my code that could explain this behavior, so I'm opening this issue in case you might have an idea what's going on.

Thank you

**Comment by Flyer53** [comment]
Hi Antoine,

I'm not aware of anything within jsPanel that could cause this issue and so far didn't receive any other report like this.

With a very quick test I could not reproduce the issue.
Is there any callback function that for some reason returns focus to the first panel?
Any other framework in use that might change `z-index` values?
Your demo shows that the new panel is on top at first as intended. And then something happens I can't explain either right now, sorry.

Regards,
Stefan

**Comment by afourmy** [comment]
Hello,

Ok thank you. It's probably my code then, perhaps another library I'm using that is changing the z-index. I will close this issue and keep investigating.

Thanks !

**Comment by Flyer53** [comment]
Ok... can you tell me what the z-index values of the two panels are after the second one vanished behind the first one?

**Comment by afourmy** [comment]
@Flyer53 

OK I have a better understanding of what happens now. Actually we see the problem in the video that I posted, but it's not obvious so I missed it at first.

1) I open a first jspanel which contains a bunch of buttons
2) I click on a button that will open another jspanel, that must be in front of the first one

But I am also using jspanel tooltips, and each button has a tooltip attached to it. The tooltip is triggered with a delay of 800ms in my case. As you can see in the video, 800ms after opening the second panel, the tooltip is displayed and it causes the first panel to be back in front.

On the other hand, if I move the mouse out of the button right after clicking it, the tooltip is never displayed so the second panel stays in front of the first one.

In order to fix it, I removed these lines in my project:
https://github.com/Flyer53/jsPanel4/blob/master/source/extensions/tooltip/jspanel.tooltip.js#L113-L115

Perhaps there could be an option in the `create` function of the tooltip to deactivate these lines that change the z-index, in case they have unintended side-effects like this.

Thanks

**Comment by Flyer53** [comment]
@afourmy 
Thank you very much for your investigations and detailed descripton 😄 

After checking this out a bit I agree that it's a good idea to add a configuration option for the tooltips to prevent fronting the parent panel when the tooltip is used inside panel content.
I'm working on an updated tooltip version and will post a link here once I have something ready you can test. It will probably default to not fronting a parent panel, so there won't be a need to change tooltip codes unless you want the parent panel fronted.

A question is: should the parent panel in question front when the button triggering the tooltip is clicked?

Happy coding,
Stefan

**Comment by afourmy** [comment]
> A question is: should the parent panel in question front when the button triggering the tooltip is clicked?

I suppose it should. But I guess it also makes sense that whenever a new panel is created, it should be "fronted" (from what I understand, that is already the case). So I suppose the chain of events would then be the following:
1) click on button => parent panel is fronted (in most cases, the parent panel was already in front anyway since you're clicking on a button inside it, so this step wouldn't be doing anything)
2) the callback of the click button triggers the creation of a new panel, which in turn is put in front (i.e in front of the parent panel too)

As for fronting the panel of a tooltip, I'm not sure in what cases this is useful: in most cases, the parent component of the tooltip would already be in front (since the tooltip was triggered), but if it is not in front, then you are no longer looking at whatever triggered the creation of the tooltip, so you probably don't want it to alter the z-index of the parent panel.

I guess in the end, it depends a lot on the use-case so having an option to make the fronting behavior optional is more than enough.

Thank you !

**Comment by Flyer53** [comment]
@afourmy 
Ok, I added an option `parentPanelFront` which defults to `false`. It prevents the "parent panel" from being fronted when a tooltip is created from inside its content section. Should work out of the box without a change in your code.
A simple demo is [here](https://alpha.jspanel.de/docs/demos/test-blank.html). The button in one of the panels creates a tooltip without fronting the "parent panel".

Download https://alpha.jspanel.de/downloads/jspanel-4.11.4-alpha.zip and check it out. The **tooltip** script is updated to v1.4.0

I didn't change anything else. As you said, it very much depends on the usecase.

Please let me know how it works out, thanks!

**Comment by afourmy** [comment]
@Flyer53 

Yes I just tested and it works fine ! 

Thanks !
