### ISSUE TITLE
MinimizeTo in div as in page

### ISSUE THREAD

**Issue by attyskater** [Flyer53/jsPanel4#159]
Hi,
I can't figure out if it's a bug or it was developed this way, but when using the minimizeTo parameter and indicating the id of a div, it correctly minimizes the dialog in that div, but the length takes up the whole div and the button to normalize the panel is not shown.
I attach a small example [here](https://jsfiddle.net/svz3hxot/).

If possible it would be very convenient to replicate the behavior of the web page minimize on any div. 

Thanks a lot

**Comment by attyskater** [comment]
Hi,

Thank you very much for the timely reply.Yes, the position is right. I created a quick test just to replicate the MinimizeTo behavior in a div.

Don't worry about it, just take your time to look at it. I'm not in a hurry!

Your library looks amazing! Great job ;)

**Comment by Flyer53** [comment]
Thanks for the praise 😄 

Ok, I made a small update to the css file. This takes care of the wrong width and missing normalize control (might need some more testing though).

**But there remains one hing you have to consider:** Using option **minimizTo** with a string value of either `'default'`, `'parent'` or `'parentpanel'` will create a special container (styled correspondingly) exclusively intended to take the minimized panel replacements.
But when you use **minimizTo** with a selector string the minimized panel replacements are simply appended to the referenced container which is styled according to your liking and might contain other content as well. So it might be better if you create your own dedicated container for the minimized panel replacements. 

Downlaod [v4.11.5-alpha](https://alpha.jspanel.de/downloads/jspanel-4.11.5-alpha.zip) for testing and please let me know how it works out.

Regards,
Stefan

**Comment by attyskater** [comment]
Thank you very much! I'm a little busy, but as soon as I can I'll do some testing. 

Thanks for your advice!

Regards,
Attilio

**Comment by attyskater** [comment]
Sorry, but I could only do some testing now. Everything seems to be working perfectly! Thanks

Regards,
Attilio

**Comment by Flyer53** [comment]
Fixed with v4.12.0 release
