### ISSUE TITLE
[BUG] contentSize callback no longer has "this"

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#16]
Hi Stefan,

In **v3** I was able to do this:

```js
content: function() {
    // Adding "<div class="myContentDiv">...</div>" here.
},
contentSize: {
    width: function() {
        return $('.myContentDiv', this).width() + 30;
    },
    height: 350
},
```

`this` was pointing to current panel instance, That way I was setting panel's width on the fly, depending on the width of its contents rendered in `content` callback.

However, in **v4** `width()` callback's `this` no longer points to the panel instance. Instead, it looks as in the attachment.

![image](https://user-images.githubusercontent.com/3987203/35577373-60238922-05af-11e8-85d5-ceeff376a4e7.png)

Would it be possible to provide panel instance as callback argument (or any other way)?

Thanks!

**Comment by Flyer53** [comment]
Copied ...
Let me check this out ...

**Comment by Flyer53** [comment]
Download [beta.2.24](http://alpha.jspanel.de/downloads/jspanel-4-beta.zip)

Functions passed to `contentSize`/`panelSize` `width` and/or `height` now receive the panel as argument and `this` also refers to the panel.

**Comment by temuri416** [comment]
I'll try ASAP and will update you!
