### ISSUE TITLE
js error when you start dragging a resize handle located at clientX==0 or clientY==0

### ISSUE THREAD

**Issue by eklmnop** [Flyer53/jsPanel4#160]
Hello,
Thanks for your efforts, we use **jspanel** in many projects. Recently our tester found that when she drags
the resize handles (with a mouse) sometimes a javascript error is 
thrown "Uncaught TypeError: Cannot read property '0' of undefined"

To reproduce an error the resize handle should be located close to the left or top side of the browser window

Revisiting the source (source/jspanel.js v4.11.4) at lines 3891-3892
startX = e.clientX || e.touches[0].clientX,
startY = e.clientY || e.touches[0].clientY,

when a resize handle is located at clientX == 0 or clientY == 0
then this value gives a boolean false and js engine evaluates the second predicate
e.touches[0].clientX which gives the error (cause e.touches is undefined)

It can be fixed, i think, as

startX = e.clientX || e.touches?e.touches[0].clientX:0,
startY = e.clientY || e.touches?e.touches[0].clientY:0,

**Comment by Flyer53** [comment]
Hi there,

Thank you very much for the report and a possible fix. I'll check it out as soon as I find some time.

Does it give you any more problems? Or is it just the error message without any negative side effects?

Regards,
Stefan

**Comment by Flyer53** [comment]
Meanwhile I could verify the issue. But your proposed solution doesn't fix it.

I'm on it ...

**Comment by eklmnop** [comment]
Hello Stefan,

 

the bug was discovered because in one of our projects we decided to show the js error diagnostics in (red colored) modal windows to end-users.

You know, usually these errors are rested peacefully in the console and no such messages are barely seen (except to the F12 users). 

But this time the red popup ... and the problem was reported to me. 

We had some malfunctioning in that project – that is why we start catching-and-displaying errors.

 

The project is still at the development stage. So a fix is not that urgent.

Sorry i can’t fund your job – the projects i participate in are low budget

 

Best regards,

Eugene Kitaev

**Comment by Flyer53** [comment]
Meanwhile I worked on this issue a bit and it seems to work now.

You can [download v4.12.0-alpha](https://alpha.jspanel.de/downloads/jspanel-4.12.0-alpha.zip) to give it a try.
And please let me know how it works out.

Regards,
Stefan

**Comment by eklmnop** [comment]
Yes, it seems fixed to me.

I bundled my code with jspanel-4.12.0-alpha/es6module/jspanel.js and since that can’t reproduce the error any more.

**Comment by Flyer53** [comment]
Fixed with v4.12.0 release
