### ISSUE TITLE
Close all open panels at once

### ISSUE THREAD

**Issue by huypxgear** [Flyer53/jsPanel4#167]
Hi, Is there any method that could remove all open panels?

**Comment by Flyer53** [comment]
Hi, there is no dedicated method to close all panels at once.
You can easily do this with:
```javascript
document.querySelectorAll('.jsPanel').forEach(function(panel){
  panel.close();
});
```
Or if you need to select a specific set of panels to close take a look at
https://jspanel.de/#global/getPanels

**Comment by Flyer53** [comment]
@huypxgear 
You opened this issue 4 weeks ago, I answered right away, and you didn't respond to my answer yet. I would find it appropriate to get some feedback...

**Comment by huypxgear** [comment]
@Flyer53 
Sorry for the delayed response. Thank you for the suggestion I already knew this.
It would be great if we have a dedicated method to close all panels rather than looping through all. Anw this library is great
