### ISSUE TITLE
jsPanel.hint annimations break panel.close()

### ISSUE THREAD

**Issue by syonfox** [Flyer53/jsPanel4#171]
Ok so I was unable to get the get code copied from the docs to work.
I believe the issue is in here:

## reproduce
on https://sharedgoalof.life
which is basic with jspanel@version v4.13.0
```javascript
//paste this into console with jspanel4

    function resNotify(res) {

        let closeCB = (panel) => {
            setTimeout(()=>{
                console.log('freken close: ',  panel.close(), '  panel: ', panel);
                // panel.close();

            }, 4000)
        }

        if (res.success) {
            jsPanel.hint.create({
                position: 'right-top 0 15 down',
                contentSize: '310 auto',
                content: res.msg,
                theme: 'success filled',
                headerTitle: '<i class="fad fa-check mr-2"></i>Success',
                //animateIn: 'animate__animated animate__bounceInUp',
               // animateOut: 'animate__animated animate__bounceOutUp',
                autoclose: {
                    time: '4s',
                    background: 'linear-gradient(90deg, rgba(255,0,0,1) 0%, rgba(0,255,17,1) 100%)'
                },
                // callback: closeCB
            });
        } else {
            jsPanel.hint.create({
                position: 'right-top 0 15 down',
                contentSize: '310 auto',
                content: res.msg,
                theme: 'danger filled',
                headerTitle: '<i class="fad fa-check mr-2"></i>Failure',
                animateIn: 'animate__animated animate__bounceInUp',
                animateOut: 'animate__animated animate__bounceOutUp',
                autoclose: {
                    time: '4s',
                    background: 'linear-gradient(90deg, rgba(255,0,0,1) 0%, rgba(0,255,17,1) 100%)'
                },
                // callback: closeCB
            });
        }
    }


resNotify({success:true, msg: 'Woo I work'});
resNotify({success:false, msg: 'Boo I dont'});
```
I think it might have to do with the animation not returning in here ~line 715. Is there a extra style I need to include for animations.

```
self.close = function (cb, closedByUser) {
      if (self.closetimer) {
        window.clearInterval(self.closetimer);
      }

      document.dispatchEvent(jspanelbeforeclose);
      self.statusBefore = self.status;

      if (self.options.onbeforeclose && self.options.onbeforeclose.length > 0 && !jsPanel.processCallbacks(self, self.options.onbeforeclose, 'some', self.status, closedByUser)) {
        return self;
      }

      if (self.options.animateOut) {
        if (self.options.animateIn) {
          jsPanel.remClass(self, self.options.animateIn);
        }

        jsPanel.setClass(self, self.options.animateOut);
        self.addEventListener('animationend', function (e) {
          e.stopPropagation();
          self.remove(self.id, closedByUser, cb);
        });
      } else {
        self.remove(self.id, closedByUser, cb);
      }
    };
```

**Comment by Flyer53** [comment]
@syonfox 
Hi there,
As far as I can see the only problem is that your page doesn't load the CSS for the animations. So the animation never starts and therefore no `animationend` event is fired.
In your examples you use third party CSS animations which are not included in jsPanel. As stated in the docs for options `animateIn` and `animateOut` there is only one built-in animation for each option. Either use those built-in animations or load the the CSS needed. In this case _**animate.css**_  from [https://animate.style/](https://animate.style/). Then it should work fine.

Hope this helps,
Stefan

**Comment by syonfox** [comment]
Thanks for the quick response that did solve the problem. hope your having a happy new year so far. 

Best,
Kier

**Comment by Flyer53** [comment]
You're welcome,

And yes ... I do 😏 

Happy coding and stay healthy
Stefan

**Comment by Flyer53** [comment]
@syonfox 
I just noted on your website that you use jsPanel within your PLAN Map tool. Could it be possible for me to see a working live version of that tool somehow? One of the big issues I have with jsPanel is that almost all use cases are on non-public sites, so I never really see how people use it ...

**Comment by syonfox** [comment]
Unfortunately there is no public demo for PLANmap but if you are willing to sign an nda I could probably setup a demo site with fake data for you.  If you are interested in that send an email to dev@syon.ca

I do however have a public project that uses jspanels https://bullchat.syon.ca this is not as advanced of an implementation but I plan on implementing some more advanced features.  This is in its alpha stage and should evolve over the coming months as I add encryption and utility.

additionally on my https://sharedgoalof.life/ModalLogic.html blog post I uses jspanels to embed sites using iframes.

If you have any questions feel free to reach out.

ps sorry for the lack of RTFM :) 

Best, Kier
