### ISSUE TITLE
Cannot move panel after manually resizing a maximized panel

### ISSUE THREAD

**Issue by umutamac** [Flyer53/jsPanel4#179]
I noticed a behavior that could potentially confuse or frustrate some users. I suppose I could call this a bug.

1. Open a panel
2. Maximize it with the button in the top toolbar
3. Manually resize the panel by click & dragging the edge in any direction with the mouse
4. The panel doesn't seem like it is maximized anymore,  but it is still in "maximized" state (Notice the maximize icon in toolbar. It doesn't change back after I manually take the panel out of maximized state)
5. I try to move the panel around by grabbing the toolbar, but the panel does not move

As an additional example, in https://jspanel.de, I can see this behavior in the panel for changelog.

I would expect the maximized state to be turned off automatically when I manually change the panel size 

If there is a known workaround that anyone can share in the mean time, it would be awesome.

**Comment by Flyer53** [comment]
Hi there ...
... and thanks for the report. It's something I have to investigate as soon as I find some time. Meanwhile please try the following workaround:
```javascript
jsPanel.create({
    resizeit: {
        start: function (panel, paneldata, e) {
            this.status = 'normalized';
            this.setControlStatus('maximize', 'show');
            this.setControlStatus('normalize', 'hide');
        }
    }
});
```
And please let me know how it works out for you.

**Comment by umutamac** [comment]
Hello again,

Your suggestion worked pretty much perfectly. I just changed the "this" to panel, since I was having a bit of an issue with Vue, but apart from that, it really ended up being a drop-in solution.
```
jsPanel.create({
    resizeit: {
        start: function (panel, paneldata, e) {
            if (panel.status == "maximized") {
                panel.status = 'normalized';
                panel.setControlStatus('maximize', 'show');
                panel.setControlStatus('normalize', 'hide');
            }
        }
    }
});
```

Thanks a lot for the quick response.

**Comment by Flyer53** [comment]
@umutamac 
You may download a [v4.14.1-alpha](https://alpha.jspanel.de/downloads/jspanel-4.14.1-alpha.zip) for testing which should fix the issue without a workaround. I would appreciate if you gave it a try and provide some feedback.
Thanks,
Stefan
