### ISSUE TITLE
[Feature request] Double click title bar to maximize/restore the panel.

### ISSUE THREAD

**Issue by elgs** [Flyer53/jsPanel4#18]
Looking at the stars now, this project definitely is underappreciated! I'm wondering if there's any chance to enable double click on the title bar, for the panel to maximize and restore themselves. Thank you so much for the awesome work!

**Comment by Flyer53** [comment]
@elgs 
Hey there ... and thanks for the praise :)

It's not built-in so far, but you can achieve this with
```javascript
jsPanel.create({
    callback: function (panel) {
        panel.titlebar.addEventListener('dblclick', function () {
            if (panel.status !== 'maximized') {
                panel.maximize();
            } else {
                panel.normalize();
            }
        });
    }
});
```

**Comment by elgs** [comment]
@Flyer53 Thank you so much!
