### ISSUE TITLE
Accessing element in iframe using jQuery.

### ISSUE THREAD

**Issue by MadTomT** [Flyer53/jsPanel4#183]
Hi.

I'm trying to replicate something I've got working with another window/panel script.

I'm loading my page using the following and adding jQuery and a js page.

```javascript
jsPanel.create({
    headerTitle: 'demo panel',
    content: '<iframe src="test.php" style="width: 100%; height: 100%;"></iframe>',
    callback: function() {
          var iframe = this.content.firstChild.contentWindow.document
		
	  var Link = document.createElement("script") 
	  Link.src = "jquery-min.js"; 
	  Link .type = "text/javascript"; 
	  iframe.body.appendChild( qLink );
		
	  var js = document.createElement("script") 
	  js.src = "test.js"; 
	  js .type = "text/javascript"; 
	  iframe.body.appendChild( js );
      }
});
```

This seems to work with jQuery and the js is available.

In the test.js I'm finding a form, cloning it and adding it to another element. This is working in the other app, but doesn't seem to do anything in jspanel.  This is the code I'm using:

 ```javascript
form = $('.menu form').clone()
form.find("[name='submit']").remove();
	
$('.home div:first-child').after("<div id='newform'></div>");    
$('#newform').append( form ); 
```

Could anyone advise what I'm doing wrong and how to get this working with jspanel.

Thanks

**Comment by Flyer53** [comment]
I personally don't think it's aproblem related to jsPanel.
Could it be related to the peculiarities of `iframe` elements?

**Comment by MadTomT** [comment]
Hi,
Thanks for the reply.
The issue appears to have been how I was referencing the content within the iframe.
I'm now using the following and it seems to be working.

```
		callback: function( panel ) {
			panel.querySelector('iframe').onload = function(){
				
				var iframeDoc = panel.contentDocument || panel.contentWindow.document;
				
				var Link = document.createElement("script") 
				Link.src = "jquery-min.js"; 
				Link .type = "text/javascript"; 
				iframeDoc.body.appendChild(Link);
				
			};
		}
```

One question, the `panel.querySelector('iframe').onload = function` seems to be triggered every time a page within the iframe is loaded or reloaded. This is perfect for what I need but want to make sure that is how the callback is meant to be working.

Thanks

**Comment by Flyer53** [comment]
The callback you set up with the panel's `option.callback` is executed only once after the panel was created.
But within this callback you set up an event handler for the `onload` event. And this handler is of course called each time the `onload` event fires. So if I understand you correctly it's working the way it's supposed to work.

**Comment by MadTomT** [comment]
Thanks that explains it. 😀
