### ISSUE TITLE
Bring panel to front.

### ISSUE THREAD

**Issue by MadTomT** [Flyer53/jsPanel4#184]
Hi,
Is it possible to click anywhere in an iframe panel to bring it to the front?

Currently I have to use the header bar.

Thanks

**Comment by Flyer53** [comment]
No, that's not possible. At least there is no simple way to achieve this as far as I can tell.

Remember that an [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) represents a nested [browsing context](https://developer.mozilla.org/en-US/docs/Glossary/Browsing_context) and that whatever you display in an `iframe` **represents its own document**. So a click in this document does not happen in the host document and the panel itself is part of the host document, not of the doc in the `iframe`. In other words, the host document doesn't know that content in the iframe was clicked.
If it's worth the effort ... take a look at the [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) interface.

Regards,
Stefan

**Comment by MadTomT** [comment]
Thanks I had a feeling that would be the case. Thanks
