### ISSUE TITLE
Font and icon size of minimized panel replacement

### ISSUE THREAD

**Issue by MadTomT** [Flyer53/jsPanel4#186]
Hi,

I'm creating my panel and have set `headerControls: 'xs',` this looks fine apart from when the panel is minimised the the font and icons appear larger not xs.

Have I missed a setting ?

Thanks

**Comment by Flyer53** [comment]
Hi there,
No, you don't miss anything. It's just that the minimized replacements always have the same size regardless of the setting for the header controls. In cases where more than one panel is used and the panels have different size settings for the controls it wouldn't look that well visually if the minimized replacements had different sizes also.

Do all your panel use the same setting for `headerControls` concerning their size? Then I might have a simple hack for you.

**Comment by MadTomT** [comment]
Hi, 
All the panels are using the same `headerControls` setting.
Thanks

**Comment by MadTomT** [comment]
Thanks this is working perfectly. :)
