### ISSUE TITLE
TS2304: Cannot find name 'jsPanel'.

### ISSUE THREAD

**Issue by R1cro** [Flyer53/jsPanel4#19]
I'm using `require` to include jsPanel into my code, but I don't understand how to define jsPanel into require section:

```
 require(["../../components/jspanel/jspanel", "css!../../components/jspanel/jspanel"], () => {
                            this.jsPanelConstructor = jsPanel;  // << TS2304: Cannot find name 'jsPanel'.
                            this.addJsPanelIntoPanoramaViewer();
                        })
```
But all is working fine. I just want to define this jsPanel before I can use him.

So, any ideas?

**Comment by Flyer53** [comment]
@R1cro 
It seems you use _require.js_ od _node_ or any other library using a _require_ statement. Although I didn't work with javascript _modules_ so far I think I can say that a require (or any other import) statement works only if the "required" resource/module **exports** something.
jsPanel is a javascript lib that exposes the variable **jsPanel** in the golbal scope. But it doesn't export anything using any kind of _export_ statement.

I plan to add additional files to the repo that provide jsPanel as native javascript module. Possibly with the coming beta.3 this month already.  So be a little bit patient and check the repo once in a while. Or subscribe to the [newsletter](http://jspanel.de/contact.html) and you'll be notified when I publish a new release.

Hope I could help

**Comment by R1cro** [comment]
Thank you for answer, @Flyer53.
