### ISSUE TITLE
Can JsPanel drag and drop with two windows ?

### ISSUE THREAD

**Issue by davidbourrel** [Flyer53/jsPanel4#190]
Hi ! 

Thanks a lot for your library, you did a really good job !

I'm working on a new feature and I wonder if JsPanel can drag and drop something from a window to another window ? 

To be more specific, I'm working with Tabulator library and I want to drag a row like this : http://tabulator.info/examples/5.3?#movable-between-elements to another window (like a simple list just for test) but I wonder if is it possible or not ? 

Sorry for my english skills

Thank you !

**Comment by davidbourrel** [comment]
![image](https://user-images.githubusercontent.com/64352100/178738364-730681f9-805b-4766-99f7-00b2a94fe1b1.png)

**Comment by Flyer53** [comment]
Hi there ... and thanks for the praise 😄 
And don't worry about your English ... mine won't be better ...

With "drag and drop" I assume you mean a drag/drop operation from one jsPanel to another jsPanel in the same page. Or from a jsPanel to some other element in the same page. Or did I misunderstand you?
In case I'm right, such a drag/drop operation is all about the content of a jsPanel. And that's completely up to you. jsPanel does not implement any features working on the content of a jsPanel.
But if the tabulator library offers such a feature I don't see a reason why those features should not be usable within a jsPanel. In the end jsPanel is just another element in the page as all the other elements.

By the way: I opened the link to the tabulator examples in FF, Chrome and EDGE. Not a single one of those drag/drop examples worked.

Regards,
Stefan

**Comment by davidbourrel** [comment]
Ok thank you so much for your quick reply ! :D 

Your right it was from Tabulator inside a jsPanel to a content (list for the moment) inside another jsPanel.

Yes Tabulator has a strange drag and drop (it works if you keep left click pressed and you right click at the same moment xD). I think it's not a problem, it can be fixed by Tabulator later ^^.

Ok it could works so I'll try it !

Have a great day !
