### ISSUE TITLE
Text Overflow Bug in the Minimized Header 

### ISSUE THREAD

**Issue by Oliviero50** [Flyer53/jsPanel4#194]
**Describe the bug**
The updated `jspanel.css` file since the version `4.15` causes the text of the header of the minimised replacement to overflow.

**To Reproduce**
The bug is reproducible on the jsPanel.de website too.
1. Go to [jsPanel.de](https://jspanel.de/)
2. Open a window and minimize it with the minimize button.
3. See the unwantaed text overflow in the minimized header.

**Expected behavior**
The text-overflow of the minimized header should be set to ellipsis. ( three dots at the end, if overflow happens)

**Screenshot of the bug**
![image](https://user-images.githubusercontent.com/17961489/188095909-bc9bc4fb-821b-4e1d-a25f-91419b5b001a.png)

**Devices**
Reproducible on all devices and in all browsers.

**Additional context**
The bug first appeared in the _jsPanel version 4.15_, where the `jspanel.css` file was refactored in this [commit](https://github.com/Flyer53/jsPanel4/commit/3696ba4106c28b828382c84bf92de12163e7fd5d).
It appears that the css selector for `.jsPanel-hdr` right at the beginning of the file (line 57) was changed from `.jsPanel .jsPanel-hdr` to only `.jsPanel-hdr`.
However, the selector `.jsPanel-hdr` selects the header in both the main window and also the minimized replacement, whereas `.jsPanel .jsPanel-hdr` only selected the header in the main window.
This causes the minimized replacement header to get unwanted styling like `display:flex`, `flex-direction:column`, etc...

**Possible bug fix**
It should be enough to use the more specific selector `.jsPanel .jsPanel-hdr` again. 
This way, the unwanted styling will not be applied on the the header in the minimized replacement.

I also looked at other changes of the [commit](https://github.com/Flyer53/jsPanel4/commit/3696ba4106c28b828382c84bf92de12163e7fd5d) in the `jspanel.css` file and they shouldn't cause more problems like this.

Thank you for your work!

Kind regards
Oliver

**Comment by Flyer53** [comment]
@Oliviero50 
Thanks a lot for the report and detailed description. The change in the css file was necessary to improve the use of customized themes. I obviously missed this issue though.
Would you please try the preliminary [v4.16.1-alpha](https://alpha.jspanel.de/downloads/jspanel-4.16.1-alpha.zip) where this should be fixed.

Happy coding,
Stefan

**Comment by Flyer53** [comment]
fixed with v4.16.1 release
