### ISSUE TITLE
Ajax Content Timeout And Data Error 

### ISSUE THREAD

**Issue by mehmetalidumlu** [Flyer53/jsPanel4#2]
Hi, first of all thank you for this plugin you have created. I started using it right away. But I am having problems with ajax requests. I created default values ​​for the plugin. then I invoked a partial view from within the application. 
As a result I got this error: 

> Uncaught DOMException: Failed to set the 'timeout' property on 'XMLHttpRequest': Timeouts cannot be set for synchronous requests made from a document.
    at Object.ajax (http://localhost:2533/Contents/ExternalComponents/Plugins/JSPanel/dist/jspanel.min.js:1:4462)
    at Object.create (http://localhost:2533/Contents/ExternalComponents/Plugins/JSPanel/dist/jspanel.min.js:1:55382)
    at Object.ShowJSPanel [as Show] (http://localhost:2533/DojoComponent/Utilities/JSPanel/JSPanel.js:13:21)
    at HTMLButtonElement.<anonymous> (http://localhost:2533/DojoComponent/app/main.js:433:25)
    at HTMLButtonElement.dispatch (http://localhost:2533/Contents/ExternalComponents/Plugins/jQuery/jquery-2.2.4.min.js:3:7537)
    at HTMLButtonElement.r.handle (http://localhost:2533/Contents/ExternalComponents/Plugins/jQuery/jquery-2.2.4.min.js:3:5620)

The code block I wrote is: 

> JSPanel.Show({
                    Id: 'Get-Info-List',
                    ContentAjax: {
                        url: 'Partial/CallPartial',
                        data: {
                            PartialName: 'InfoItemList'
                        },
                        method:'GET',
                        async: false,
                        evalscripttags:true,
                        done: function (data, textStatus, jqXHR, panel) {
                            this.content.empty();
                            this.content.css('padding', '5px').append(data);
                        },
                        fail: function (jqXHR) {
                            this.setTheme('danger')
                                .headerTitle('<i class="fa fa-exclamation-triangle"></i> İstek Başarısız')
                                .content.append(jqXHR.responseText).css("padding", "20px");
                        },
                        always: function (arg1, textStatus, arg3, panel) {}
                    },
                    HeaderTitle: 'Bilgi Al'
                });

![screenshot_2](https://user-images.githubusercontent.com/15678340/33757476-6286406a-dc0b-11e7-9f4d-2fa1b927177e.png)

 In the examples you prepared, I saw that the data parameter was not sent in ajax requests. 

> jsPanel.create({
container:'body',
    contentAjax: {
        url: 'Partial/CallPartial',
                        data: {
                            PartialName: 'InfoItemList'
                        },
        done: function (panel) {
            panel.content.innerHTML = this.responseText;
        },
        evalscripttags: true
    }
});

The above code block shows the following error message when it sends a request.
Error: The partial view 'CallPartial' was not found or no view engine supports the searched locations

![screenshot_1](https://user-images.githubusercontent.com/15678340/33757433-22d16b84-dc0b-11e7-8bf5-5cbf93f66192.png)

`Request Address: http://localhost:2533/Partial/CallPartial`

Can you help me with this?

Thank you again...

**Comment by Flyer53** [comment]
@mehmetalidumlu 
Hey there and thanks for your feedback :)

Before I try to dive into this a bit deeper I at least see an error in the done, fail and always callbacks. Please remember that jsPanel v4 does not make use of jQuery anymore. That means that I had to create my own XMLHttpRequest handling for jsPanel. That it turn means that the done, fail and always callbacks don't receive the same parameters as in jQuery's $.ajax() callbacks.
In jsPanel v4 option.contentAjax the callbacks done, fail and always receive **only the panel as argument**, not the number of arguments you know from jQuery. In all 3 callbacks the XMLHttpRequest object is available via the keyword **this**.

Another thing: As far as I know it's not recommended to use _async: false_ unless there is absolutely no way around it.

Would you please check those two issues first and give me a feedback.

Best regards, Stefan

**Comment by Flyer53** [comment]
@mehmetalidumlu 
Since you didn't answer to this for 3 months now I consider this issue as not relevant anymore.
