### ISSUE TITLE
The title bar is small and the close, etc. icons are not shown

### ISSUE THREAD

**Issue by samcov** [Flyer53/jsPanel4#202]
I'm not sure why this is happening, my guess is that there is some conflict with something else I'm using, because in a standalone page it works properly.

Are there any known libaries that bother this app?

**Comment by samcov** [comment]
It turns out that the css for a button in another css file completely screwed it up.

I commented out that one portion of the css and it works a treat!

**Comment by Flyer53** [comment]
Sorry that I didn't answer in time. I'm currently on vacation a few days.

Glad you could solve it already 👍
