### ISSUE TITLE
How to create toolbars?

### ISSUE THREAD

**Issue by eydun** [Flyer53/jsPanel4#203]
Thank you for this awesome project.

Is it possible to create toolbars in jsPanel4 as in jsPanel3? (https://v3.jspanel.de/api/#examples/toolbars)

**Comment by Flyer53** [comment]
Hi there,

Of course, for a footer toolbar take a look at
 https://jspanel.de/#options/footerToolbar
and for a header toolbar see
 https://jspanel.de/#options/headerToolbar

Regards,
Stefan

**Comment by eydun** [comment]
Thank you, I will try it 👍
