### ISSUE TITLE
Problem with modal of Bootstrap4

### ISSUE THREAD

**Issue by crisloliant** [Flyer53/jsPanel4#23]
Hi, 

I use Bootstrap 4 for my project and JSPanel V4 Beta but I tring use modal on JsPanel, This option not found because no detect modal windows and lock the all screen with modal-backdrop fade show.

**Comment by dneilson** [comment]
Do you have the modal in the panel?
Or append directly to the body?
I could see it doing that if the modal-dialogue was in the panel rendered itself.
It also appears to have a lower z-index than your nav bar in the pic
@crisloliant

**Comment by Flyer53** [comment]
@crisloliant 
It's not clear to me what your actual issue is? Please try to explain in more detail.

If you want to use a jsPanel as modal take a look at http://jspanel.de/docs/#extensions/modal.

If you use a Bootstrap modal the documentation is [here](http://getbootstrap.com/docs/4.0/components/modal/) for Bootstrap 4.x

**Comment by Flyer53** [comment]
@crisloliant 
I just made a quick test with a bootstrap 4 modal and there doesn't seem to be a problem. So you need to give me a more detailed description of the issue ...

Further, as @dneilson already said if you have the HTML for the bootstrap modal inside the jsPanel it doesn't work as expected (the modal backdrop blocks the bootstrap modal). 
From the bootstrap docs:
> Whenever possible, place your modal HTML in a top-level position to avoid potential interference from other elements. **You’ll likely run into issues when nesting a .modal within another fixed element.**

So I guess your problem would be solved if you place the bootstrap modal HTML as recommended in the bootstrap docs.

**Comment by crisloliant** [comment]
Thank You, update modal of Bootstrap 4 for Modal JSPanel.

**Comment by Flyer53** [comment]
@crisloliant 
You're welcome.
In case that means "problem solved" please close the issue.
