### ISSUE TITLE
Use extensions with es6module version

### ISSUE THREAD

**Issue by lucasduarte** [Flyer53/jsPanel4#24]
Hello,

I'm using jspanel4 es6module version with an Angular 5 app.

How can I use extensions like modal this way?

None of the extension are exporting any module

**Comment by Flyer53** [comment]
Hi Lucas,
The extension files don't need to export anything because they just extend the object `jsPanel` imported from `jspanel.js`

So with native javascript you can write:
```javascript
<script type="module">
    import { jsPanel } from './dist/jspanel.js';
    import './dist/extensions/modal/jspanel.modal.js';
    // import other extensions the same way ...

    // more code

</script>   
```

**Comment by lucasduarte** [comment]
Thank you @Flyer53 .
I am using angular and angular-cli, so I couldn't import it that way.

I went back to version without es6module
