### ISSUE TITLE
Modal dragit problem when a jsPanel with syncMargins already opened

### ISSUE THREAD

**Issue by lucasduarte** [Flyer53/jsPanel4#25]
Hello,

I am facing a problem with dragit option on a jsPanel modal.

If i open the modal with dragit, without any other jsPanel opened: `jsPanel.modal.create({dragit: true})`
it works like a charm. I can drag it without problems:

![image](https://user-images.githubusercontent.com/3685788/37095367-7d0ba4d2-21f4-11e8-893f-ff18fab69d41.png)

The problem occurs when I try to open a jsPanel.modal with dragit set to true and I already have anothe jsPanel with syncMargins option set to true:

When I open it's ok:

![image](https://user-images.githubusercontent.com/3685788/37095434-b1635112-21f4-11e8-9ffe-3a0f99f0d00b.png)

When I try to dragit it goes immediately off the screen:

![image](https://user-images.githubusercontent.com/3685788/37095506-e4784922-21f4-11e8-94d4-4492f441d1dd.png)

If the opened jsPanel syncMargins is set to false the modal dragit works well, the problem is having another jspanel with syncMargins: true opened

**Comment by lucasduarte** [comment]
I only could make it work by setting `dragit: {}` on opened jsPanel

**Comment by Flyer53** [comment]
Hi Lucas,
I can't reproduce this issue in exactly the same way. Demo video [here](https://youtu.be/VPYWTaXucHo)
The only issue I have is that the modal for some reason also uses syncMargins although the option is set to false. Do you observe this as well?
However, something is not working as intended and I have to investigate.

For a quick test I used the following code:
```javascript
jsPanel.create({
    contentSize: '600 350',
    position: 'center -50 -50',
    theme: 'primary',
    maximizedMargin: 50,
    syncMargins: true,
    callback: function () {
        console.log(this.options);
    }
});

window.setTimeout(function () {
    jsPanel.modal.create({
        theme: 'warning',
        dragit: true,
        callback: function () {
            console.log(this.options);
        }
    });
}, 2000);
```
Thanks for the report,
Stefan

PS: Why would it be necessary to drag a modal?

**Comment by lucasduarte** [comment]
@Flyer53 I reproduced the problem here: https://plnkr.co/edit/XN0QxdvIs7NPFgOR8fiv

I made it work with the empty dragit option on jsPanel workaround.

Here where i'm working they use modals as child forms, called by a main one. They want to be able to move it around to see informations on the caller form when needed and the modal one must have a backdrop and should block all other functionalities while it's opened.

Thank you

**Comment by Flyer53** [comment]
@lucasduarte 
Thanks for the Plunker demo ... and I found something (at least in the Plunker):

The height of the `<html>` and `<body>` elements don't go beyond the height of the `<h1>` in the demo. Set `<html>` and `<body>` elements **height** to **100%** and it works.

I assume it's a similar problem in your project. Let me know whether this is it ...

**Comment by lucasduarte** [comment]
@Flyer53 the html and body height was my problem.

I changed it to 100% and it worked like a charm.

Thank you man
