### ISSUE TITLE
[SUGGESTION] API method to return panel's current position and dimensions

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#28]
Hi Stefan,

Have you considered adding API methods that would return panel's X&Y, plus it dimensions?

Cheers!

**Comment by Flyer53** [comment]
There is something similar built-in already. Try
```javascript
var p = jsPanel.create({
    callback: function(){
        console.log(this.currentData);
    }
});
window.setTimeout(function(){
    p.reposition('left-top');
    console.log(p.currentData);
},1000);
window.setTimeout(function(){
    p.resize('600 300').reposition('left-top 20 20');
    console.log(p.currentData);
},2000);
```
Values stored in the panel property `currentData` are used/updated whenever a panel is resized/repositioned in order to pass the proper values to the `normalize()` method.
Depending on your needs it might be all you need already.

**Comment by temuri416** [comment]
ok, but will `p.currentData` populate if I don't fire `p.reposition()` ?

**Comment by Flyer53** [comment]
It's populated upon panel creation and updated
+ after `resize()` was called or
+ after `reposition()` was called or
+ after dragging with mouse/touch stopped or
+ after resizing with mouse/touch stopped

In other words `currentData` is updated whenever position/size values change that are relevant for normalizing a minimized/maximized panel. That means `currentData` does not update when you maximize or smallify a panel. Updating on maximize would overwrite the values needed to normalize the panel and smallify/unsmallify don't need those values at all.

**Comment by Flyer53** [comment]
What exactly do you mean with
> and, what to do if content is loaded in IFRAME or with AJAX?

Loading content doesn't change panel size/position. And when e.g. your AJAX done callback includes `panel.resize().reposition()` currentData is updated.
Am I missing something?

**Comment by temuri416** [comment]
I'd have to test that out, before I confuse you even more :-)

**Comment by temuri416** [comment]
Looks like `p.currentData` has everything I need :-)

Thanks!

**Comment by Flyer53** [comment]
@temuri416 
Is there anything more concerning this topic?
Otherwise be so kind an d close the issue.
Thanks
