### ISSUE TITLE
Bug: jsPanel.layout.restoreId crashes if nothing in local storage

### ISSUE THREAD

**Issue by LarryKlugerDS** [Flyer53/jsPanel4#30]
File: https://github.com/Flyer53/jsPanel4/blob/master/source/extensions/layout/jspanel.layout.js

    Line 46 fails when line 44:
        let panels = this.getAll(storagename),
    returns false because nothing was found in local storage.

A solution:

    Change line 44:
    let panels = this.getAll(storagename) || [],

**Comment by Flyer53** [comment]
Fixed with latest release.
