### ISSUE TITLE
Chevron Up Issue in latest beta

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel4#31]
Hi, I just updated to the latest beta and noticed when i minify (chevron up icon) the panel header disappears and you have to scroll to get it back. You can see it on the demo on the getting started page:

http://jspanel.de/getstarted.html#

Thanks

**Comment by Flyer53** [comment]
Oh sh....
And I thought I checked everything on all browsers.
Thanks for the report.

**Comment by Flyer53** [comment]
Ok, it was just a css issue.
A v4.0.0-beta.4.1 with the fix is out.

**Comment by whittssg** [comment]
Cool... thanks for the quick fix :+1:
