### ISSUE TITLE
Maximize

### ISSUE THREAD

**Issue by unk90** [Flyer53/jsPanel4#32]
Hello

Is it possilbe to add a panel into a container but when the panel is maximized fill the whole screen instead of the conainer?

**Comment by Flyer53** [comment]
Hi there,
currently there is no easy way to do this ... like setting a configuration option.
But there might be ways however. Let me try a few things and I'll post something here.
Might take a few days though ...

**Comment by Flyer53** [comment]
@unk90 
Since you did not to this issue for 3 months now I consider it done.
