### ISSUE TITLE
Collapse/Expand panel has problem

### ISSUE THREAD

**Issue by HamedFathi** [Flyer53/jsPanel4#34]
I tested your library `v4.0.0-beta.4 - 2018-03-30 17:50`

Seems you have a problem with Collapse/Expand panel.
I am using `Chrome 66.0.3359.181`. 
The problem does not exist in Firefox and Edge.

![untitled](https://user-images.githubusercontent.com/8418700/40388875-fe9ff4f4-5e25-11e8-8980-6a047f6aa1f8.png)

**Comment by Flyer53** [comment]
@HamedFathi 
Thanks for the report. All you need to do is an update to the latest version.
There the issue is already fixed.
