### ISSUE TITLE
How to remove LEFT and UPPER whitish border... see attached image

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#35]
On every JSPanel that I create I am getting this unwanted inner border which interestingly enough only appears on the left inner and top inner edge.

How can I remove it for ALL my JSPanels?

[https://mycloudvip-storage.s3.amazonaws.com/files/hugobarbosa/Photos/Public/zHiZDUKn3z.png](url)

PS.- iFrames work wonderful, but the YouTube one shows lots of ads and banners, is there a way to remove them?

**Comment by Flyer53** [comment]
@inglesuniversal 
The link above results in a 404. So I can't check the image ... Anyways, did you check already whether it comes from some other CSS you load? Nowhere in the jsPanel CSS I apply a border like this. On the contrary, jsPanel CSS deliberately sets jsPanel border to `0` for the outer panel `div`, header and content sections.

YouTube:
I don't think you'll have a lot of control over that issue unless you own the rights for the particular video. See [https://support.google.com/youtube/answer/132596?hl=en](https://support.google.com/youtube/answer/132596?hl=en)
There is a Stackoverflow post with one answer claiming to know a way to embed a video without ads.
https://stackoverflow.com/questions/13981310/embed-youtube-video-with-no-ads

**Comment by Flyer53** [comment]
@inglesuniversal 
Since sou did not answer to this issue for three months now I close it.
