### ISSUE TITLE
How can I disable the resize arrows so that users don't mess up with my windows?

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#36]
The more I use your script, the more I like it!

KUDOS Flyer53

**Comment by Flyer53** [comment]
@inglesuniversal 
Thanks for the praise 😄 

But what exactly do you mean with "disable resize arrows"?

Assuming you don't want a panel to be resizable use
```javascript
jsPanel.create({
    resizeit: false
});
```
If you want to disable the resizeit feature only temporarily use
```javascript
var panel = jsPanel.create({
    resizeit: {
        disable: true
    }
});
// in order to enable resizing again later use
panel.resizeit('enable');
```

**Comment by Flyer53** [comment]
@inglesuniversal 
Since sou did not answer to this issue for three months now I close it.
