### ISSUE TITLE
Add ability to make custom close event from headerControls

### ISSUE THREAD

**Issue by ljmerza** [Flyer53/jsPanel4#37]
I'd like to be able specify a different action if the close headerControl is clicked vs calling close() on a jsPanel instance or at least be able to differentiate between the two on the onclose event. I have different actions I want to perform based on how the jsPanel was closed.

**Comment by Flyer53** [comment]
@ljmerza 
You could make use of the fact that the `close()` method accepts a callback and combine this with option `onclosed`. Look at the following code:
```javascript
// the panel code
var panel = jsPanel.create({
  // an onclosed callback is called after a callback passed to the close() method
  onclosed: function () {
    if (!panel) {
      // the close() callback already set panel to undefined
      console.log('panel closed with close() method');
    } else {
      // var panel is still defined -> header control was used
      console.log('panel closed with header control');
    }
    panel = undefined;
  }
});


// the code to close the panel via close() method
if (panel) {
  // call close() only if panel is still defined
  panel.close(function () {
    // this callback is called prior the onclosed callback
    panel = undefined;
  });
}
```

**Comment by Flyer53** [comment]
@ljmerza 
Unfortunately you didn't respond to your question for over 3 months now. So I must assume it's irrelevant to you.

However, the next release might include an additional event `jspanelcloseduser` which is only fired if the close control is used.
