### ISSUE TITLE
Content width

### ISSUE THREAD

**Issue by naveensaravanan** [Flyer53/jsPanel4#39]
I set content width in % but after document lode it's convert to px Why?

**Comment by Flyer53** [comment]
**Where do you retrieve the pixel value from?** Normally the css width of the content section is always 100% after the panel is loaded. But retrieving a _calculated_ value will always return a pixel value, no matter how you defined the width before.

**Another point:**
If you set contentSize.width with 50% for example. Then I ask you 50% of what? The content section div is a child element of the panel's outer div which doesn't have a width (unless you set option.panelSize which would override contentSize). So the script reads the width of the panel's parent element and calculates a 50% width from that. The resulting value is a pixel value.

I hope this explains your issue. If not and you still think there is something wrong you need to provide a code sample because I can't reproduce any wrong behaviour concerning this.

**Comment by naveensaravanan** [comment]
OK i'm explain what i need. Look at image one i just set width in % then look at the second image it's display px why?
I don't want px is there any way to set responsive
![img_1](https://user-images.githubusercontent.com/15015972/42743652-72d4ecac-88e3-11e8-916a-485405d5a87f.png)
![img_2](https://user-images.githubusercontent.com/15015972/42743709-e0b11eb2-88e3-11e8-843a-d38c03950ff0.png)

**Comment by Flyer53** [comment]
**Applies to both width and height:**
A panel appended to `document.body` (which is the default) is positioned relative to the viewport and not relative to the document. (A default panel is always centered within the viewport and not within the document which might have completely different dimensions)
**So when you use a % value for width and/or height** of a panel appended to `body` the script calculates for example 49.5% width/height of the viewport and not of the document. In other words ... the visible viewport is considered the "parent element" of a panel appended to `document.body` as far as position and size is concerned. The calculation of a % value of the viewport size always ends up in a pixel value (dimensions of the viewport are not necessarily the same as of the document).

**Possible solution for you:**
Use css viewport length units for panels appended to `body`:
```javascript
jsPanel.create({
  panelSize: {
    width: '49.5vw',
    height: '55vh'
  }
});
``` 
I hope this solves your issue. Let me know how it works out ...

**Comment by naveensaravanan** [comment]
Ya its working perfectly but small issue how to manage position to responsive

**Comment by Flyer53** [comment]
The reason for showing px instead of % is the same as for width/height as explained above.
You might want to take a look at option [onwindowresize](https://jspanel.de/api.html#options/onwindowresize) and the various examples. Maybe that's all you need.

**Comment by naveensaravanan** [comment]
Thanks for your support

**Comment by naveensaravanan** [comment]
Hi
I have one question
     1. I used [container option](https://jspanel.de/api.html#options/container) but the window resize option did't work
How can i solve this problem

**Comment by Flyer53** [comment]
In this case you have to use `option.onwindowresize` with a **function** as parameter instead of just using `true`. See the exampke code below:
```javascript
jsPanel.create({
  container: '#testcontainer',
  panelSize: '80% 250',
  onwindowresize: function () {
    this.resize('80% 250').reposition();
  }
});
```

**Comment by Flyer53** [comment]
You highlighted your mistake yourself already:
When you place the panel inside a container other than `body` you have to go back to using **%-values** for `panelSize` (as I used for width in the code sample) if you want to size the panel relative to the container the panel is appended to. `vw` (viewport width) and `vh` (viewport height) don't care for the dimensions of whatever element in the page - they are length units relative to viewport size.

In your last code sample you only reposition the panel in the `onwindowresize` callback (no resize).
