### ISSUE TITLE
New tooltip extension question

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel4#4]
Hello,

On version 3 i was able to use the tooltip on item click ( i liked the style but didnt want it on hover).. So basically i created the tooltool tip panel on click.

With version 4 it is forcing me to use target ( i use target: e.target) but when i use this i have to first click the target, then hover over it. Version 3 allowed me to use any event to trigger the creation of the tooltip and then supply the element that i wanted the tooltip to "hover" over.

Is there a way to do this in V4?

Thanks

**Comment by Flyer53** [comment]
Hi again,
Ok, I have an updated beta for you to test. It includes an additional parameter **ttipEvent** for the tooltip config.
```javascript
jsPanel.tooltip.create({
    target:    '#ttip-example-1a',
    mode:      'sticky',
    ttipEvent: 'click',
    delay:     0, // might be useful with another event triggering the tooltip
    connector: '#E3E6E9',
    position:  {
        my: 'center-bottom',
        at: 'center-top',
    },
    headerControls: 'closeonly'
});
````
Download: http://jspanel.de/downloads/jspanel-4-beta.1.11.zip
Check it out and tell me how it works out please

Happy coding,
Stefan

**Comment by whittssg** [comment]
Havent tried it yet but do people still rely on delays? (delay:     0, // might be useful with another event triggering the tooltip) ... There is always someone with the worst computer in the world that messes up the time we assume should be good for everyone :)

**Comment by whittssg** [comment]
hmm.. i tried it but couldnt get it to work.. I want to call the function that creates the panel on my own.. For testing i put hello in the content field:
jsPanel.tooltip.create({
                        content: '<p>hello</p>',                    
                        target: e.target,
                        mode: 'semisticky',
                        ttipEvent: 'click',
                        connector: '#E3E6E9',
                        position: {
                            my: 'center-bottom',
                            at: 'center-top'
                        },
                        contentSize: '250 150',
                        theme: 'slategray filledlight',
                        headerRemove: true,
                        headerControls: 'none'
                    });

i see that the function is called on click but nothing shows, if i click again then it pops up, at first i thought it was because i was using an angular template hence why i swapped it with the hello. 

Not sure if this is correct but it looks like your code is watching for the click but i would like to call it myself.

Thanks as always

**Comment by whittssg** [comment]
I managed to work around it with a real nasty work around.. In angular, instead of calling the panel creation on click i call it on mouse over, so then when i click the element the panel is already created and is just listening for click (this was using your new version with the ttipevent click but it seems unnecessary if you did what you did in v3 where we could just create the panel  on our own and connect to what ever element. Thanks

**Comment by Flyer53** [comment]
I added a **tooltip on click** example to the tooltip docs (example 3) on
http://alpha.jspanel.de/docs/#extensions/tooltip
Works as expected ...
Although I have no idea how Angular might effect the jsPanel tooltips. But since the new code just swaps **mouseover** with **click** I wouldn't expect problems...

**Comment by Flyer53** [comment]
@whittssg 
Is there anything to do about this topic?
Otherwise I would close it ...

**Comment by whittssg** [comment]
all good thanks.
