### ISSUE TITLE
Right-click issue

### ISSUE THREAD

**Issue by Argun** [Flyer53/jsPanel4#40]
JS Panel is a great lib, but I encountered a weird behavior when drag panel with right-click. 
Steps as below:
1. Cursor stay on the panel header.
2. Hold the right-click and drag the panel.
3. Release the right-click.

You will find the panel is still draggable and always follow cursor position. This is on purpose or not, I think the panel should ignore the right-click drag(configuration).

Thanks in advance, Mr @Flyer53

**Comment by Flyer53** [comment]
@Argun 
Well, it's not exactly on purpose. But I wouldn't call it weird either. The dragit/resizeit interactions are started by a `mousedown` event followed by a `mousemove` event. Those events are fired regardless of whether you use the left or right mouse button. I personally don't see a problem with this and so I didn't implement anything to prevent a panel being dragged/resized with the right mouse button.

Do you have a use case where this causes a problem?

Regards, Stefan

**Comment by Flyer53** [comment]
Mmmh ... I never observed something like that before.
In what browser/OS combination does this happen?

**Comment by Argun** [comment]
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
macOS High Sierra 10.13.6

**Comment by Argun** [comment]
yes, Chrome Safari and Firefox have the same issue on Mac OS. Window(10) OS is OK.

**Comment by Flyer53** [comment]
@Argun 
I just released v4.1.0 which, among other things, limits draging/resizing and the controls to the left mouse button if a mouse is used.

**Comment by Argun** [comment]
thank you very much, I will upgrade to v4.1.0
