### ISSUE TITLE
jsPanel4 for Angular

### ISSUE THREAD

**Issue by naveensaravanan** [Flyer53/jsPanel4#41]
Hi
I'm new in angular. can you explain how to add and use jspanel in angular

**Comment by Flyer53** [comment]
Hi,
jsPanel is plain javascript without any dependencies and should therefore work with every other js framework. But there are no framework specific versions of jsPanel.
I personally don't work with any of those frameworks and won't be able to help you here, sorry.

Maybe the following link gives you some help concerning Angular: http://www.sharepointpals.com/post/Floating-panel-for-angular-js

**Comment by mostafabarmshory** [comment]
Dear @naveensaravanan , [here is a simple solution](https://stackoverflow.com/questions/51647839/how-to-use-jspanel4-with-angular-1-x/51695330#51695330)

**Comment by naveensaravanan** [comment]
Hi @mostafabarmshory  thanks for you answer. But i need latest version of angular.
I think its version 1.X. want component based version 4.x

**Comment by AviHafner** [comment]
Hi Stefan
Before you release the next new version 

it would be great if you could add parameter to yours jsPanel and all the extensions,
that Determines the viewport used to keep the panel visible ,
this is called Smart positioning to keep the panels within the Viewport

Please see the example of qtip2 from the wiki documents about qTip2 viewport ,
https://github.com/qTip2/qTip2/wiki/viewport

Yours
Avi Hafner
