### ISSUE TITLE
The attribute data in contentAjax versions 4.+.+ not working for me

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#42]
Hi Stefan

In jsPanel-3.9.2
I used **contentAjax** in this way 

type: "GET",
 url: 'GetEmployeeDetails/EngGetEmployeeDetails.ashx',
            data: {
                code: prmcode,
                panel: "y",
                type: ""
           },

In version 4. and above I could use the **contentAjax** only by this way: 

type: "GET",
	url: 'GetEmployeeDetails/HebGetEmployeeDetails.ashx' + '?code=' + prmcode +'&panel=y&type=',

_**Another serious issue**_
[I'm sorry that I was one of those who did not come back to you](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FFlyCH53%2Fstatus%2F1006470271828660224&widget=Tweet)

**Your friend always**
Avi Hafner

**Comment by Flyer53** [comment]
@AviHafner 
Hi Avi,

**option contentAjax in v4 visa v3:**
In **v3.x** `contentAjax` used jQuery's `$.ajax()` internally and so you could use all the parameters of `$.ajax()` in jsPanel's `contentAjax`. Most parameters of `contentAjax` were simply passed on to `$.ajax()` for further processing.
But **v4.x** doesn't depend on jQuery anymore as you know. So contentAjax now works with a native `XMLHttpRequest` object where everything is a little bit different.
[Example 2 of v4.x contentAjax](https://jspanel.de/api.html#options/contentAjax/example-2) uses the `data` parameter by the way. The passed data is accessed via `$_POST` and processed with a php file on the server side.

The other "serious" issue: Don't worry about that Avi. That was definitely **not** adressed to you!

Take care my friend,
Stefan 😄

**Comment by AviHafner** [comment]
Thanks

Yours
Avi
