### ISSUE TITLE
Urgent help -  jspanel does not working in IE

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#43]
hi Stafen
Please check your site https://jspanel.de/api.html#global/create in IE

the message that all my users get is 

-**jsPanelError: NO NEW PANEL CREATED!
The container to append the panel to does not exist or a container was not specified!**_

the messages upper in your site in IE
https://jspanel.de/api.html#global/create

yours
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
confirmed ... although I currently have no idea why this happens now.
I will start checking this as soon as I can ....
Sorry for the inconvenience Avi.

**Comment by Flyer53** [comment]
Ok Avi,
it seems that this bug appears only when using the minified version of the jsPanel script ... at least on my machine.
Would you please check how it works on your system with the **_unminified_** script.

Thanks in advance,
Stefan

**Comment by AviHafner** [comment]
Sorry Stafen Wrong Information

IE and jsPanel _**not working in my sites**_

**Comment by AviHafner** [comment]
Hi Stefan
when I am Using the unminified script of jsPanel
_**jspanel.js**_
  its work


Thanks yours 
Avi Hafner

**Comment by Flyer53** [comment]
However ... there is something wrong with the minified file and that needs to be fixed.
So thanks for the report Avi 😄
