### ISSUE TITLE
How to add jspanel with in div

### ISSUE THREAD

**Issue by naveensaravanan** [Flyer53/jsPanel4#44]
Hi 
jsPanel default generate based on body. will change the jsPanel with in the div

**Comment by Flyer53** [comment]
Hi,
yes, a default panel is appended to the `body` element ... if that's what you're saying. But what do you actually want to tell/ask me??
If you want to append the panel to another element than `body` take a look at [option container](https://jspanel.de/api.html#options/container).

**Comment by naveensaravanan** [comment]
Thanks for replay. I got answer
