### ISSUE TITLE
Question about loading external URL's within jsPanel

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#47]
Hello:

I own a second site, besides where my main project is hosted, and it's kind of weird that I am getting a CORS error when trying to load a small web player app which is hosted and running at that second location. 

I'm getting this message on the js log panel:

Refused to display 'https://mydomain.com/public/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Do you have a way of forcing to load an external site or webpage inside jsPanel ? or do I have to add some settings to that site?

Thanks... We have our project almost ready, so I will be sending you a VIDEO of how nice your script integrates with our environment, and we sure hope to become a paying supporter of your present and future projects.

Best regards,

Hugo Barbosa

**Comment by Flyer53** [comment]
Hi Hugo,

you have to set a `HTTP Header` on the site serving the data. You could do this in the configuration file of the server or in a` .htaccess` file.
Take a look at https://enable-cors.org/server.html where they show how to enable CORS on a server.

Looking forward to see how you use jsPanel 😄 

Best Regards,
Stefan

**Comment by mostafabarmshory** [comment]
Dear @inglesuniversal , you can use HTTP IFrame instead. http ifram can be used to inject other websites into your own, for example, YouTube clips.

Disabling CORS is a security risk.

**Comment by Flyer53** [comment]
@inglesuniversal 
Since you did not respond to this issue in 3 months I assume it's not of relevance anymore and close it ...
