### ISSUE TITLE
Panel moving doesn't unbind

### ISSUE THREAD

**Issue by atotalnoob** [Flyer53/jsPanel4#49]
First off, awesome product! I love it! 

So I have a button that users click and it opens a JsPanel. If the **VERY** first thing you do is move the panel, it gets "stuck" and unable to exit the drag event. 

My configuration
```
jsPanel.create({
                            theme: 'primary',
                            headerTitle: 'Chatbot',
                            position: 'center-top 0 58',
                            contentSize: '800 600',
                            content: "<object width='100%' height='100%' data='myDataResource'></object>",
                            callback: function () {

                            },
                            onbeforeclose: function () {
                                return confirm('Are you sure you want to close?');
                            },
                            onclosed: function () {
                                $('#mybtn').removeAttr("disabled");
                            }
                        });
```

**Comment by Flyer53** [comment]
@atotalnoob 
Thanks for the praise :)

Can you confirm that it does not happen when you avoid a mouseover over the loaded object tag? Meaning you drag very carefully and the mousecursor never enters the content section in your case.

**Comment by atotalnoob** [comment]
Hey, 

Thanks for the fast reply! 

Moving it around without entering the content section it functions correctly. 

Do you think it is related to my object tags?

**Comment by Flyer53** [comment]
My pleasure ...

It's related to the object tag but not your fault. The same once happened when the content includes an iframe and I obviously missed to check the object tag.
Please try the attached js file and let me know how it works out.

[jspanel.min.zip](https://github.com/Flyer53/jsPanel4/files/2266514/jspanel.min.zip)

**Comment by atotalnoob** [comment]
Working fine now! Thanks!!
