### ISSUE TITLE
jsPanel doesn't work with jquery getScript

### ISSUE THREAD

**Issue by atotalnoob** [Flyer53/jsPanel4#50]
Running:
```
$.getScript("/lib/jspanel/jspanel.min.js").done(function (data, textStatus) {
jsPanel.create({.....});
}
```
jsPanel is undefined meaning this fails. The jquery getscript function executes the script after load, and its variables aren't accessible. 

My current solution: 
I added a function to jsPanel.js:
```
function GetJsPanel() {
    return jsPanel;
}
```

And then call it using: 

```
var jsPanel; //outside of loading block for scope
$.getScript("/lib/jspanel/jspanel.min.js").done(function (data, textStatus) {
jsPanel = GetJsPanel(); 
jsPanel.create({.....});
}
```

I can make a merge request with this, if you'd prefer.

**Comment by Flyer53** [comment]
Hi again ...
I checked the following jQuery code ...
```javascript
$.getScript('dist/jspanel.js')
.done(function(){
  jsPanel.create();
});
```
... with FF, Chrome, Edge, Opera, Vivaldi, Brave and IE11. All browsers get it done as expected without any problem or error message whatsoever. So I guess there must be another issue in your case.

**Question:** Why would you load the jsPanel script with `$.getScript()`?  You also need to load the jsPanel css which cannot be loaded using `$.getScript()`.

**Comment by atotalnoob** [comment]
Hmm, odd. I spent a couple hours trying to get it to work... Must be something on my end. 


I load the css in dynamically as well. 


I have a chatbot application that we need to be able to easily embed into any existing platform with minimal effort. So I have 1 JS import that imports and loads all the js, css, etc. It makes it much simpler if the only thing our end users have to do is include one script in their page, rather than something more complex.

**Comment by Flyer53** [comment]
How about setting up your own function to load a script? Something like:
```javascript
function addScript(path, type, callback) {
  let script = document.createElement('script');
  script.onload = callback;
  script.src = path;
  script.type = type;
  document.head.appendChild(script);
}
```
and then call it like
```javascript
addScript('/lib/jspanel/dist/jspanel.min.js', 'text/javascript', function() {
    // do something
});
```
It's worth a try ...

**Comment by Flyer53** [comment]
@atotalnoob 
Do you still have any trouble concerning this issue?

As of version 4.1.0 there is a built-in method `jsPanel.addScript()` which loads and executes a script.

**Comment by atotalnoob** [comment]
A script or JSPanel script? 

My problem was jsPanel.create wasn't defined as a function, but if I returned it as a variable, it worked fine. 

Basically, I have a chatbot I want to embed into a page via only one script. So I have to load all of the dependencies for my bot dynamically into the page. 

My team has switched over to typescript (Highly recommend!). So all of the below is TypeScript.

```
let script = document.createElement('script');
            script.src = "/lib/jspanel/jspanel.min.js";
            script.onload = jpLoadHandler;
            document.head.appendChild(script);
```
jpLoadHandler:
```
   function jpLoadHandler() {
        //@ts-ignore
        jsPanel = <any>GetJsPanel(); // ignored because TypeScript needs a definition and we are loading dynamically, thus no definitions are there!
        let app = document.createElement('div');
        app.id = "#chat-app";
        jQuery(document.body).append(app);
        let appElement = jQuery('#chat-app');
        if (appElement != null && appElement != undefined) {
            jQuery('#chat-btn').on('click', function () {
                jQuery('#chat-btn').attr('disabled', 'disabled');
                if (useCase == "" || useCase == null || useCase == undefined) {
                    jsPanel.create({
                        theme: 'primary',
                        headerTitle: 'chat',
                        position: 'center-top 0 58',
                        contentSize: '700 500',
                        content: '<iframe width="100%" height="100%" src="src"></iframe>',
                        onbeforeclose: function () {
                            return confirm('Are you sure you want to close the chat?');
                        },
                        onclosed: function () {
                            $('#chat-btn').removeAttr("disabled");
                        }


                    });
                }
                else {
                    jsPanel.create({
                        theme: 'primary',
                        headerTitle: 'chat',
                        position: 'center-top 0 58',
                        contentSize: '700 500',
                        content: '<iframe width="100%" height="100%" src="src"></iframe>',
                        onbeforeclose: function () {
                            return confirm('Are you sure you want to close the chat?');
                        },
                        onclosed: function () {
                            $('#chat-btn').removeAttr("disabled");
                        }


                    });
                }
            });

```

**Comment by Flyer53** [comment]
`jsPanel.addScript()` loads any script like the function _addScript_ I posted above. So it's just one more method of the global object `jsPanel`.

Thanks for all the infos. Looks like you found a working solution :)
Please close the issue if you consider it done.

_**Typescript**_ is not a topic I dived into yet. But I agree that it would be worth the effort ... someday I might start ... maybe ;)
