### ISSUE TITLE
headerTitle and headerLogo are not updated if the panel is minimized

### ISSUE THREAD

**Issue by akstek** [Flyer53/jsPanel4#52]
If I use the method setHeaderLogo(), or setHeaderTitle() while the panel is minimized the properties are not updated on the minimized container.

**Comment by Flyer53** [comment]
@akstek 
Confirmed!
Please try attached file (don't mind the version number) and let me know how it works out. Assuming it works it will be in the next release. My first tests seem to work out fine ...
[jspanel.min.zip](https://github.com/Flyer53/jsPanel4/files/2315400/jspanel.min.zip)

**Tip:** In case your logo is a SVG you might need to use the callback of `.setHeaderLogo()` to set CSS width and/or height of the SVG

**Comment by akstek** [comment]
@Flyer53 
Thank you for the fast fix! I can confirm that it's working,

**Comment by Flyer53** [comment]
Issue fixed with v4.2.1
