### ISSUE TITLE
New Windows creation

### ISSUE THREAD

**Issue by oddjobz** [Flyer53/jsPanel4#54]
Hey Stefan, hope you are well!
I'm using jsPanels (4) on a new project and it's working really well, but I've run into a slight issue that I can't seem to solve. I'm creating a number of panels in quick succession, and I'd like to have them "stacked", which is something earlier versions did. For some reason, all I can seem to manage is either overlayed (i.e. all on the same spot) which seems to be the default, or side by side, using "position" "at" "my". Is there a working stacking example somewhere I could look at for V4?

**Comment by Flyer53** [comment]
Hey Gareth,
Yeah I'm fine, thanks :)
How about yourself?

There are several options that might work for you:

**No 1: offsets** - [jspanel.de/api.html#options/position/offset-params](https://jspanel.de/api.html#options/position/offset-params)
That's basically what previous jsPanel versions did ... counting panels and calculating offsets
```javascript
var panel_1 = jsPanel.create({
  position: 'left-top',
  headerTitle: 'panel_1'
});
var panel_2 = jsPanel.create({
  position: 'left-top 50 50',
  headerTitle: 'panel_2'
});
var panel_3 = jsPanel.create({
  position: 'left-top 100 100',
  headerTitle: 'panel_3'
});
```

**No 2: parameter `autoposition` of option position** - [jspanel.de/api.html#options/position/auto-params](https://jspanel.de/api.html#options/position/auto-params)
This will position the panels underneath the previous one. Closing a panel will reposition the remaining panels.
```javascript
var panel_1 = jsPanel.create({
  position: 'left-top down',
  headerTitle: 'panel_1'
});
var panel_2 = jsPanel.create({
  position: 'left-top down',
  headerTitle: 'panel_2'
});
var panel_3 = jsPanel.create({
  position: 'left-top down',
  headerTitle: 'panel_3'
});
```

**No 3: position parameter `of` plus offsets**
```javascript
var panel_1 = jsPanel.create({
  position: 'left-top',
  headerTitle: 'panel_1'
});
var panel_2 = jsPanel.create({
  position: {
    my: 'left-top',
    at: 'left-top',
    of: panel_1,
    offsetX: 50,
    offsetY: 50
  },
  headerTitle: 'panel_2'
});
var panel_3 = jsPanel.create({
  position: {
    my: 'left-top',
    at: 'left-top',
    of: panel_2,
    offsetX: 50,
    offsetY: 50
  },
  headerTitle: 'panel_3'
});
```

Let me know whether you can use one of those options.

Regards,
Stefan

PS: What about your old Ionman project? Still existing somewhere?

**Comment by Flyer53** [comment]
I think about adding support of functions for ALL `option.position` parameters. Might make it even more flexible ...

**Comment by oddjobz** [comment]
Hi, not too bad .. :)
I'm using option 3 and still seem to be having the same problem, i.e. the things I'm trying aren't doing what I expect, in this instance I'm using #3 and I'm getting all windows in the middle of the screen, overlayed. It looks like I have something in the config that's causing a problem, specifically, looking at the html generated I have;
```html
<div
 class="jsPanel jsPanel-standard jsPanel-depth-3 jsPanel-theme-default"
 data-btnclose="enabled"
 data-btnmaximize="enabled" 
 data-btnnormalize="enabled" 
 data-btnminimize="enabled"
 data-btnsmallify="enabled" 
 data-btnsmallifyrev="enabled"
 id="jsPanel-1"
 style="z-index: 20; border-radius: 8px; width: 800px; position: fixed; left: 880px; top: 108.5px; opacity: 1; height: 497px;">
<div class="jsPanel-hdr jsPanel-theme-default" style="border-top-left-radius: 8px; border-top-right-radius: 8px;">
```
Yeah, I ran out of time on Ionman .. but it would be a good demo for what I'm doing now .. must dig out the source sometime and look it over .. :)

**Comment by oddjobz** [comment]
This is my create;
```javascript
    console.log('Create... of .. ', jsPanel._previous_panel)
    let panel = jsPanel.create({
      headerToolbar: '<p class="buttons"></p>',
      my: 'left-top',
      at: 'left-top',
      offsetX: 50,
      offsetY: 50,
      of: jsPanel._previous_panel,
      borderRadius: 8,
      template: tpl,
      maximizedMargin: 0,
      syncMargins: true,
      theme: 'primary',
      headerTitle: this._name + '@' + this._node,
      contentSize: {width: '800px', height: '480px'},
      iconfont: 'fa',
      onwindowresize: true,
```
with jsPanel._previous_panel = panel at the end ...

**Comment by oddjobz** [comment]
Not too bad .. brain isn't working tho' .. I was being an idiot and not putting the my/at/of inside a position {} .. :)
```javascript
    let position = 'center'
    if (jsPanel._previous_panel) {
      position = {
        my: 'center',
        at: 'center',
        of: jsPanel._previous_panel,
        offsetX: 50,
        offsetY: 50
      }
    }
```
I ran out of time on Ionman .. but it would be a good demo for what I'm doing now .. should probably dig out the code at some point and see what sort of shape it's in ... :)

**Comment by Flyer53** [comment]
@oddjobz 
Just released v4.2.1 (4.2.0 is skipped). As of this version all position parameters accept a function as value. So you could do something like ...
```javascript
var config = {
  position: {
    my: 'left-top',
    at: 'left-top',
    of: function () {
      var panels = jsPanel.getPanels();
      return panels.length > 1 ? panels[1] : 'window';
    },
    offsetX: function () {
      var panels = jsPanel.getPanels();
      return panels.length > 1 ? 50 : 0;
    },
    offsetY: function () {
      var panels = jsPanel.getPanels();
      return panels.length > 1 ? 50 : 0;
    }
  }
};
jsPanel.create({
  config: config,
  headerTitle: 'panel 1'
});
jsPanel.create({
  config: config,
  headerTitle: 'panel 2'
});
jsPanel.create({
  config: config,
  headerTitle: 'panel 3'
});
jsPanel.create({
  config: config,
  headerTitle: 'panel 4'
});
```
... to generate stacked panels.
https://jspanel.de/api.html#global/getPanels

**Comment by Flyer53** [comment]
@oddjobz 
Hi Gareth, is there anything open on this issue? Otherwise I'd ask you to close it.
Regards,
Stefan

**Comment by oddjobz** [comment]
@Flyer53 Sorry, yes, will close, many thanks, all good :) .. jsPanel is now well-integrated into the application and working flawlessly .. :)
