### ISSUE TITLE
Question: Implement the close button

### ISSUE THREAD

**Issue by GustavoArriola** [Flyer53/jsPanel4#56]
Hello!
I'm starting a project and I plan to use jsPanel (it looks great!)

The problem I have is that in my application I am opening several instances of jsPanel. Therefore, I have a unique method that is responsible for creating the panel and using AJAX charge the content thereof (including the accept / cancel buttons on the foot).

This is my implementation of jsPanel:

```javascript
        function ShowPopup(title, url, size, param) {
            jsPanel.create({
                theme: 'success',
                headerTitle: title,
                iconfont: 'fas',
                border: '2px solid #1bb394',
                boxShadow: 1,
                dragit: {
                    opacity: 1
                },
                contentSize: size,
                content: 'Loading...',
                contentAjax: {
                    method: 'POST',
                    url: url,
                    data: param,
                    done: function (panel) {
                        $(panel.content).html(this.responseText);
                    },
                    beforeSend: function () {
                        this.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    }
                },
                onfronted: function () {
                    jsPanel.getPanels().forEach(function (elmt) {
                        elmt.setTheme('bootstrap-secondary');
                        elmt.style.border = '2px solid gray';
                    });

                    this.setTheme('success')
                    this.style.border = '2px solid #1bb394';
                }
            });
        }

        $('.popupWindow').on('click', function (e) {
            e.preventDefault();
            ShowPopup($(this).data('title'), $(this).data('url'), $(this).data('size'), $(this).data('param'));
        });
```
How can I implement the close button similar to the button in the upper right corner?

I think I can not implement **footerToolbar**. I try to create a generic method for all my calls to the server. I was thinking of an attribute in HTML5 (data-xxx) on the html element as boostrap has it, but I do not know if this is possible.

Best regards,
Gustavo

![jspanel-contentfromserver](https://user-images.githubusercontent.com/13947325/46511757-6bebf500-c81e-11e8-90a7-41d15c551143.PNG)

**Comment by Flyer53** [comment]
Hi Gustavo,
I understand you want the button `Cancelar` to act as regular close button? If so you just need to add the event handler for the button to the **done callback of option.contentAjax**. Assume the button has the class `cancelar` then the done callback could look like:
```javascript
done: function (panel) {
    $(panel.content).html(this.responseText);
    $('.cancelar', panel.content).on('click', function() {
        panel.close();
    });
}
```
It would also be possible to add a footer toolbar with the buttons. A basic panel with a bootstrap button in a footer toolbar looks like:
```javascript
jsPanel.create({
  footerToolbar: '<button type="button" class="btn btn-outline-dark btn-sm cancelar">Cancelar</button>',
  callback: function(panel){
    $('.cancelar', panel.footer).on('click', function(){
      panel.close();
    });
  }
});
```
Hope I could help. If I misunderstood your question don't hesitate to write again ...
Regards,
Stefan

**Comment by GustavoArriola** [comment]
@Flyer53 thanks! 

it works perfectly!

Best regards,
Gustavo
