### ISSUE TITLE
jsPanel4 for Vue 2

### ISSUE THREAD

**Issue by houzw** [Flyer53/jsPanel4#59]
Hi, I have created a simple Vue  component  use  jsPanel4
https://github.com/houzw/simple-vue-components/tree/master/jsPanel

it maybe useful to some people 
or maybe someone could help to improve it

**Comment by Flyer53** [comment]
@houzw 
Thanks a lot 😄 
I appreciate that and added a link to your repo to the Getting-Started page and the FAQs.
Regards,
Stefan

**Comment by disitec** [comment]
Hey! We also created a wrapper for using this library in a Vue way. Take a look here! https://github.com/64robots/vue-js-panel

Awesome work!

**Comment by Flyer53** [comment]
@disitec 
Thank you so much :)
I added a link to your repo on the Getting-Started page and the FAQs as well
Regards,
Stefan

**Comment by lycxyz** [comment]
Hey，I have a question about this tool,but wen I use npm run dev command,it occurs this error
Module build failed: Error: **Couldn't find preset "@babel/env" relative to directory "G:\\CollaborateModeling\\GeoProlemSolving\\GeoProblemSolving-front\\node_modules\\_vue-js-panel@0.0.1@vue-js-panel"**,how can I solve it?

**Comment by Flyer53** [comment]
@lycxyz
This doesn't seem to be related to jsPanel directly.
But if you make a Google search with `Couldn't find preset "@babel/env" relative to directory` you get a bunch of results ... https://www.google.com/search?client=firefox-b-d&q=Couldn%27t+find+preset+%22%40babel%2Fenv%22+relative+to+directory
