### ISSUE TITLE
Error using extension with es6module and webpack

### ISSUE THREAD

**Issue by Lock-up** [Flyer53/jsPanel4#60]
Hi,
I use the es6module version of jspanel4 when I try to add the modal extension I get following error:

>Uncaught ReferenceError: **_jsPanel_** is not defined 

the error occurs in jspanel.modal.js
>96: jsPanel.modal.ziModal = (function(startValue = **_jsPanel_**.modal.ziModalBase) {

The problem is how webpack packs the file.

Input:
```
 jsPanel.modal.ziModal = (function(startValue = jsPanel.modal.ziModalBase) {
    let val = startValue;  
    return {
        next: function() {
            return val++;
        }
    };
})();
```

Output:
```
_jspanel_js__WEBPACK_IMPORTED_MODULE_0__["jsPanel"].modal.ziModal = (function(startValue = jsPanel.modal.ziModalBase) {
    let val = startValue;
    return {
        next: function() {
            return val++;
        }
    };
})();
```

The problem is webpack doesn't resolve the **_jsPanel_** variable in the function paramter correctly.
If I change the input to:
```
jsPanel.modal.ziModal = (function() {
    let val = jsPanel.modal.ziModalBase;
    return {
        next: function() {
            return val++;
        }
    };
})();
```

Then it works fine, output:
```
_jspanel_js__WEBPACK_IMPORTED_MODULE_0__["jsPanel"].modal.ziModal = (function() {
    let val = _jspanel_js__WEBPACK_IMPORTED_MODULE_0__["jsPanel"].modal.ziModalBase;
    return {
        next: function() {
            return val++;
        }
    };
})();
```

I'm not sure if it is a issue in webpack or something else.
Do you have any idea?

**Comment by Flyer53** [comment]
@Lock-up 
Well, I don't use webpack, so I can only guess.
But after a quick google search it seems that webpack simply doesn't handle function default parameters.

Maybe the following link helps
https://stackoverflow.com/questions/42857868/webpack-default-parameters-es6

Sorry that I can't help any more at the moment ...

Thanks for your report :)

**Comment by Flyer53** [comment]
@Lock-up 
Ok, since there was a small detail that didn't work out as planned anyhow I made a little change to the latest v4.3.0-alpha3 that should also fix your issue.
Download https://alpha.jspanel.de/downloads/jspanel-4.3.0-alpha3.zip
Let me know how it works out please ...

**Comment by Lock-up** [comment]
@Flyer53 
Hi, 
thank you for your message, looks good!

I found one other issue, you imported the unminified version of jspanel in jspanel.modal.min.js
`import {jsPanel} from '../../jspanel.js';`

This adds the modal property only to this version not the minified. So I have to import the unminifed version to make use of the modal.

this is because webpack creates a unique variable for every import, that means the jsModal object from jsPanel.js is an other as the jsPanel.min.js.

Here is what webpack produces for jsPanel.min.js:
```
/* harmony import */ var _jspanel_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../jspanel.js */ "./node_modules/jspanel4/es6module/jspanel.js");
_jspanel_js__WEBPACK_IMPORTED_MODULE_0__["jsPanel"].modal||(_jspanel_js__WEBPACK_IMPORTED_MODULE_0__["jsPanel"]
```

And this is the jsPanel (minified) I use later:
```
/* harmony import */ var jspanel4_es6module_jspanel_min_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! jspanel4/es6module/jspanel.min.js */ "./node_modules/jspanel4/es6module/jspanel.min.js");
jspanel4_es6module_jspanel_min_js__WEBPACK_IMPORTED_MODULE_4__["jsPanel"].modal.create();
```

I hope it is clear what I mean.

**Comment by Flyer53** [comment]
@Lock-up 
Got it and thanks for the report. You're right with the on other issue which gets easily overlooked when creating all the files. I'll add a note to the docs when it's time for the release and hopefully won't overlook this again 😏

**Comment by Lock-up** [comment]
@Flyer53 
Nice thank you. Do you already have a release date?

**Comment by Flyer53** [comment]
@Lock-up 
If no other issue comes up I think it will be within the next 2 weeks ...

**Comment by Lock-up** [comment]
@Flyer53 
Ok, good to hear.
Maybe I found some issue in the alpha version you sen.
In the position function:

> 1402	        if (**_elmt.options_**.container === document.body) {
1403	            defaults.of = document.body;
1404	        }

It crashes because `elmt.options` is undefined.
**_elmt_** is a css selector: '#jsPanel-2'

Hope this helps.

**Comment by Flyer53** [comment]
@Lock-up 
Thanks for the hint ... I'll check that out.

**Comment by Flyer53** [comment]
@Lock-up 
Mmmmh ... I can't reproduce the error you posted above. Never had any issues with that, so right now I don't know what to do about this ...

**Comment by Lock-up** [comment]
Hi @Flyer53 ,
nice to hear just updated to the latest version.

Just some additional information for my other problem.
Before the update I used the following code to set the panel position:
```
jsPanel.position('#' + draggedPanel.id, {
    my: 'left-top',
    at: 'right-top',
    of: '#' + p.id,
    offsetX: SNAPMARGIN,
     offsetY: getOffset(draggedPanel.offsetTop, otherPanelTop)
});
```

With the update this doesn't work anymore and I even can't find the position function in the API documentation for the global object anymore.

So I changed it to the following which works:
```
draggedPanel.reposition({
    my: 'left-top',
    at: 'right-top',
    of: '#' + p.id,
    offsetX: SNAPMARGIN,
     offsetY: getOffset(draggedPanel.offsetTop, otherPanelTop)
});
```

So at the moment I'm not sure if it is a bug and I should open a new issue or if the global position funktion is obsolete.
But anyway thanks for your help!

**Comment by Flyer53** [comment]
@Lock-up 
Hey there,
The global positioning function is still there and usable of course. But not just as easy as before and I needed to update the docs and examples.
As a result of the change the element you want to position must have a property `options` of type `object` with a setting for option `container`. This is because option container now defaults to `'window'` and not to `document.body` as before. So it's still posible to use the global method `jsPanel.position()`. However, if you want to position an already existing panel then `reposition()` is the better option I think.

Docs are online again: https://jspanel.de/api.html#global/position

Examples using `jsPanel.position()` to position existing panels:
```javascript
jsPanel.create({
  id: 'panel-1'
});
jsPanel.position(document.querySelector('#panel-1'), 'center-top 0 60');
```
or
```javascript
var p = jsPanel.create();
jsPanel.position(p, 'center-top 0 60');
```

The problem in your previous code is you used a selector string but you now need an element object.

Hope this helps,
Stefan

**Comment by Lock-up** [comment]
@Flyer53 
Allright, thank you very much and thanks for your support!
Greetings Jan

**Comment by Flyer53** [comment]
@Lock-up 
I missed something important, so I updated the docs once more.
Only relevant if you want to position an element that is not a jsPanel.
