### ISSUE TITLE
how can I render the react component in the jsPanel

### ISSUE THREAD

**Issue by princenarendrapatil** [Flyer53/jsPanel4#62]

**Comment by Flyer53** [comment]
I would really appriciate if you could discribe your issue with some words ...
+ what do you want to achieve?
+ what did you try already?
+ what is the issue exactly?
+ error messages?
+ maybe some example code ...

**Comment by Flyer53** [comment]
@princenarendrapatil 
You did not respond to this issue for almost 3 months. So I consider it obsolete and close it.

**Comment by AienTech** [comment]
Hi @Flyer53 ,
So, it's kind of easy to imagine,

- we've got a react component
- the component must be rendered into the panel's `content` property.

as an example:
```
jsPanel.create({
  id: "panel-1",
  theme: "primary",
  headerTitle: "my panel #1",
  position: "center-top 0 58",
  contentSize: "450 250",
  content: <p>Hello World</p>,
  callback: function() {
    this.content.style.padding = "20px";
  }
});
```

this can also be illustrated as:
```
jsPanel.create({
  id: "panel-1",
  theme: "primary",
  headerTitle: "my panel #1",
  position: "center-top 0 58",
  contentSize: "450 250",
  content: <MyComponent {...props}/>,
  callback: function() {
    this.content.style.padding = "20px";
  }
});
```

regards

**Comment by gino8080** [comment]
@Flyer53 the correct approach is like https://github.com/priteshjha4u/react-jspanel4 done
https://github.com/priteshjha4u/react-jspanel4/blob/14fc7f77fd7d9aae711c691cb25b4165e95a4a30/src/App.js#L61

**Comment by Flyer53** [comment]
@gino8080 
Thanks for the hint 😄 
With the next release I'll add a link to this repo in the docs.
