### ISSUE TITLE
Feature Request - setControlStatus, add  hide,show 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#68]
currently there  is option  enable,disable,remove 
 i want you  to add  hide, show 

for example 
panel.setControlStatus('minimize','hide')
panel.setControlStatus('minimize','show')

**Comment by Flyer53** [comment]
Hi there,
I'll consider adding this in version 4.5.0 which will probably be released this month.

**Comment by alpastar** [comment]
thank-you

**Comment by Flyer53** [comment]
Just uploaded a v4.5.0-alpha7 which includes the `hide` and `show` parameters.
https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha7.zip

**Comment by Flyer53** [comment]
@alpastar 
feature implemented in v4.5.0
https://jspanel.de/api.html#methods/setControlStatus
