### ISSUE TITLE
feature request  , modal   closeOnBackdrop: {true,false} 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#69]
currently,  there is no option to prevent modal  from closing by clicking  backdrop  
so i want  an option  CloseOnBackdrop 

closeOnBackdrop : true  -> closing by click backdrop , 
closeOnBackdrop : false -> no-close by click backdrop(default)  

if   CloseonBackdrop == false , then  
 to close modal-panel,   one  must  do
1.  click close-button in modal-header 
2.  or, click ok, cancel button  in modal-footer (if provided)
3.  or,  close() by program

**Comment by AviHafner** [comment]
Hi Stefan ,
I vote for this proposal.
I wanted to make a similar request to this in the past.

yours
Hefner Avi

**Comment by Flyer53** [comment]
I'll consider this for the next release.

**Comment by alpastar** [comment]
thanks!!, it is working .....

**Comment by Flyer53** [comment]
@alpastar @AviHafner 
feature implemented in v4.5.0
https://jspanel.de/api.html#extensions/modal
