### ISSUE TITLE
feature request , add parameter to position shorthand string

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#70]
position-shorthand-string is very convenient especially with es6 Template literals(tick)
so if you make position-shorthand-string as an four-argument-string ,
i think  everyone will  become happy ^^
say 
element-position, container-position, offsetX ,  offsetY 

 i'm afraid is there any reason not doing so...

**Comment by Flyer53** [comment]
What do you mean with container-position?

**Comment by Flyer53** [comment]
The shorthand strings usable with option position are meant to simplify the most used positionings.
It never was not meant to allow for all positioning options available.

However, I can think about extending shorthand strings somewhat. But that will not happen with v4.5.0 already.

Btw:
If `option.container` is set to `"window"` (which is the default) `option.position.of` defaults to `"window"` as well.
So your first example posted above is the same as `"left-top 0 0"`.
Your second example doesn't make a lot of sense to me because it won't be within the browser viewport.

**Comment by Flyer53** [comment]
Can you provide a fully working example please that let's me reproduce the error.
The error messages you posted all originate in the positioning method. But your code sample doesn't use any particular positioning.

Note: `container: "window"` is the default, no need to put that in the panel config.

**Comment by alpastar** [comment]
found  villain !! ,   it depends  on  existence of  'position.of '

jsPanel.create( {
  id            : "_panel_img_mb",  // "panel_img_mb"
  headerControls: { maximize: "remove" } ,
  panelSize   : {width:"320px",height:"auto"}  ,
//contentSize : {width:'100%',height:'70px'} ,
  container   : "window"  ,
  content     : $("#div_es1")[0] ,
  position    : {
      my      :  "center",
      at      :  "center",
//    of      :  "window" ,     // don't omit,   causes error. 
      offsetX: 0,
      offsetY: 0
  } 
});
// Uncaught TypeError: Cannot read property 'classList' of undefined
// at Object.position (jspanel.js:1571)
// at Object.create (jspanel.js:3951)
-----------------------------------------------------------
no-error 

jsPanel.create( {
  id            : "_panel_img_mb",  // "panel_img_mb"
  headerControls: { maximize: "remove" } ,
  panelSize   : {width:"320px",height:"auto"}  ,
//contentSize : {width:'100%',height:'70px'} ,
  container   : "window"  ,
  content     : $("#div_es1")[0] ,
  position    : {
      my      :  "center",
      at      :  "center",
     of      :  "window" ,          // important  !! 
      offsetX: 0,
      offsetY: 0
  } 
});

**Comment by alpastar** [comment]
this  is  my wrapper-class  for  jsPanel ,  

var go_panel = {
 ..........

 //##################################################################
   modal : {
 //##################################################################
  //---------------------------------------------------------------------------------
   _opt_defa  : {
  //---------------------------------------------------------------------------------
      closeOnBackdrop:  false ,           // SON
      closeOnEscape  :  false ,           // SON
      theme          : 'primary' ,
      position       : 'center-top 20 50' ,
      dragit         : {
        cursor            : 'move',
        handles           : '.jsPanel-headerlogo, .jsPanel-titlebar, .jsPanel-ftr',
        opacity           : 1,
        disableOnMaximized: true
      } ,
    },

  //---------------------------------------------------------------------------------
   box : function(to_opt) {
  //---------------------------------------------------------------------------------
     o_opt = $.extend({},this._opt_defa,to_opt);
     jsPanel.modal.create(o_opt);
   },  
 }     // end of modal 
................
}    // end of go_panel 

go_panel.modal.box( ) ;

**Comment by Flyer53** [comment]
@alpastar 
I can't reproduce the errors you posted.
So if you still have them there must be something else that's wrong.

Even if I copy and paste the code you posted under _found villain !!_ I don't get any error. So at the moment I can't say what might be wrong.

**Comment by Flyer53** [comment]
@alpastar 
Feature implemented in v4.5.0
https://jspanel.de/api.html#options/position/shorthand
