### ISSUE TITLE
Snap boxes for trigger 'pointer' are offset by container size ... I think

### ISSUE THREAD

**Issue by fq-selbach** [Flyer53/jsPanel4#76]
I'm currently experimenting with jsPanel and so far I really like it :-) , but there seems to be an issue with the position of the snap boxes when using the pointer as trigger inside a container that is not 100vw/100vh. The CSS is correctly positioning them inside the container but they will only appear at a certain offset.
I believe this is because of:
`var pmx = e.touches ? e.touches[0].clientX : e.clientX` 
in combination with the code following: https://github.com/Flyer53/jsPanel4/blob/d9cd1890ecba72932cb114ef4061e1774f8f7cd0/source/jspanel.js#L938
... but I can't pin it down exactly.

I'm using the latest release version via CDN: https://cdn.plot.ly/plotly-latest.min.js

**Comment by Flyer53** [comment]
@fq-selbach 
Hey there ... and thanks for the report.
Confirmed! There's a bug I'll have to look into ...

**Comment by fq-selbach** [comment]
Thank for looking into it.
Actually I'm using the snap boxes as seen in the demo (https://jspanel.de/api.html#options/dragit/example-8c) to trigger functions and then it makes sense to use 'pointer' to distinguish between "normal" positioning and "positioning with action". It's kind of how Windows works.

**Comment by Flyer53** [comment]
I'm on it ... but since the currently implemented code involved seems a bit complicated I'll probably recode the whole thing. The general idea is there ... I'll try to get it done for the next release in a few weeks.

**Comment by Flyer53** [comment]
@fq-selbach 
Ok, I have a modified version for testing. If you want to give it a try download [v4.5.1-alpha.4](https://alpha.jspanel.de/downloads/jspanel-4.5.1-alpha.4.zip)
A new example using `trigger: 'pointer'` at https://alpha.jspanel.de/api.html#options/dragit/example-8d

Other updates in 4.5.1-alpha:
+ set size of controls - https://alpha.jspanel.de/api.html#options/headerControls/example-2
+ new theme modifier `'filleddark'` - https://alpha.jspanel.de/api.html#options/theme/example-2

**Comment by fq-selbach** [comment]
Great! It's working!! 🥇 👍 
Thanks a lot!
