### ISSUE TITLE
removeChild error

### ISSUE THREAD

**Issue by wangkenping** [Flyer53/jsPanel4#77]
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.  at HTMLDivElement.<anonymous> (http://192.168.0.104:8080/crm/plugins/jspanel/jspanel.min.js:1:20299)
(anonymous) @ jspanel.min.js:1

**Comment by Flyer53** [comment]
What do you expect me to do now?
Without a single piece of information beside the naked error message I can't do anything.
You really need to provide some more infos ...

**Comment by Flyer53** [comment]
@wangkenping 
Since you did not respond to this for almost 3 weeks now I assume it's not of importance anymore and close the issue.
