### ISSUE TITLE
Advice and guidance : How can I show a hint panel, when I have on the screen a modal panel

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#78]
Hi Stepan
your Advice : How can I show a hint panel, when I have on the screen a modal panel.
when i try to implement  the hint panel
Hiding under the modal panel.

Yours
Avi

**Comment by Flyer53** [comment]
Hi Avi,
Well, that's the idea of a modal ... to hide everything else. But there are two options that come to my mind to have a hint on top of a modal:

**1.** Manually reset z-index of the hint after it was created
```javascript
var modal = jsPanel.modal.create();

setTimeout(function(){
    var hint = jsPanel.hint.create({
        panelSize: '200 115',
        position: 'right-top -5 5',
        theme: 'danger'
    });
    hint.style.zIndex = 11000; // won't work in panel callback!
},1000);
// copy and paste to your dev tools to try it
```
**2.** Append hint to modal (of course requires hint to be smaller than the modal)
```javascript
var modal = jsPanel.modal.create();

setTimeout(function(){
    var hint = jsPanel.hint.create({
        panelSize: '200 115',
        position: 'right-top -5 5',
        container: modal,
        theme: 'danger'
    });
},1000);
```

Check it out and let me know how it works out.

Yours,
Stefan

**Comment by AviHafner** [comment]
Perfect.
Yours solution as always works like a charm.

yours 
Avi Hafner
