### ISSUE TITLE
Is there an 'unsnap' event?

### ISSUE THREAD

**Issue by fq-selbach** [Flyer53/jsPanel4#81]
I would like to add a CSS class depending on the snap status of a panel. Is there any event I could use?
I think this would be the line to modify (if there is none):
https://github.com/Flyer53/jsPanel4/blob/d9cd1890ecba72932cb114ef4061e1774f8f7cd0/dist/jspanel.js#L893

**Comment by Flyer53** [comment]
No, there is no `unsnap` event.
Did you try using the `dragstart` event or the `dragit.start` callback?

**Comment by fq-selbach** [comment]
I thought about it, but failed in the first try 😆. I think I got it now:
```
document.addEventListener('jspaneldragstart', function(event){
        var panel = document.getElementById(event.detail);
        if (panel.snapped && panel.options.dragit.snap.resizeToPreSnap && panel.currentData.beforeSnap) {
            document.dispatchEvent(new CustomEvent('jspanelunsnap', { detail: panel }));
        }
    });
```
Not that in my version I'm using 'resizeToPreSnap' as a condition.

**Comment by Flyer53** [comment]
Mmmmh ... I thought of something like
```javascript
jsPanel.create({
    dragit: {
        snap: {
            snapLeftTop: function () {
                // add/remove/switch class
            }
        },
        drag: function () {
            // add/remove/switch class
            // a panel can't be snapped anymore once you start dragging it
        }
    }
});
```

**Comment by fq-selbach** [comment]
I've decided to use the global event because the function in the options might be overwritten on panel creation. I'm generating panels with different default options and each of them could in theory have a different drag callback so I wanted to add some common behavior with the global listener.

**Comment by Flyer53** [comment]
Sounds good to me ... it just has to work for you 😏

**Comment by fq-selbach** [comment]
Looks good so far, I'll close the issue :-)
