### ISSUE TITLE
iframe overlay bug [part2]

### ISSUE THREAD

**Issue by fq-selbach** [Flyer53/jsPanel4#85]
From the previous discussion: https://github.com/Flyer53/jsPanel4/issues/79

If a panel has a child panel that has an iframe the methods `item.content.querySelector('.jsPanel-iframe-overlay')` and `item.content.querySelector('iframe')` will find that iframe and assume it belongs to the parent 😬

[EDIT1]: I've tried to fix this assuming that an iframe has to be a direct child of the content object with:
```
//var overlay = item.content.querySelector('.jsPanel-iframe-overlay');
var overlay;
if (item.content.children){
	for (var i=0; i<item.content.children.length; i++){
		if (item.content.children[i].classList.contains('jsPanel-iframe-overlay')){
			overlay = item.content.children[i];
			break;
		}
	}
}
if (index > 0) {
	//if (item.content.querySelector('iframe') && !overlay) {
	if (item.content.firstElementChild && item.content.firstElementChild.tagName == "IFRAME" && !overlay) {
```
But this will not work either because if you press the child panel this will trigger 2 calls to the "front" method, first to itself and AFTERWARDS to the parent. The 2nd call will then add the overlay again.

[EDIT2]: I'm currently using a hack that buffers the actual clicked item like this this:
```
// front panel on mousedown
this.pointerdown.forEach(function (item) {
	self.addEventListener(item, function (e) {
		if (!e.target.closest('.jsPanel-btn-close') && !e.target.closest('.jsPanel-btn-minimize') && options.paneltype === 'standard') {
			var underMouse = document.elementFromPoint(e.pageX, e.pageY);
			var $panel = $(underMouse).closest('.jsPanel');
			if ($panel.length > 0){
				jsPanel.lastFrontTargetPanel = $panel.get(0);
			}
			self.front();
		}
	}, false);
});
```
And then check for it in the iframe overlay test (followed by the code from EDIT1):
```
if (jsPanel.lastFrontTargetPanel && jsPanel.lastFrontTargetPanel == obj){
            // iframe extra: panel with an iframe get a content overlay if panel is not the topmost panel -> content section click fronts the panel
            this.getPanels().forEach(function (item, index) {
...
```
Note that I'm using jQuery `$(underMouse).closest` because the vanilla JS version has no IE11 support (which I'm not even sure is actually supported anyways).

**Comment by Flyer53** [comment]
Something to try:

`panel-1` is the parent panel
`panel-2` is the childpanel of `panel-1`
both have an `iframe`

**Do not append `panel-2` to `panel-1.content` but directly to `panel-1`**

`getChildpanels()` and `closeChildpanels()` called on `panel-1` and `isChildpanel()` will not work then because they expect the childpanel to be in the content section, but that could easily be dealt with in case the other thing works.

**Comment by Flyer53** [comment]
@fq-selbach 
Did you make any tests concerning this topic lately?

**Comment by fq-selbach** [comment]
Hi Stefan, I'm still using the hack described above. Served me well so far 😅

**Comment by Flyer53** [comment]
OK, since you have a working solution I'd ask you to close this issue. Or is there any urgent need to do someting more about it?
Regards, Stefan

**Comment by fq-selbach** [comment]
Hi Stefan,
this issue will probably come up again when/if we want to update jsPanel so it would be great to have an "official" fix. Unfortunately I cannot commit this fix due to the jQuery dependency ... I guess.

**Comment by Flyer53** [comment]
Experimenting with an idea I found a way to do without the iframe overlays that does not interfere with the dragit/resizeit actions. As a result you don't need a second click to activate something in an underlying panel with an iframe. Looked quite good at first glance, but ...

What if the underlying panel with the iframe neither has the header section nor a footer toolbar or even a padding for the content section/iframe?
Then there's nothing you could click on in order to front the panel. Every click in the panel would actually be a click in the source document of the iframe.

So the only way to make such a panel "frontable" would be either to:
+ not remove the header section
+ add a footer toolbar
+ add padding to the content section
+ add a border to the iframe
+ add a border to the panel

to have something to click on.

I'm afraid that such a solution would cause more trouble for the user than having to click twice.

What do you think?

**Comment by fq-selbach** [comment]
Hi Stefan. In our use-cases we usually have either a set of "static" iframe-panels in the background (arranged in a grid, they will never get fronted) or we have iframe-panels with a header (normal or a custom simplified header). I think it would be perfectly ok for the user to click on the header first if they want to front the panel and leave it behind other panels if they make a direct click.
Some (most) of the iframe-pages we use support the ´postMessage´ interface that would even allow us to transfer the in-frame click to the parent panel, but this would not work for pages like "bing.com" e.g..

**Comment by Flyer53** [comment]
Hi again,
mmmh, need to think about this a bit ...
However, I created a simple demo using a modified js file working without the overlays:
https://jspanel.de/docs/demos/iframe-in-several-panels.html

And you can download the modified test version from https://jspanel.de/downloads/jspanel-4.7.0-modified-iframe-handling.zip

The more I think about it I see the modified version as a good solution. Anyone using a content section only panel has to think about the consequences anyhow...

PS: Auf GitHub sollen es alle lesen können, aber sonst könnten wir doch auch auf Deutsch schreiben, oder?

**Comment by Flyer53** [comment]
Sure, it's so easy that I wonder why I didn't have this idea earlier ...
On **dragstart/resizestart** the CSS property `pointer-events` of all `<iframe>` elements in the doc are set to `'none'` and on **dragstop/resizestop** restored to `'auto'`.
I hope it works without any negative side effects ...

**Comment by fq-selbach** [comment]
Hi Stefan, sorry for the late reply but I've some challenges upgrading to the 4.7.0 version because there are so many code changes that I cannot easily transfer my custom "fixes" (the things we've discussed in the other issues). It will probably take some more time or I might even have to write my own version with the same "hack" to try it out.

**Comment by Flyer53** [comment]
@fq-selbach 
Take your time, no problem ...

**Comment by Flyer53** [comment]
@fq-selbach 
Any news on this issue?
As far as I see it there's nothing to do on my end ...

**Comment by fq-selbach** [comment]
@Flyer53 
We are still using the "workaround" mentioned at the beginning (EDIT 2). In the end this was more intuitive than having to click the header only to front the panel. At some point I'd like to spend some more time on this issue but currently it's on low priority for us. 
If the initial issue is fixed in your version due to the new method of handling the overlay feel free to close this here.
