### ISSUE TITLE
[feature request] hint ,  embedded progressbar 

### ISSUE THREAD

**Issue by alpastar** [Flyer53/jsPanel4#87]
1.
I  think  it would be better for  hint  to  shows-up  small progressbar 
when a  hint  have a  timeout.
sample : iziToast 
http://izitoast.marcelodolza.com// 

2. 
hint usually  have no-header-controls. 
so  i prepare close button in a content. 
but  if  hint(with no-header-controls)  have a option  to show-up close button , 
i think  every one will become more  happy^^

**Comment by Flyer53** [comment]
Hi there ... and thanks for your ideas.
Let me think about this a bit ...
Regards,
Stefan

**Comment by Flyer53** [comment]
@alpastar 
Concerning your point nr 2:
I added a corresponding feature to an updated hint extension. You find an example on https://alpha.jspanel.de/api.html#extensions/hint - see example 2
You can download the whole package (v4.7.0-alpha.1) [here](https://alpha.jspanel.de/downloads/jspanel-4.7.0-alpha.1.zip)

**Important note:** `v4.7.0-alpha.1` also includes completely recoded positioning methods. So if you use updated `jspanel.js` as well there might be some positioning issues. It should work quite well though and I would appreciate if you gave it a try.

**Comment by alpastar** [comment]
thanks,  those were busy days , so i forgotten this topic,
 i will try ....

**Comment by Flyer53** [comment]
@Flyer53 
I just updated to v4.7.0-alpha.2 with the following changes concerning your requests:
+ removed the extra close control from the hint extension and added it as regular option for all panels. See https://alpha.jspanel.de/api.html#options/addCloseControl
+ implemented a first version of option autoclose updated with an optional progressbar. See https://alpha.jspanel.de/api.html#options/autoclose and [hint extension example 2](https://alpha.jspanel.de/api.html#extensions/hint/example-2)

[Download latest alpha](https://alpha.jspanel.de/downloads/jspanel-4.7.0-alpha.2.zip)

Whenever you have time it would be great to get some feedback ...

**Comment by Flyer53** [comment]
@alpastar 
Updated to [v4.7.0-alpha.11](https://alpha.jspanel.de/downloads/jspanel-4.7.0-alpha.11.zip)
The progressbar seems fine to me. I just didn't decide yet whether I should make the progressbar a default or not?
Example: [alpha.jspanel.de/api.html#options/autoclose](https://alpha.jspanel.de/api.html#options/autoclose)

**Comment by alpastar** [comment]
@Flyer53   
looks beautiful ...  ^^

as a  developer, it would be better to be default (as long as autoclose == true) 
and   it would be better for progressbar to be shown to application user ,

so IMHO, it would be better to be default  when autoclose = true

**Comment by Flyer53** [comment]
@alpastar 
Agreed ... and updated to [v4.7.0-alpha.12](https://alpha.jspanel.de/downloads/jspanel-4.7.0-alpha.12.zip) where the autoclose progressbar is shown by default.
https://alpha.jspanel.de/api.html#options/autoclose

**Comment by Flyer53** [comment]
autoclose progressbar implemented in v4.7.0
