### ISSUE TITLE
control icon styles and sizing

### ISSUE THREAD

**Issue by Flyer53** [Flyer53/jsPanel4#89]
**I'm working on new built-in control icon SVGs and improved sizing.**

A preview is available [here](https://alpha.jspanel.de/api.html#options/headerControls).

I plan to activate the new SVGs with the update to jsPanel v4.7.0

You're welcome to share your thoughts ...

**Notes:**
1. currently the new built-in icons resemble Font Awesome 5 icons (regular)
2. custom sizing should be quite easy finally
3. minimized panels will generally have a little smaller icon size independent from icon size setting of main panel.
4. there is no more dedicated "unsmallify" icon (and no extra "unsmallify" control). When a panel is smallified the smallify icon is rotated by 180 degrees and the smallify control is used for both smallify and unsmallify

![control-sizes](https://user-images.githubusercontent.com/6769021/56794198-ee192680-680d-11e9-91ad-09849df6c109.jpg)

**Comment by oddjobz** [comment]
Ok, so the normalised window set with size=xs now looks good;
![screen1](https://user-images.githubusercontent.com/7396121/56834543-93adb380-6869-11e9-8093-e458608c9973.png)
However, this is what I see when the same window is minimised;
![screen2](https://user-images.githubusercontent.com/7396121/56834578-af18be80-6869-11e9-8334-dcdf23cdafe6.png)
Doesn't look quite right ...

**Comment by Flyer53** [comment]
Doesn't look like you updated to the latest [4.7.0-alpha.4](https://alpha.jspanel.de/downloads/jspanel-4.7.0-alpha.4.zip)

**Comment by Flyer53** [comment]
updated in v4.7.0
