### ISSUE TITLE
Export main object and entry point for node module usage?

### ISSUE THREAD

**Issue by qdot** [Flyer53/jsPanel4#9]
Could you add an entry point pointing at dist/jspanel.js in your package.json, and export the var jsPanel in jspanel.js? That'd make things easier to use when building this into a node app. Happy to put in a PR too if needed.

**Comment by Flyer53** [comment]
Hi Kyle,
thanks for your input. But please consider that I'm not a trained programmer. jsPanel is sort of a hobby to keep my brain working 😏 

Everything about javascript modules, exports, imports and so on would be a completely new topic for me I don't know more about than that those features exsist. I understand your reasoning and I'm willing to learn something new of course. But how to tackle this? It's important to me that jsPanel v4 remains free of any dependencies, runs in browsers down to IE11 and that I understand the code ...

Any suggestions?

Regards,
Stefan

**Comment by qdot** [comment]
No prob! Happy to explain.

So, before I get into this, just want to make sure of what tools you're using. It looks like you're writing your code in the source directory, partially using the es6 version of Javascript (which allows for variable declarations using 'let', etc). However, in the dist directory, it's in es5 (using var, etc.). Are you using babel/browserify/something else to do that change?

**Comment by Flyer53** [comment]
Yep ...
+ The `source` directory has all the files I do my coding with. ES6 as far as I can understand/handle it and as long as it can be transpiled to ES5.
+ Transpiling is done with Babel using `presets: ['env']`
+ Minification is done with Uglify
+ The`dist` directory with all the production files is created using Gulp

I don't have any experiance with browserify, webpack and the like.
As already said, knowing that a concept "modules" exsists is about all I know. But I do know that now modules are available in native javascript. So it seems natural to me that this would be the way to go?

Just for info ...
Changes I'm working on:
`jspanel.js` currently has some code outside the declaration of the global `jsPanel` object. I want to move all this code inside the `jsPanel` object declaration.

**Comment by Flyer53** [comment]
@qdot 
Ok Kyle, I'm experimenting a bit and it seems to be quite easy to wrap my latest jsPanel4 code in a native ES6 module (including the extensions).
So maybe you should wait a few days until I can provide a simple demo page and a testpackage to download.
What do you think?

**Comment by qdot** [comment]
Sure, that'd be fine. I'm working with my own modified version for the moment. All I did was put an "export" in front of var jsPanel and it's worked well enough for me, though I haven't tried with plugins yet. I figured since you're using babel, it would probably handle the conversion of "export" to something that IE11 would ignore.

The other thing I needed was an entry point in package.json, which basically just means putting a line like 
```
"main": "./dist/jspanel.js",
```
in the package.json config. This allows node to autoimport a file, so we can do things like "import * from 'jspanel4'". 

Thanks!

**Comment by Flyer53** [comment]
@qdot 
Attached is a zip file with the latest jsPanel4 beta code as ES6 module. Files are not minified and the js is **not** transpiled to ES5. There might be issues, but I think it's ok for testing.
Another change: I replaced the jsglyph iconfont with corresponding svg icons -> no more fonts to load and no fonts directory anymore.

**Question:** There's a strange issue I currently have no idea how to fix. On touch devices using either the minimize or the close control will also trigger a handler for an element (not part of the panel) under the control. It seems to be connected to the implementation of the PointerEvent API.
On FF mobile for Android for example, where the PointerEvent API is not turned on yet everything is fine.
On Opera mobile for Android, where PointerEvent is turned on it happens only when using touch, but not with mouse. Same on Brave for Android.
Do you have any idea about this?

[es6module.jspanel.zip](https://github.com/Flyer53/jsPanel4/files/1642331/es6module.jspanel.zip)

**Comment by qdot** [comment]
@Flyer53 
Ok, finally got a chance to sit down and test the es6 version, things work great! Thanks for putting that together.

I was already bundling fonts with webpack in my own project, but SVG should work fine too. :)

I'm not sure about the pointerevent issues. I only have an iphone for mobile testing at the moment, and things seem ok enough on there, not sure why events are firing under the panel, sounds like it might be a Webkit or Blink bug?

**Comment by Flyer53** [comment]
Sounds good :)
There're still a few minor issues to take care of though ...

I'll probably drop the use of the PointerEvent API and stick with Touch/Mouse for the time being.

Might have a beta.3 in a few days ...

**Comment by Flyer53** [comment]
@qdot 
Hey Kyle ... just released v4.0.0-beta.3
+ the release includes a new folder **es6module** containing all files needed to run jsPanel4 as native ES6 module
+ `package.json` is updated with the key `main` ponting to `jspanel.js` inside the folder **es6module** (not to dist)
+ although all js files are ES6 modules the remaining code is still compiled to ES5 using Babel. Minification is now done with babel-minify

Let me know how it works out ...
