### ISSUE TITLE
How to reposition floating panels when dragging window size

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#92]
Hi, I have this minor issue.

If I resize my screen manually by dragging the edges of my browser (chrome), everything adjusts to the new location, except the small floating panels (jsPanel4) that I have opened on my site using your script.

How can I make them responsive to screen size?

Regards

**Comment by Flyer53** [comment]
@inglesuniversal 
Hi there,
take a look at option [onwindowresize](https://jspanel.de/api.html#options/onwindowresize) which will reposition a panel on a window resize event depending on settings. If you also need to resize a panel you'll need to use option `onwindowresize` with a function.

**Comment by Flyer53** [comment]
@inglesuniversal 
Hi Hugo,
I would really appriciate if you gave me some kind of feedback whether it did help you or not ...
Otherwise I consider this question answered and close the issue.
Regards, Stefan

**Comment by inglesuniversal** [comment]
Deeply sorry... I was away from the office... I did work perfectly. I'm still making some tests... and I will surely write again soon.

**Comment by Flyer53** [comment]
@inglesuniversal 
Hi Hugo,
Any news? Did you find some time to make your tests?

**Comment by inglesuniversal** [comment]
I will send you a test link soon so you can tell me if that is the expected behavior. Thanks for your Awesome Support!!!!

**Comment by Flyer53** [comment]
@inglesuniversal 
Hi Hugo,
again 2 months passed ... any news?

**Comment by inglesuniversal** [comment]
Please allow me to run this test this very week

**Comment by Flyer53** [comment]
@inglesuniversal 
Dear Hugo,
Again another 5 weeks passed since my last message. That's more than 6 months now since my first response to your request.
I guess I'll close this issue pretty soon then ...

**Comment by inglesuniversal** [comment]
Test Completed with FLYING COLORS!!!!

Amazing onwindowresize works like a charm on Chrome (current release)

Bravo!!!!
