### ISSUE TITLE
iframe initiation issue

### ISSUE THREAD

**Issue by phillf** [Flyer53/jsPanel4#93]
Created an iFrame to provide easy reference of Radio Codes for OpenCAD using jsPanel. When a user triggers the panel it will show itself and the page will dim but the panel will also dim and they cannot manipulate the panel or the content inside of said panel.

https://jira.opencad.io/secure/attachment/14104/capture-for-jira-screenshot-20190704-060752-584.png

`mdt.php?dep=police:1454 Uncaught (in promise) DOMException
success @ mdt.php?dep=police:1454
i @ VM1820 jquery.min.js:2
fireWith @ VM1820 jquery.min.js:2
z @ VM1820 jquery.min.js:4
(anonymous) @ VM1820 jquery.min.js:4
load (async)
send @ VM1820 jquery.min.js:4
ajax @ VM1820 jquery.min.js:4
getStatus @ mdt.php?dep=police:1430
(anonymous) @ mdt.php?dep=police:1147
i @ VM1820 jquery.min.js:2
fireWith @ VM1820 jquery.min.js:2
ready @ VM1820 jquery.min.js:2
J @ VM1820 jquery.min.js:2
mdt.php?dep=police:1452 Uncaught (in promise) DOMException
success @ mdt.php?dep=police:1452
i @ VM2147 jquery.min.js:2
fireWith @ VM2147 jquery.min.js:2
z @ VM2147 jquery.min.js:4
(anonymous) @ VM2147 jquery.min.js:4
load (async)
send @ VM2147 jquery.min.js:4
ajax @ VM2147 jquery.min.js:4
getStatus @ mdt.php?dep=police:1428
(anonymous) @ mdt.php?dep=police:1145
i @ VM2147 jquery.min.js:2
fireWith @ VM2147 jquery.min.js:2
ready @ VM2147 jquery.min.js:2
J @ VM2147 jquery.min.js:2`

I receive the above errors in my console. I think there might be a conflict but I am not sure where if there is one.

EDIT: It would help if I provided a link to the source... duh. https://repo.opencad.io/users/pfernandes/repos/opencad-php/browse?at=refs%2Fheads%2Ffeature%2FOCPHP-192. The page in question is codeReference.php

Ref: https://jira.opencad.io/browse/OCPHP-192

**Comment by Flyer53** [comment]
Hi Phill,
in the error msg you posted I can't see anything pointing to jsPanel as cause of this issue.
And why do you think it's related to the iframe?

What kind of panel is it? As far as I see it it's not a modal jsPanel. So where does the "backdrop" fading out the page come from? Could it be that it's just a z-index thing ... the backdrop element having a higher z-index than the panel and thus blocking out the panel?

Regards,
Stefan

**Comment by Flyer53** [comment]
@phillf 
You didn't respond to this issue for 4 weeks now.
Anything to say on this ... or is it simply irrelevant by now?
