### ISSUE TITLE
How do I add Jspanel to href class element

### ISSUE THREAD

**Issue by Horlaes** [Flyer53/jsPanel4#95]
First off, thanks for the fantastic library, you are a God sent!

My question: I am creating a virtual piano whereby if I click a button or an element, Jspanel should pop-up, I already converted the code into the container, and everything seems to be working fine except for the button. Thanks, and I'll greatly appreciate:

This is how I have structured Js panel:

```
var myvar = '<div class="keyboard-options">'+
'Sound'+
'<select ID="sound">'+
'	<option value="0" selected>Keyboard</option>'+
'	<option value="1">Organ</option>'+
'    <option value="2">Acoustic Guitar</option>'+
'    <option value="3">Lead!</option>'+
'</select>'+
'<div ID="keyboard" class="keyboard-holder"></div>'+
'<div class="keyboard-options">'+
'Range [C<span ID="OCTAVE_LOWER">3</span>-B<span ID="OCTAVE_UPPER">5</span>]'+
'<input type="button" ID="-_OCTAVE" value="-" />'+
'<input type="button" ID="+_OCTAVE" value="+" /><br />'+
'<i>(Use left/right arrows to adjust with keyboard)</i>'+
'</div>'+
'<div id="notesPlayed" class="notesPlayed"></div><div id="notesPlayedhidden" style="display:none"></div> <button id=\'playback\' disabled>Playback</button> <button id=\'clear\' disabled>Clear</button>'+
'</div>';
jsPanel.create({
      position: {
   		my: 'center-bottom',
      at: 'center-bottom',
      offsetX: 5,
      offsetY: 45
  },
closeOnEscape: true,
    theme:       'dark',
    headerTitle: 'Virtual Piano',
    contentSize: '450 250',
  content: myvar
});
    </script>
```

How do I attach it to this: 
```
<a class ="audiosynthbtn" id = "must-hide">Audiosynth</a>
```

 so when clicked, Jspanel should pop-up

Edit: I have tried the option container, didn't work for me

**Comment by Flyer53** [comment]
If I get you right you want the `a` element to be the "button" that opens the jsPanel on click. Is that correct?
Modify the a like
```javascript
<a href="#" class="audiosynthbtn" id="must-hide">Audiosynth</a>
```
and then add the click handler:
```javascript
document.getElementById("must-hide").addEventListener("click", function(e){
  // prevent default behaviour of a element
  e.preventDefault();
  // create panel
  jsPanel.create({
    position: {
      my: 'center-bottom',
      at: 'center-bottom',
      offsetX: 5,
      offsetY: 45
    },
    closeOnEscape: true,
    theme:       'dark',
    headerTitle: 'Virtual Piano',
    contentSize: '450 250',
  content: myvar
  });
});

**Comment by Horlaes** [comment]
Thanks for your super fast reply, I am currently checking the code, and I'll report back on how it goes

**Comment by Horlaes** [comment]
Doing what you suggested worked but I lost the actual application, I am only seeing the CSS I applied and not the actual content: myvar codes

**Comment by Flyer53** [comment]
Did you forget to set the value for"myvar"?

**Comment by Horlaes** [comment]
I set the value; screenshot of what I got https://prnt.sc/okrzm3 , and this is what I expected https://prnt.sc/oks0u4 , This is the fiddle https://jsfiddle.net/Faruqa97/82f4qxja/4/

**Comment by Flyer53** [comment]
The fiddle works fine on my machine using Firefox
![06](https://user-images.githubusercontent.com/6769021/61995557-71a31780-b08a-11e9-8ece-0e378f2f2326.jpg)

**Comment by Flyer53** [comment]
Ok, when you add the click handler for the button is does not work as expected. the div `#keyboard` is not populated with any HTML.
Probably the div `#keyboard` is populated with the jacascript you're running when the page loaded. In your sample code the panel is already there. But when the panel is closed and reopened with the button the div `#keyboard` has to be populated again -> the corresponding js has to run again, which it doesn't. At least thats what I guess. So you would have to move the code populating the div `#keyboard` to the callback of the panel like:
```javascript
jsPanel.create({
    theme:       'primary',
    headerTitle: 'Virtual Piano',
    position:    'center-top 0 58',
    contentSize: '450 250',
    content: myvar,
    callback: function(panel) {
      // code to setup the keyboard ...  
    }
});
```

**Comment by Horlaes** [comment]
It seems I didn't save the one I added the click handler to, and I expect it to work since the javascript object is of a singleton class, I have achieved the result with js modal, but I just love your library, so sleek, draggable, and I would spend a month getting it to work ;) 

Look at the initial one I did with a modal https://jsfiddle.net/Faruqa97/hf0urLbx/, between, I moved the code into the panel, and didn't work too. this is it:  https://jsfiddle.net/Faruqa97/82f4qxja/16/

**Comment by Flyer53** [comment]
Thanks that you like it so much 😄 
You now put the HTML in the callback. That's not necessary, it's already there (the value of `myvar`).

But there must be some code that fills `<div ID="keyboard" class="keyboard-holder"></div>` with the actual HTML needed to display the keyboard. That's probably some js and that's what needs to be in the callback.

Look at the comment I put in the code sample below
```javascript
jsPanel.create({
    theme:       'primary',
    headerTitle: 'Virtual Piano',
    position:    'center-top 0 58',
    contentSize: '450 250',
    content: myvar,
    callback: function(panel) {
      // remove all js from the javascript pane of your fiddle and put the javascript in here
    }
});
```
[Here is a working fiddle](https://jsfiddle.net/flyer53/qrvjuhg1/3/)
That can sure be optimized ... but it works ...

**Comment by Flyer53** [comment]
Updated the fiddle: https://jsfiddle.net/flyer53/qrvjuhg1/6/

**Comment by Horlaes** [comment]
You are a real master man, may you live long in peace and dough ;). It worked like charmmmmmm! Is it possible to call the panel more than once, like having two buttons or more

**Comment by Flyer53** [comment]
That's absolutely possible.
**But requires a bunch of changes in the javascript creating the keyboard because it uses only ID attributes. And you know that a specific ID may appear only once in a single document.**
Where did you get the script from?

So I modified the script to use classnames instead of IDs.

Here is the demo creating 2 panels: https://alpha.jspanel.de/docs/demos/faruq/

**Comment by Horlaes** [comment]
It's actually an open-source script I have been re-working to soothe a WordPress website, this the link to the script http://www.keithwhor.com/music/ I notices you are using query selector to target the class names, and it actually worked if a certain button is clicked more than once. 

The issue I have now is that if I create a new button with the same class (I changed the i.d to class), it won't pass the function to the new button, is there a way to destroy the first function, and pass it to the new button, this is the current fiddle I have been trying to get for over 7 hours https://jsfiddle.net/h8ymqpw2/42/

Thanks for your help man, I owe you a lot

**Comment by Flyer53** [comment]
Ok, the buttons creating the panel should have an ID. Otherwise it's more work to identify them.

I reworked the demo which now shows 3 buttons, each one creating a new panel with a keyboard.
+ I separated the js in separate files (so the js loads only once)
+ put the css in a separate file
+ put the template for the panel content in a separate file

The only thing not working as expected is the playback. Playback works, but always in the first panel opened.

https://alpha.jspanel.de/docs/demos/faruq/

**Comment by Horlaes** [comment]
This is exactly how I want it to work, many thanks, and I am super happy it worked. Yh, the playback should work only on one panel. as users should only be working on a single panel at a time, so that's no problem. 

I will need more info about you, I need to credit you. Also, just followed you on twitter

**Comment by Horlaes** [comment]
I finally got it to work without separating any files, 

Since the queryselector only selects a single element, and that would only work for the first element, or returns null if no element is found. I added the event listener on a parent container, which means I changed the markup and added the button as a child element. 

Using, `queryselector` on the parent container assumes I have a selector on each child, voila. here is the fiddle: https://jsfiddle.net/h8ymqpw2/43/

**Comment by Horlaes** [comment]
Updated one with playback only playing once fixed: https://jsfiddle.net/h8ymqpw2/44/

**Comment by Flyer53** [comment]
Ok, when that's what you want ... fine :)
But why 3 buttons that create exactly the same panel with the same setup? Clicking the first button 3 times results in exactly the same 3 panels.
And I would recommend to think about having css, js and the keyboard template in separate files as in my last demo. Would be a lot easier to maintain when parts of the code have to be updated for example.

**Comment by Horlaes** [comment]
I really love the last demo you sent but the issue I have is I don't have an idea on how to turn the ajax URL 'keyboard_template.html' into an actual URL (I know nothing about ajax).

I am working on Wordpress and the only way I think that could work is if I have a URL like so http://demo/keyboard_template.html into the actual ajax URL, any workaround for that?

Also, I have been playing with your panel editors, you are a really a God sent.

**Comment by Flyer53** [comment]
The AJAX thing should not be a problem. The file `keyboard_template.html` in my demo has to be somwhere on my server and therefore it has a URL, either relative or absolute. So the `configAjax` part in the panel configuration could also look like:
```javascript
// with an absolute URL
contentAjax: {
  url: 'https://jspanel.de/docs/demos/faruq/keyboard_template.html',
  done: function (panel) {
      panel.content.innerHTML = this.responseText;
      new AudioSynthView(panel).draw();
  }
}

// or with a relative URL
contentAjax: {
  url: './keyboard_template.html',
  done: function (panel) {
      panel.content.innerHTML = this.responseText;
      new AudioSynthView(panel).draw();
  }
}
```
But the more important issue I think is to keep the few hundred lines of js out of the panel configuration. If you load the AudioSynth and Keyboard generating javascript in a `<script>` tag it's loaded only once on pageload. The way you do it it's loaded (and parsed) every time you create a panel with the keyboard. Look at the code needed to create the panel in my demo ...
```javascript
 jsPanel.create({
     position: 'left-top 150 170',
     contentSize: '920 400',
     contentAjax: {
         url: 'keyboard_template.html',
         done: function (panel) {
             panel.content.innerHTML = this.responseText;
             new AudioSynthView(panel).draw();
         }
     },
     headerTitle: 'Virtual Piano',
     headerControls: 'sm',  // see note below
     theme: 'success filledlight'
 });
```
and compare it to the code you need in your demo. What is easier to handle and maintain?

**Note:** `headerControls: 'sm'` works only when you update to jsPanel v4.7.0 (your pen still uses v4.6.0)

**Comment by Horlaes** [comment]
Exactly, I already tried it with an absolute URL, and it didn't work for me. I separated the script, and it's now on my server, check it out https://codepen.io/horlaes/pen/vogeYG

**Comment by Horlaes** [comment]
Okay, solved it by downloading a chrome extension to allow CORS: Access-Control-Allow-origin. Many thanks, man, you are a superstar! 

Since it only allows access from a single origin, I believe it should work out-of-the-box from my server when implemented right?

Also, should I just copy your info on here, and use for credit purposes on my end.

**Comment by Flyer53** [comment]
👍 Yes, once you have it on your server CORS is not an issue anymore.
Glad I could help!
Well, when it's a publicly available site I would appreciate if you note using jsPanel somewhere.
And a link, so I can see your work would be nice also ...

**Comment by Horlaes** [comment]
Would update you on with a link in a few hours, and would for sure add a link pointing to Jspanel (Honestly, I haven't seen someone generous and brilliant for years, you're really a badass)

**Comment by Horlaes** [comment]
Here we go Stefan shorturl.at/gJT16 , thanks a lot for the panel. 

I noticed it's kinda laggy on mobile but that's no issue. I credited you at the start of the guide, and also a footnote link + credit at the bottom of the page, check and let me know if I should change anything.

**Comment by Flyer53** [comment]
All fine Ahmed 👍 
Just the spelling: it's **jsPanel**, not Jspanel. Not that I'm picky, but you want to do it right ... don't you 😏 
If something comes up you can also mail me directly: info@jspanel.de

**Comment by Horlaes** [comment]
Oh sorry, I have corrected the typo, thanks for that. Of course, I wanna do it right ;) Who doesn't want something nice, any idea on how to make it better?
