### ISSUE TITLE
Zoom picture and magnifier (not jsPanel related)

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#96]
Hello Stefan 
I will be glad to get help or advice from you.

The document I present in the web has some images that the student has inserted, 
and I display them as part of the document.
The problem is that sometimes images are small and unreadable, 

and I must provide
1.  Increase the image to the size of the size of viewport (screen).
2. Option to allow the advisor(client) to zoom the
 image and move left or right up if the magnification exceeds the screen's limits.

Thank you and good day
your
Hefner Avi

**Comment by Flyer53** [comment]
Hi Avi,
As you know I'm always willing to help ... if I can.
But how is this related to jsPanel?
Do you plan to show the images in a jsPanel?
Did you try anything already?
How about an existing library? Did you search for one yet? I'm sure there's something out there.

Best Regards,
Stefan

**Comment by AviHafner** [comment]
Hi Stefan
My Question Not Really related to jsPanel?

But your opinion as my friend and one of  my Best technical good advisors,
important to me.

I have built an example with a solution to my question and would be happy if you could consider checking it.

The example in the following link :
https://www.admin.technion.ac.il/avi/

Please click on the picture , and after it , use the slider

Yours
 Avi Hefner

**Comment by Flyer53** [comment]
Hi Avi,
looks like you have a working solution that takes care of the zooming.
So the only thing missing is a way to drag the image around. Correct?

**Comment by AviHafner** [comment]
Hey, Stefan, you're right.

I don't know how   in the panel I can let the user to drag the image left or right up or to Down.
I'd appreciate it, can you have any advice for me or a hint?

Yours 
Avi Hafner

**Comment by Flyer53** [comment]
Do you, or can you use jQuery?
If so [here](https://css-tricks.com/snippets/jquery/draggable-without-jquery-ui/) would be a simple drag function you could implement to drag the image inside the panel.

Btw: I get an error `ReferenceError: output is not defined` when I try to zoom the image in your example

**Comment by Flyer53** [comment]
Hi Avi,
I created a simple example with a single jsPanel having only an image as content and the image inside the content section is draggable. Just take a look at the source code to see how I've done it.
https://alpha.jspanel.de/docs/demos/avi/

Best Regards,
Stefan

**Comment by AviHafner** [comment]
Its looks amazing

I'm going to test it,
After it,
I am going to return to you with my full impression
After checking that in my testing environment .

Yours 
Avi Hafner
.

**Comment by AviHafner** [comment]
Hi stafen 
**It’s perfect and amazing**.

I have 2 projects,
one is for the advisors and I am using Jquery .
And the other one for students where I use pure JavaScript,
And in the future when development pressure has dropped slightly,
I will Translate the code into pure JavaScript.
I added to $.fn.drags  mouseout event.

My latest example : 
https://alpha.jspanel.de/docs/demos/avi/



**You are perfect and amazing**.

Yours 
Avi Hafner

**Comment by Flyer53** [comment]
My pleasure Avi 👍 
Just one request for the future: If you have a request not directly related to jsPanel please mail me via **_info@jspanel.de_**. The GitHub repo should be limited to issues directly related to jsPanel.
Yours, Stefan 😄
