### ISSUE TITLE
Layout extension sometimes restores wrong position

### ISSUE THREAD

**Issue by keenhon** [Flyer53/jsPanel4#98]
Hi,

I am new to jsPanel and what a wonderful work you have done.

I was trying to save layout and restore. However I think I may have found a bug. After my panels are restored, if I only adjust one of the panel, and then do save layout again. Only that panel is saved. When I restore, the rest of the panels went back to default.

**Comment by keenhon** [comment]
I did some check on the code. Should add the two bolded lines to fix the issue

          var useConfig = Object.assign({}, config, savedConfig);
          var restoredPanel = jsPanel.create(useConfig);
          restoredPanel.style.zIndex = savedConfig.zIndex;
          restoredPanel.style.left = storedpanel.left;
          restoredPanel.style.top = storedpanel.top;
          **restoredPanel.currentData.left = storedpanel.left;
          restoredPanel.currentData.top = storedpanel.top;**
        return restoredPanel;

**Comment by Flyer53** [comment]
@keenhon 
Thanks for the praise :)
... and for your report. I'll check that out next week since I'm on vacation for a few more days.
Regards,
Stefan

**Comment by Flyer53** [comment]
@keenhon 
There indeeed seems to be some bug I'll have to investigate further. But the coming release 4.8.0 will probably not have the fix for this issue already.

**Comment by Flyer53** [comment]
@keenhon 
I just uploaded a new v4.9.0-alpha.8 which includes an updated layout extension.
The issue you reported seems to be fixed, some more testing needed though. In addition the layout extension now saves/restores panel status (minimized, maximized etc.)

Docs: https://alpha.jspanel.de/api.html#extensions/layout
Download: https://alpha.jspanel.de/downloads/jspanel-4.9.0-alpha.8.zip

I would highly appreciate if you gave it a try. And some feedback would be great as well 😏

**Comment by Flyer53** [comment]
fixed with v4.9.0 release
